### ISSUE TITLE
How to increase point size when drawing a polygon

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-draw#1001]
**mapbox-gl-js version**:1.11.0
**mapbox-gl-draw version**:latest

### Steps to Trigger Behavior

 1. import MapboxDraw from '@mapbox/mapbox-gl-draw'
 2. create a draw handler:
this.drawingManager = new MapboxDraw({
      displayControlsDefault: false,
      controls: {
        polygon: true,
        trash: true
      },
      styles: theme
    })
 3. click draw polygon and then draw a polygon on map

### Expected Behavior
I want the point size to be bigger
### Actual Behavior
very small, hard to select
<img width="657" alt="Screen Shot 2020-07-30 at 12 44 18 PM" src="https://user-images.githubusercontent.com/13723721/88967476-bbf14280-d262-11ea-86b7-2d874c315d1b.png">

**Comment by caiusCitiriga** [comment]
Any news on this? I'd love to see how this can be accomplished too ❤️

**Comment by usb248** [comment]
Change `circle-radius` value in paint property simply ...

**Comment by tejasdotchavan** [comment]
> Change `circle-radius` value in paint property simply ...

Could you give us an example/ point to documentation?

**Comment by 321ckatz123** [comment]
@tejasdotchavan 

https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/EXAMPLES.md

    // vertex point halos
    {
      "id": "gl-draw-polygon-and-line-vertex-halo-active",
      "type": "circle",
      "filter": ["all", ["==", "meta", "vertex"], ["==", "$type", "Point"], ["!=", "mode", "static"]],
      "paint": {
        "circle-radius": 5,
        "circle-color": "#FFF"
      }
    },
    // vertex points
    {
      "id": "gl-draw-polygon-and-line-vertex-active",
      "type": "circle",
      "filter": ["all", ["==", "meta", "vertex"], ["==", "$type", "Point"], ["!=", "mode", "static"]],
      "paint": {
        "circle-radius": 3,
        "circle-color": "#D20C0C",
      }
    },

Change those circle-radius values to whatever you want.
