### ISSUE TITLE
Cannot load a drawn map

### ISSUE THREAD

**Issue by rosshulford** [mapbox/mapbox-gl-draw#1009]
I create an area as per the example and I save all the points as a 'feature'.

https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

Going back into the map I would like a user to edit this area. I try and load the feature into the map, it draws a polygon but I do not have any of the control points for editing.

How do I allow user to edit a drawn area which was previously saved? I assume there must be an setting but there is nothing I can find in the api?

     let feature = {
          id: "03542671a33354aa988e8f87999041c1",
          type  : "Feature",
          properties: {},
          geometry: {
            type: "LineString",
          coordinates: [
            [
              -97.89407420158425,
              38.935035015195325
            ],
            [
              -98.10006785392693,
              38.92862536476278
            ],
            [
              -98.10693430900587,
              38.858080987258774
            ],
            [
              -98.00966948212873,
              38.82462661507586
            ],
            [
              -97.94659042424455,
              38.827315670056066
            ],
            [
              -97.93491745061198,
              38.85833448529365
            ],
            [
              -97.93491745061198,
              38.8722350814937
            ],
            [
              -97.90264511174541,
              38.89414972989536
            ],
            [
              -97.89985566935775,
              38.91675861239864
            ],
            [
              -97.89779573283425,
              38.927442828360256
            ],
            [
              -97.89436250529523,
              38.93385258565132
            ],
            [
              -97.89407420158425,
              38.935035015195325
            ]
          ],
        }
        }
      draw.add(feature)

**Comment by KhairulislamLinkon-TomTom** [comment]
you can change the mode to active the editing. On `direct_select` will allow to edit the shape and delete vertex of the polygon.
`draw.changeMode('direct_select', {
  featureId: '03542671a33354aa988e8f87999041c1'
});`
