### ISSUE TITLE
Can't change button title on Polygon tool

### ISSUE THREAD

**Issue by ryanm** [mapbox/mapbox-gl-draw#1018]
The button title on the Polygon tool is set [here](https://github.com/mapbox/mapbox-gl-draw/blob/3e2f29f0b76ec5f1fd912081bbee9ec68de9bf69/src/ui.js#L122) as "Polygon tool (p)". How do I change that to (like) "Draw" or "Polygon"? I could fork mapbox-gl-draw just to make that change, but would prefer not to have to do that.

**mapbox-gl-draw version**: 1.1.2

### Steps to Trigger Behavior

 1. Add polygon control
 2. Hover polygon button

### Expected Behavior
Text "Draw" appears

### Actual Behavior
Text "Polygon tool (p)" appears

**Comment by avpeery** [comment]
@ryanm this issue tracker is focused on bug reports and feature requests, so although we’re glad to point you in the right direction we can’t offer general support in this channel. For “how to” questions like this, I suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!
