### ISSUE TITLE
Build error with ES6 import

### ISSUE THREAD

**Issue by pomm0** [mapbox/mapbox-gl-draw#1021]
**mapbox-gl-js version**: 1.12.0
**mapbox-gl-draw version**: 1.2.0

### Steps to Trigger Behavior

 1. Clone https://github.com/pomm0/mapbox-issue and install dependencies `npm install`
 2. Start ember server with `npm run start`

### Expected Behavior

Import should work with `import MapboxDraw from '@mapbox/mapbox-gl-draw';`

### Actual Behavior

Build error:
![image](https://user-images.githubusercontent.com/6084030/98116752-01985980-1ea9-11eb-886b-9955c4521ed2.png)

Also mentioned at https://github.com/mapbox/mapbox-gl-draw/issues/997#issuecomment-663260146

Is working with version 1.1.0 of mapbox-gl-draw and importing like so `import MapboxDraw from '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw';` (As written in https://github.com/mapbox/mapbox-gl-draw/issues/844)

As far as I interpret this, this has nothing to do with `ember.js` or the `ember-auto-import` plugin what allows importing npm modules inside `ember.js`.

Without `import MapboxDraw from '@mapbox/mapbox-gl-draw';`, build is working, so it should be related to mapbox-gl-draw

**Comment by pomm0** [comment]
well, looks like related to https://github.com/mapbox/mapbox-gl-draw/issues/970

**Comment by nrgapple** [comment]
I am getting this issue too with `react-mapbox-gl-draw`. [Here is a codesandbox with the issue](https://codesandbox.io/s/react-mapbox-gl-draw-error-chdf9?file=/pages/index.js)

**Comment by nrgapple** [comment]
@pomm0 why did you close this?

**Comment by pomm0** [comment]
> well, looks like related to #970

Because there is already a [open issue](https://github.com/mapbox/mapbox-gl-draw/issues/970) for that
