### ISSUE TITLE
Black editing polygon not removed on Draw.clear(), and Draw.clearAll is not a function

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-draw#104]
If I have a black editing polygon showing when Draw.clear() is run, the black polygon will still remain - I think it should also be removed?

Also, Draw.clearAll() gives me an error (Draw.clearAll is not a function)

**Comment by kelvinabrokwa** [comment]
I am deprecating `clearAll` since there is no longer history functionality. I will make sure to update the docs accordingly. 

As for the `clear()` I will investigate but it might be an upstream bug in mapbox-gl.

Thanks :smile:

**Comment by joedjc** [comment]
No problem. By the way I noticed that the performance is way better after switching to mapbox-gl 0.11.3 so I guess there were some issues in how it was rendering geoJSON which were affecting it.

I also found that the drawing.start and drawing.end events don't seem to fire? However, edit.new works ok.

**Comment by kelvinabrokwa** [comment]
@joedjc `drawing.start` and `drawing.end` are firing on my machine. I can't seem to replicate your problem. Do you mind posting your code snippet?

**Comment by joedjc** [comment]
Ah - the answer is in your question! In the API documentation it says to use 'draw.start' and 'draw.end', which I was using, when it should be 'drawing.start'/'drawing.end'. If I use 'drawing' its ok.

So just need the documentation updating or the method changed to match it.

**Comment by kelvinabrokwa** [comment]
@joedjc I've fixed the docs as of 4cf4546cd7287bb9bdf62549cf78c4fdce49d135. Thanks!
