### ISSUE TITLE
drawing polygon shows the outline of the tile

### ISSUE THREAD

**Issue by hahaxiaowai** [mapbox/mapbox-gl-draw#1045]
**mapbox-gl-js version**: 1.X
**mapbox-gl-draw version**:1.2.2

### Steps to Trigger Behavior
Hi! 
I just initialized it and did nothing， why?
![image](https://user-images.githubusercontent.com/49934348/113119322-e60c6180-9242-11eb-8f43-8bb817a6b5d6.png)

**Comment by avpeery** [comment]
Hi @hahaxiaowai unfortunately it's not clear what you're trying to achieve from your brief description. This issue tracker is for reporting bugs and requesting features. We cannot offer general support in this channel. For "how to" questions like this, I suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!
