### ISSUE TITLE
Hello, does MapBox support drawing a circle or a fan?

### ISSUE THREAD

**Issue by 18792564007** [mapbox/mapbox-gl-draw#1046]
Hello, does MapBox support drawing a circle or a fan?

**Comment by kashalkar** [comment]
Not that I am aware of...

However, you can add your own custom modes 
https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/MODES.md
or 
have a look at this project https://github.com/iamanvesh/mapbox-gl-draw-circle#readme
