### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by gstf** [mapbox/mapbox-gl-draw#105]
When not using lineStringCtrl, polygonCtrl, squareCtrl or markerCtrl this line throws the error in the title.

https://github.com/mapbox/gl-draw/blob/46d69fdbf6d83a7847133dbb9077995dba588f39/src/draw.js#L384-L387

**Comment by kelvinabrokwa** [comment]
done in https://github.com/mapbox/gl-draw/commit/c5a951db398d903ea59aa1387db511ccc92acf29

**Comment by gstf** [comment]
I don't think this is fixed. The issue is here https://github.com/mapbox/gl-draw/blob/master/src/draw.js#L389-L392 and appears when not using all controls when initiating Draw. Example:

```
    let draw = this.draw = glDraw({
      position: 'bottom-right',
      keybindings: true,
      geoJSON: [],
      controls: {
        square: true,
      }
    });
```

``this.lineStringCtrl``, ``this.polygonCtrl`` and ``this.markerCtrl`` will then be undefined and throws a TypeError when accessing classList.

**Comment by kelvinabrokwa** [comment]
@gstf oh no! I'll fix this as soon as possible.

Thank you :smile:

**Comment by gstf** [comment]
:+1: thanks!
