### ISSUE TITLE
Remove dependency on @mapbox/geojsonhint

### ISSUE THREAD

**Issue by ThisIsMissEm** [mapbox/mapbox-gl-draw#1051]
**mapbox-gl-js version**: n/a
**mapbox-gl-draw version**: all

### Issue

Currently this package (mapbox-gl-draw) depends on the `@mapbox/geojsonhint` package, which has been marked as deprecated in npm: https://www.npmjs.com/package/@mapbox/geojsonhint

This also introduces some security vulnerabilities via the dependency chain of `@mapbox/geojsonhint`. As far as I can tell, this package is only used to perform validation of geojson via the `add` API: https://github.com/mapbox/mapbox-gl-draw/blob/main/src/api.js#L77-L80

The recommendation from `@mapbox/geojsonhint` is to perform validation some other way; Removing the deep integration here would only have a minor affect on usability of this module, as only the `add` method did validation of the geojson, and all others didn't.

If you would like a PR to remove this dependency, please let me know and I'll prepare one.

**Comment by ThisIsMissEm** [comment]
This would be a fix to the security issue in the current version (1.2.2) of the package, https://app.snyk.io/test/npm/@mapbox/mapbox-gl-draw/1.2.2?tab=issues

**Comment by StevenLangbroek** [comment]
Is... is that really desired? No longer validating geometry before it's added? That seems like it would need to be a breaking change? Are there alternative libraries perhaps?

**Comment by ThisIsMissEm** [comment]
> Is... is that really desired? No longer validating geometry before it's added? That seems like it would need to be a breaking change? Are there alternative libraries perhaps?

It would be a breaking change — but surely this library should expect only valid GeoJSON geometries would be passed to it? There are other libraries if you want to fully validate GeoJSON: https://www.npmjs.com/package/geojson-validation

**Comment by ThisIsMissEm** [comment]
But also, the set method, which allows passing a FeatureCollection, does not do the same sort of validation anyway.
