### ISSUE TITLE
is there a function could be used when I use draw_line_string to make sure My end Point is my needed point which has required elements

### ISSUE THREAD

**Issue by Roxannej** [mapbox/mapbox-gl-draw#1057]
**mapbox-gl-js version**:
**mapbox-gl-draw version**:

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by avpeery** [comment]
Hi @Roxannej. Were you able to find a solution to your problem? This issue tracker is used for bug reports and feature requests, so although we’re glad to point you in the right direction we can’t offer general support in this channel. For “how to” questions like this, I suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks.
