### ISSUE TITLE
How to change styles after finished one shape programmatically?

### ISSUE THREAD

**Issue by ZijianZhang991203** [mapbox/mapbox-gl-draw#1058]
Hi, I am trying to let users draw on the map and each shape needs to be in different color. The method I found rn to change color is to get a certain featureId and then change the styling. But, how do I change the styles for the next shape I am about to draw? Thanks for any kind of help.

**Comment by Userluckytian** [comment]
![image](https://user-images.githubusercontent.com/66506773/124208382-02f25280-db1a-11eb-87cc-2c22bf0a9809.png)

通过map.getStyle().layers。 你可以获取到所有的图层，找到你绘制并添加的图层id，然后修改它。

**Comment by mengshucc** [comment]
why that I change the color by `map.setPaintProperty()` then the polygon's color repaint like starting.

**Comment by avpeery** [comment]
@ZijianZhang991203 Were you able find a solution to your problem? Generally, this issue tracker is focused on bug reports or feature requests. For “how to” questions like this, I suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!
