### ISSUE TITLE
What does the benchmark look for

### ISSUE THREAD

**Issue by YeomanYe** [mapbox/mapbox-gl-draw#1061]
Thank you very much for providing this tool, it is very useful for me.But I have some doubts about this tool.What are your benchmarks based on? (the amount of data, method of measurement, indicator of measurement and so on)

**Comment by avpeery** [comment]
Hi @YeomanYe Thanks again for your questions. The issue tracker is focused on bug reports and feature requests. To help point you in the right direction, here is [file location](https://github.com/mapbox/mapbox-gl-draw/tree/main/bench) of the benchmarking tools in mapbox-gl-draw. Thanks!
