### ISSUE TITLE
Architectural issues

### ISSUE THREAD

**Issue by YeomanYe** [mapbox/mapbox-gl-draw#1062]
Thank you very much for providing this tool, it is very useful for me.But I have some doubts about this tool.I want to realize the synchronization of several feature edits, such as dragging points and changing the length of lines. However, I haven't found a way to realize it in the tool library. Is there any architecture diagram of this library? I want to learn it and do secondary development based on it.

**Comment by avpeery** [comment]
Hi @YeomanYe thanks for your question. Here is the documentation for the [mapbox-gl-draw API](https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/API.md). In general, this issue tracker is focused on bug reports and feature requests, so although we’re glad to point you in the right direction we can’t offer general support in this channel. Thanks!
