### ISSUE TITLE
Can this be used on images, not just maps?

### ISSUE THREAD

**Issue by dmitrycreator** [mapbox/mapbox-gl-draw#1067]
You have a very cool area selection implementation, and I would like to try using your project using an image instead of a map. Tell me, is it possible? Do you have examples of this implementation?

**Comment by SnailBones** [comment]
@DmitryAk I'm not exactly sure what your use case is, but I think it's possible since Mapbox GL JS can be used with images. Here's an [example](https://docs.mapbox.com/mapbox-gl-js/example/georeference-imagery/).

**Comment by avpeery** [comment]
@dmitrycreator Checking in to if you needed more clarity (if so, could you provide more information about the use-case?). I will close this issue if @SnailBones example was helpful. Thanks!
