### ISSUE TITLE
how to show the length of polygon edge while drawing

### ISSUE THREAD

**Issue by zhudaoruyi** [mapbox/mapbox-gl-draw#1086]
how to show the length of polygon edge while drawing, like this:

![ani](https://user-images.githubusercontent.com/20452000/147228140-20717c9f-d7aa-433f-9ca1-489bed369f23.gif)

**Comment by zhudaoruyi** [comment]
It is easy to show area on the centroid of the polygon with the demo 

[https://github.com/mapbox/mapbox-gl-draw/issues/801](https://github.com/mapbox/mapbox-gl-draw/issues/801)

**Comment by zhudaoruyi** [comment]
solved

**Comment by creimers** [comment]
@zhudaoruyi How did you end up doing it? I'm facing the same challenge.
