### ISSUE TITLE
Existing features don't get rerendered on draw.set

### ISSUE THREAD

**Issue by wyozi** [mapbox/mapbox-gl-draw#1122]
**mapbox-gl-js version**: 2.10.0
**mapbox-gl-draw version**: 1.3.0

### Steps to Trigger Behavior

 1. Have custom style for feature based on user properties, e.g.
```
  {
    id: "draw-path-arrows",
    type: "symbol",
    filter: ["all", ["==", "$type", "LineString"], ["has", "user_arrows"], ["!=", "user_arrows", "none"]],
    layout: {
      'symbol-placement': 'line',
      'symbol-spacing': 20,
      'icon-allow-overlap': true,
      'icon-rotate': ['case', ['==', ['get', 'user_arrows'], 'fwd'], 0, 180],
      // 'icon-ignore-placement': true,
      'icon-image': 'arrow',
      'icon-size': 1,
      'visibility': 'visible'
    },
  },
```
 2. Change feature property (here `arrows`) and set all features with `draw.set`

### Expected Behavior

Given feature updates and re-renders so custom style properties are applied correctly.

### Actual Behavior

Feature doesn't re-render so property change has no effect until something else triggers a re-render.

I assume something should be added here https://github.com/mapbox/mapbox-gl-draw/blob/7e4e21a832dcb78014d927dcdb50e43b6a8d251d/src/api.js#L96 to trigger re-render if properties change

**Comment by Bryce-Davidson** [comment]
Any update on this? The features require a click action to render a color property which has been changed without draw.setFeatureProperty

**Comment by Bryce-Davidson** [comment]
Under the line referenced above 

[`internalFeature.properties = feature.properties;`](https://github.com/mapbox/mapbox-gl-draw/blob/7e4e21a832dcb78014d927dcdb50e43b6a8d251d/src/api.js#LL96C2-L96C2)

There needs to be a check to see if ANY of the Feature properties have changed

**Comment by Bryce-Davidson** [comment]
I made the changes below on my own fork and everything works as expected.
```javascript
// If a feature of that id has already been created, and we are swapping it out ...
        const internalFeature = ctx.store.get(feature.id);
        // If the immediate properties have changed, rerender
        if (
          !objectShallowEquals(internalFeature.properties, feature.properties)
        ) {
          // indicate changed immediate properties
          ctx.store.featureChanged(internalFeature.id);
        }
```

```javascript
function objectShallowEquals(a, b) {
  if (a === b) return true;
  if (a === null || b === null) return false;

  const ka = Object.keys(a);
  const kb = Object.keys(b);
  if (ka.length !== kb.length) return false;

  return ka.every((ki) => a[ki] === b[ki]);
}

export default objectShallowEquals;

```
