### ISSUE TITLE
CSS is not namespaced

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#116]
`.trash`, [for example](https://github.com/mapbox/mapbox-gl-draw/blob/9323dbdb0ab85e733b0e3899a67b5a207fc43036/dist/mapbox-gl-draw.css#L49), overrides the global `.trash` rather than creating a mapbox-gl-draw trash style.

**Comment by samanpwbb** [comment]
When re-writing css I recommend following this convention:

1. Every rule should be exactly one class so everything has the same CSS specificity.
2. Prefix all rule names with an exact copy of the project name in npm:  `mapbox-gl-draw`
3. Descriptive parts of the rule should follow after a single or double `_`. 

See https://github.com/moroshko/react-autosuggest for an example of a project with CSS that is extremely easy to work with.
