### ISSUE TITLE
how to show or hide the draws

### ISSUE THREAD

**Issue by SuhaibMaraqa** [mapbox/mapbox-gl-draw#1171]
Hello, I was wondering how can I hide and show a draw, maybe there is a "visibility" property on the draw to control it?

**Comment by stepankuzmin** [comment]
Hi,

You can use [map.addControl](https://docs.mapbox.com/mapbox-gl-js/api/#map#addcontrol) and [map.removeControl](https://docs.mapbox.com/mapbox-gl-js/api/#map#removecontrol) for that.

```js
var Draw = new MapboxDraw();

map.addControl(Draw);
```
