### ISSUE TITLE
Sanitation strike

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#119]
<img width="434" alt="2015-12-10 at 12 00 pm" src="https://cloud.githubusercontent.com/assets/32314/11722222/a22b81b8-9f35-11e5-8a91-9950caf68080.png">

Editing multiple features, the trash keeps piling up, the union must agree on a new contract soon.

**Comment by kelvinabrokwa** [comment]
wowza thats not supposed to happen https://github.com/mapbox/mapbox-gl-draw/blob/a154758695dd1b4f44f7aa6acde24602e7bfdf76/src/draw.js#L165-L171
