### ISSUE TITLE
mapbox-gl as a peer dependency?

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#120]
Having mapbox-gl as a dependency bloats build files. The directions control solves this problem by [including mapbox-gl as a peer dependency](https://github.com/mapbox/mapbox-gl-directions/blob/9d4745763649db104c539e7b04ea493d3b2f0af9/package.json#L52-L54). Any reason we shouldn't do that here?

/cc @kelvinabrokwa @tristen @scothis @tmcw

**Comment by scothis** [comment]
Do it! You'll probably also want to include mapbox-gl as a devDependency. General advice is to make peerDependency version range as broad as possible, without being unbounded.
