### ISSUE TITLE
Click listener error

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-draw#126]
Messing around in a larger application and got `Uncaught TypeError: Cannot read property 'getOptions' of undefined` from one of my [less elegant additions](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/draw.js#L244). I can't recreate in smaller test cases but just flagging for now (and because I feel bad about creating this error)

**Comment by mcwhittemore** [comment]
@drewbo can you confirm if https://github.com/mapbox/mapbox-gl-draw/pull/147 fixes this?

**Comment by drewbo** [comment]
The offending line is removed so I'm comfortable closing this for now and reopening something if a similar error occurs.

**Comment by mcwhittemore** [comment]
Sounds good!
