### ISSUE TITLE
Winding order matters for polygons and cuts out other features

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#128]
![winding](https://cloud.githubusercontent.com/assets/32314/11752959/7e5bbc40-a010-11e5-8292-740391704ad5.gif)

Winding order shouldn't matter

**Comment by mcwhittemore** [comment]
For first version we should not support cutting of features. Does this seem ok to most people?

**Comment by tmcw** [comment]
This seems like a pure bug: this isn't intended behavior, right?

**Comment by mcwhittemore** [comment]
@tmcw - I don't like this behavior, but I'm not sure what the intent was. The geojson spec wants holes to be part of the polygon they are in so in the future I think we'll want to let holes happen as the second polygon in the polygon set GeoJSON. 

http://geojson.org/geojson-spec.html#polygon

**Comment by tmcw** [comment]
Yeah, these are not holes. This is a bug: I'm confident there is no intended feature. It is a bug.

**Comment by mcwhittemore** [comment]
@tmcw - are you saying this is a bug in mapbox-gl-js?

**Comment by tmcw** [comment]
It's likely a bug in gl-js, or potentially a bug in gl-draw.

**Comment by mcwhittemore** [comment]
This has been fixed in mapboxl-gl@0.16.0. Sadly the breaking changes in 0.16.0 don't work with the current version of Draw. Will fix as part of fresh-start.
