### ISSUE TITLE
Avoid getter methods if they aren't necessary

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#133]
https://github.com/mapbox/mapbox-gl-draw/blob/7731e824f483090a31158bb3cae90fb5dd365041/src/geometries/geometry.js#L51-L61

These methods get public properties of a class; class users should access the properties directly instead.

**Comment by kelvinabrokwa** [comment]
@tmcw sorry, I'm suffering from Java brain...
