### ISSUE TITLE
What should the mapState method be named?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#134]
https://github.com/mapbox/mapbox-gl-draw/blob/ccae3b48355d7c10e469e95e48c22db25e2784b5/src/draw.js#L426-L521

This method does a bunch of things, it should be named a verb that's one or all of those things.

**Comment by mcwhittemore** [comment]
Yea, I read this as a getter the first few times I saw it.

**Comment by kelvinabrokwa** [comment]
fixed in #142
