### ISSUE TITLE
External vs internal events

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#138]
@kelvinabrokwa I've been playing with gl-draw a bit today. For a project I want to take features out of draw when the `I'm done drawing` event is fired. That said, this event is also used by gl-draw so it is possible that I'd start listening before the inner workings of gl-draw set up their own listeners. If the actions gl-draw takes on those actions are important to me, I'm out of luck. I'd like to look into standardizing some of these events and create a good separation between events for end users and triggers to needed for the inner workings of gl-draw. What do you think?

**Comment by kelvinabrokwa** [comment]
@mcwhittemore I totally agree, events are pretty wonky in gl-draw right now so please do whatever you must!
