### ISSUE TITLE
More edit events

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-draw#139]
It would be nice to have `edit.start` and `edit.end` events.

**Comment by mcwhittemore** [comment]
@edenh what are you looking to get out of `draw.edit.start`? Do you expect to get this when a new feature is being created, or only on existing features?

I think edits should end with a `draw.set` event. What else are you looking for in an `draw.edit.end` event?

**Comment by edenh** [comment]
I'm mostly looking for events when items are selected and deselected for edit.

**Comment by benheb** [comment]
@edenh @mcwhittemore I see that this pr was merged into master a long time ago... but I don't see these events in the latest build?? `draw.edit.start` and `draw.edit.end` do not work... and no sign of this: https://github.com/mapbox/mapbox-gl-draw/pull/146/files#diff-3bf35cd41da51153dcca3003656f7c67R85

**Comment by mcwhittemore** [comment]
This event was dropped. You can use [draw.update](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#drawupdate) and [draw. modechange](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#modechange) to derive the same information about the state.

**Comment by benheb** [comment]
@mcwhittemore thanks – just got it working with update/modechange, so that'll do!
