### ISSUE TITLE
Create Bower installer

### ISSUE THREAD

**Issue by rbonillajr** [mapbox/mapbox-gl-draw#140]
Can you add the Bower installer?

**Comment by tmcw** [comment]
We don't plan on supporting bower officially in any projects: the [rationale is laid out in the Mapbox GL JS ticket](https://github.com/mapbox/mapbox-gl-js/issues/1342#issuecomment-156059243). Feel free to create a third-party bower installable. GL Draw is installable by webpack, npm, CDN, and file download.
