### ISSUE TITLE
cdn

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-draw#143]
Do you have a version on a cdn? I wanted to make a fiddle showing an issue I have but can not do it without a cdn version to link to from the fiddle.

**Comment by tristen** [comment]
Soon! work is happening here for it: https://github.com/mapbox/mapbox-gl-plugins/issues/2

In the interm you can use [rawgit](https://rawgit.com/). i.e  https://raw.githubusercontent.com/mapbox/mapbox-gl-draw/master/dist/mapbox-gl-draw.js

**Comment by musicformellons** [comment]
Great! thanks.

**Comment by musicformellons** [comment]
@tristen Mmmh, 
http://jsfiddle.net/
does not accept the rawgit, so any suggestions how to get it working?

**Comment by tristen** [comment]
Sorry - I posted the wrong link.  https://cdn.rawgit.com/mapbox/mapbox-gl-draw/master/dist/mapbox-gl-draw.js should work.

**Comment by musicformellons** [comment]
Yeah, that works. Thx.
