### ISSUE TITLE
hide draw on create

### ISSUE THREAD

**Issue by rbonillajr** [mapbox/mapbox-gl-draw#144]
@kelvinabrokwa 
in page ready show delete button 

![image](https://cloud.githubusercontent.com/assets/8268226/11783341/b8937c96-a244-11e5-8296-9329105afa34.png)

when I add an anthropologist or line guide does not go black , but when you zoom out pink figure

![image](https://cloud.githubusercontent.com/assets/8268226/11783435/49d84f06-a245-11e5-962c-59eb9f615e90.png)

![image](https://cloud.githubusercontent.com/assets/8268226/11783446/6356db0a-a245-11e5-92b6-09fdfbb8ec5d.png)

**Comment by mcwhittemore** [comment]
@rbonillajr I'm not understanding what it is you are expecting here. Can you please reword?

**Comment by rbonillajr** [comment]
Image 1: loading the map , by default displays the delete button. 
Image 2: on mousedown with draw don't show black mark 
Image 3: to finish draw don't show feature. the feature show when  zoom in

my code is 

```javascript
/** @ngInject */
export function mapgl(L: any, mapboxgl: any): ng.IDirective {

  return {
    restrict: 'E',
    scope: {
    },
    templateUrl: 'app/components/mapxplor/mapxplor.html',
    controller: MapglController,
    controllerAs: 'vm',
    bindToController: true
  };
}

/** @ngInject */
export class MapglController {
    public L: any;
    public mapboxgl: any;
    public turf: any;
    public BufferService: BufferService;
    public scope: any;

  constructor(L: any, mapboxgl: any, turf: any, BufferService: BufferService, $scope: ng.IScope) {
     this.L = L;
     this.mapboxgl = mapboxgl;
     this.turf = turf;
     this.BufferService = BufferService;
     this.scope = $scope;
     var vm = this.scope;
     // var test = BufferService.generate(30,'miles',{'lat':80.01, 'lng': -40});
     
    this.mapboxgl.accessToken = 'pk.eyJ1IjoicmJvbmlsbGFqciIsImEiOiI5M2FhYjRjNjFjNTE2YTU2NjUxNzJiNmQ3Mjc3OWFjMSJ9.dj1BlB2pdE2TqjQT42kl8A';
    var map = new mapboxgl.Map({
        container: 'mapgl',
        style: 'mapbox://styles/mapbox/streets-v8',
        zoom: 7,
        center: [-79.89260990593574,8.488481600020107]
    });
   
    map.on('style.load', function () {
        map.addSource('Comercios', {
            type: 'vector',
            url: 'mapbox://rbonillajr.6kph7pea'
        });
        map.addLayer({
                'id': 'COMERCIOS',
                'interactive': true,
                'type': 'circle',
                'source': 'Comercios',
                'paint': {
                    'circle-radius': 8,
                    'circle-color': 'rgba(55,148,179,1)'
                },
                'source-layer': 'COMERCIOS'
            });
    });
    map.on('click', function (e) {
        map.featuresAt(e.point, {layer: 'COMERCIOS', radius: 10, includeGeometry: true}, function (err, features) {
            if (err || !features.length)
                return;
    
            var feature = features[0];
            
            if (typeof popup != 'undefined') {
                map.removeLayer(popup);
            }
            
            var popup = new mapboxgl.Popup()
                .setLngLat(feature.geometry.coordinates)
                .setHTML(feature.properties.NOMBRE)
                .addTo(map);
        });
    }); 
    
    map.on('mousemove', function (e) {
        map.featuresAt(e.point, {layer: 'COMERCIOS', radius: 10}, function (err, features) {
            map.getCanvas().style.cursor = (!err && features.length) ? 'pointer' : '';
        });
    });
    
    map.addControl(new mapboxgl.Navigation({
        position: 'top-left'
    }));
    var Draw = mapboxgl.Draw();

    map.addControl(Draw) 

  }
}
```

**Comment by mcwhittemore** [comment]
Oh! The delete button is showing up on load! I'll make sure we fix that in the next release.

I agree, when drawing, the mouse down event should clearly show a black dot so you know you've started. This also will be fixed in our next release.

Because gl-draw creates geojson features, they are for all zoom levels. If you want the features to not show up at different zoom levels, you need to change the layer in the style to look different at different zoom levels. This doc should help you - https://www.mapbox.com/mapbox-gl-style-spec/#types-function

**Comment by mcwhittemore** [comment]
Putting this jsfiddle here to document the problems you're having - http://jsfiddle.net/bv2Lg3dw/1/

**Comment by rbonillajr** [comment]
@mcwhittemore  Thanks.
I using draw tool for select markers when the user needs.

**Comment by mcwhittemore** [comment]
@rbonillajr - you are using draw to let you select markers? It might be better to look into using the raw mapbox-gl-js api for this. `featuesAt` and `setStyle` should let you do good highlighting without having to load data via geojson. Geojson is still pretty slow in mapbox-gl-js.

**Comment by rbonillajr** [comment]
@mcwhittemore yes, I know. Thanks
