### ISSUE TITLE
can not customize

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-draw#145]
I tried to customize the points I draw on a map (larger circle and color red) but it does not work. Here is a fiddle:
http://jsfiddle.net/musicformellons/sgqtzwgj/

**Comment by kelvinabrokwa** [comment]
@musicformellons your `styles` parameter is not structured correctly. It must contain keys that are gl-draw layer ids and the values are the styles. See https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#options for example

```js
var Draw = mapboxgl.Draw({
  styles: {
    'gl-draw-polygon': {
      'paint': {
        'fill-color': '#00ffff',
        'fill-outline-color': '#00ffff',
        'fill-opacity': 0.25
      }
    },
    'gl-draw-polygon-stroke': {
      'paint': {
        'line-color': '#0000ff',
        'line-width': 4
      }
    }
  }
});
```

**Comment by musicformellons** [comment]
Thanks, the example indeed works. I also got it working now for points, which are really circles. It is confusing that the default values for points in the themes/style.js file are for icons, NOT CIRCLES. So instead of using icon-size you have to use circle-radius etc. Looks like the defaults are stale!?

**Comment by mcwhittemore** [comment]
geojson doesn't have an concept of circles. You can use points to fake this idea, but points are also used for other things just as names and POIs. That said, if you have a good way to express this in the stylesheet, please feel free to make a PR.

Closing this for now.
