### ISSUE TITLE
Set does not work, but update does

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-draw#148]
The coordinates do not come through using set ([ 0, 0] instead of [ 10, 10], but update does work...
http://jsfiddle.net/musicformellons/v412dLsx/
What's wrong?

**Comment by mcwhittemore** [comment]
@musicformellons thanks for reporting this bug. We are working on a large refactor of gl-draw that should fix this problem.

**Comment by musicformellons** [comment]
Ok, thanks!
