### ISSUE TITLE
putting drawings 'behind/ before' mapbox layers

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-draw#151]
I suppose this would be a feature request. I would like to be able to put a circle behind another mapbox gl js/ mapbox gl draw "layer".

**Comment by mcwhittemore** [comment]
@musicformellons do you want to do this for all circles or just for some of them?

mapbox-gl-js is where ordered of layers is controlled, so if you wanted to move all points under another layer in the map, you should be able to move the gl-draw layers around in the style using the [get](https://www.mapbox.com/mapbox-gl-js/api/#Map.getLayer), [remove](https://www.mapbox.com/mapbox-gl-js/api/#Map.removeLayer) and [add](https://www.mapbox.com/mapbox-gl-js/api/#Map.addLayer) layer functions.

**Comment by musicformellons** [comment]
Cool! Thanks.
