### ISSUE TITLE
npm requires should be supported without the end user needing the same version of babel

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#152]
Lets make main point at the dist file

**Comment by mcwhittemore** [comment]
browserify lets you exclude modules, so we'd want to exclude anything that is a peer dependency

**Comment by anandthakker** [comment]
@mcwhittemore I still see `main` pointing at `index.js` and thus requiring babel when i browserify a project that includes gl-draw as a dependency.

**Comment by mcwhittemore** [comment]
@anandthakker - the built file is at dist/mapbox-gl-draw.js. You should be able to require this file via `require('mapbox-gl-draw/dist/mapbox-gl-draw')`.

**Comment by anandthakker** [comment]
@mcwhittemore Something weird happened last night when I tried that -- I was getting an empty object exported from `mapbox-gl-draw/dist/mapbox-gl-draw`.  For now I just went ahead and added babelify to my project, allowing me to require the main module
