### ISSUE TITLE
Methods for manipulating edit state

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-draw#154]
`Draw.setEdit(String: drawId)`: select a single feature as editable
`Draw.unsetEdit(String: drawId)`:  deselect a single feature
`Draw.setEditAll()`: select all features
`Draw.unsetEditAll()`: deselect all features

**Comment by mcwhittemore** [comment]
@edenh - what is the goal of this api? When would you want to programmatically start/stop editing?

**Comment by mcwhittemore** [comment]
From another ticket I see you want to have selecting done via key bindings. Currently gl-draw does its own key bindings, I think we should keep it that way.
