### ISSUE TITLE
Great Drawing Tool or Great setData abstraction api?

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#157]
@edenh and I have been talking a bit over the last few days about what gl-draw should be. On one hand gl-draw could be a fully featured drawing tool, on the other it could be a set of api's to make working with the geojson and setData easier.

Currently gl-draw has been moving towards option one with a few option two features. But as we start to use it more and more questions about how custom one would want to make their drawing tools lead us consider option two. 

We could go both routes, but I think that would lead to a rather bloated api.

A few issues that touch on this tension: #154, #109, #139

/cc @kelvinabrokwa @drewbo @tmcw @musicformellons @samanpwbb

**Comment by samanpwbb** [comment]
> a set of api's to make working with the geojson and setData easier.

I'd be great to have this. Will open up a wider range of use cases for the project and give users more flexibility to build exactly the kinds of draw interactions that want. 

We wouldn't need to remove the existing UI components – they could stay in the project and use the APIS. Developers would then have the choice to directly access the API and build their own UI or use the existing UI components.

**Comment by drewbo** [comment]
My use case so far has been much closer to the second option than the first (I removed the UI elements but leave in the ability to draw a polygon). I like @samanpwbb's suggestion, basically it ends up being both options but is very light on the drawing specific features. No strong feelings either way from me.

**Comment by mcwhittemore** [comment]
Yea, most projects are going to create their own buttons to start drawing. We will need an api to start drawing these features.

I'm still concerned with what a more exhaustive api approach means. I'll post in a bit when my thoughts are better formed.

**Comment by mcwhittemore** [comment]
I got my thoughts down in #158. After that, @edenh and I chatted a bit and realized that dropping the idea of editing from gl-draw and moving to selected helps clear up a bunch of my concerns. Do this would push us more towards @samanpwbb suggestion.
