### ISSUE TITLE
Activating draw at an arbitrary time

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#159]
It says in the API.md: "Note: make sure to instantiate Draw before any calls to map.on('load')"

Even though I don't really understand why, it seems that the draw functionality has to be initialised together with the map. If I try to initialise it later, it does not work.

How can I enable and disable drawing programmatically at arbitrary times in my application?

**Comment by kelvinabrokwa** [comment]
I'm actually working on a patch that I believe should enable this. I will write back to this issue when I merge it.

**Comment by averas** [comment]
Cool, thanks.

**Comment by averas** [comment]
While you're at it.. I tried out your branch <code>tests</code> which I believe contains these fixes.

While adding the draw functionality at an arbitrary time does now work, removing it and adding it again does not. It seems layers and sources are not cleaned up to a state where map.addControl(draw) works after performing a map.remove(draw).

**Comment by kelvinabrokwa** [comment]
@averas this is actually what I'm working to fix this week (and the main blocker for the test branch). I'm looking at the [mapbox-gl.js](https://github.com/mapbox/mapbox-gl-js) events API to see if there is a way to tell when a source/style has loaded. Once I find a work around this problem should be fixed.

**Comment by kelvinabrokwa** [comment]
@averas https://github.com/mapbox/mapbox-gl-draw/pull/168 addresses your original ticket. I'm going to close this and track your second concern in https://github.com/mapbox/mapbox-gl-draw/issues/169
