### ISSUE TITLE
get bounds of selected region

### ISSUE THREAD

**Issue by rishabhjain30** [mapbox/mapbox-gl-draw#160]
How can I draw a region on the map and get its bounds? I want to filter the markers to show it only in that region.

**Comment by averas** [comment]
Whatever you draw generates GeoJSON. This GeoJSON can subsequently be used for filtering of another geographic data set. I assume however, by all rights, that such filtering is not in the scope of this drawing library, so you will have to do that yourself, or incorporate another library for it.

If you draw a polygon and want to filter a set of points I would suggest you use turf.js for the filtering part:

http://turfjs.org/static/docs/module-turf_within.html

**Comment by rishabhjain30** [comment]
@averas I will be doing filtering on the backend. I need bounds of a region drawn by the user using mouse. Thanks.

**Comment by averas** [comment]
So you need a bounding box kind of geometry? If you draw a square polygon (supported by the library) I would argue that the polygon itself is such a bounding box. If you draw an irregularly shaped polygon and need the bounding box (envelope) I would again point you towards turf.js.

Ship your bounding box coordinates to you backend and perform the filtering.

**Comment by rishabhjain30** [comment]
So, if I draw a square, how can I get the coordinates of that square?

**Comment by rbonillajr** [comment]
Hi @rishabhjain30 this code work for me.

```javascript
        var points = [];
        map.on('mousedown', function (e) {
            points = [];
            points.push([e.point.x, e.point.y]);            
        });
        map.on('mouseup', function (e) {
            points.push([e.point.x, e.point.y]);            
        });
```

then assign variable points 

```javascript
          map.featuresIn(points, {layer: 'ALIMENTACION', includeGeometry: true}, (err, features) => {                
                console.log(features);
            });
```

**Comment by mcwhittemore** [comment]
Thanks @rbonillajr and @averas for helping clear this up
