### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rbonillajr** [mapbox/mapbox-gl-draw#162]
The documentation is not updated for example events.

for example this link: 
https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#drawdeslect

**Comment by kelvinabrokwa** [comment]
@rbonillajr thanks for pointing this out. The examples are a bit out of date. I'll grab this soon.

**Comment by mcwhittemore** [comment]
Do we want to drop examples and just have people look at debug/index.html for now? These example are much more complex than they need to be and bring in concepts outside of draw.

**Comment by kelvinabrokwa** [comment]
@mcwhittemore sounds good to me
