### ISSUE TITLE
nodes of draw repeated

### ISSUE THREAD

**Issue by rbonillajr** [mapbox/mapbox-gl-draw#163]
the GeoJSON repeated one node (first and last)

result this draw is:

[-81.4911206481233, 8.773606438078104],[-81.4911206481233, 8.273819023152939],[-80.3375561949983, 8.273819023152939],[-80.3375561949983, 8.773606438078104],[-81.4911206481233, 8.773606438078104]

![image](https://cloud.githubusercontent.com/assets/8268226/12102227/67b14596-b307-11e5-915d-f90a46f37e1c.png)

**Comment by kelvinabrokwa** [comment]
@rbonillajr from the GeoJSON spec:

> For type "Polygon", the "coordinates" member must be an array of LinearRing coordinate arrays.

> A LinearRing is closed LineString with 4 or more positions. The first and last positions are equivalent (they represent equivalent points).

the first and last coordinates in a GeoJSON polygon must be the same.

**Comment by rbonillajr** [comment]
Ah ok thanks for info. 


{
"Nombre": "René Bonilla",
"Correo": "rbonillajr@hotmail.com",
"Celular": 62330460
}
