### ISSUE TITLE
draw.set fires before feature is committed 

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#164]
In the documentation it states that <code>draw.set</code> is <code> .. fired every time a feature is committed via escape or the double click. </code> However, it seems that the event is fired immediately upon selecting a draw option from the buttons. Before the feature is committed it contains geometries with zeroed coordinates.

It would be nice to have a way to only react to actual changes to the committed features.

**Comment by mcwhittemore** [comment]
@averas I think `draw.select.start` should happen when a new feature is created and `draw.set` should only happen when the geojson has changed and is being committed.

@edenh and @kelvinabrokwa does that sound right to you?

Also, we really need to clean up the docs here. The example are way out of date and the api.md file has the wrong event names...

**Comment by edenh** [comment]
Selection events are the following:

- `draw.select.start` when a feature is _selected for edit_
- `draw.select.end` when a feature is deselected

It might make sense to split up the `draw.set` event to be:

- `draw.add` when a new feature is added
- `draw.set` when an existing feature is updated ("committed")

**Comment by mcwhittemore** [comment]
I think `draw.add` would just be a subset of `draw.select.start` unless we make the select events only fire for existing features. This seems redundant to me. I think end users will be able to know if its a new feature by seeing if the have a record of the feature in their application.

**Comment by averas** [comment]
But you mean the change the current behaviour of draw.set to just firing the event when the feature is committed?

**Comment by mcwhittemore** [comment]
@averas yep. I think draw.set being fired at the start of the drawing seems weird to me and doesn't match out documentation, so I'm calling it a bug. If you have time, please feel free to open a PR. I'm a few days out from getting to it.
