### ISSUE TITLE
map zoom in show trash button

### ISSUE THREAD

**Issue by rbonillajr** [mapbox/mapbox-gl-draw#166]
trash button show when zoom in the map

load map:
![image](https://cloud.githubusercontent.com/assets/8268226/12120158/85489ef6-b39d-11e5-8fe2-685a4e754c76.png)

zoom in map:

![image](https://cloud.githubusercontent.com/assets/8268226/12120280/2fd04888-b39e-11e5-92ee-57c459be779b.png)

**Comment by averas** [comment]
I've noticed this too, when using shift-bbox-zoom.

**Comment by mcwhittemore** [comment]
@averas - we're using featuresAt from mapbox-js to select features. My guess is that some how a feature from the under lying map is being caught in this call and before checking for the feature in gl-draw, we're adding the trash button.

**Comment by rbonillajr** [comment]
I'm using the debugger project for test. 

Could you check on that code ?

**Comment by mcwhittemore** [comment]
@averas - Sorry. My comment wasn't clear. I've see this bug too. My comments above were about why I think its happening. I'm currently pushing on a few other things, so it will be at least a week before I can look at this in detail. If you have time to make the PR, that would be great!
