### ISSUE TITLE
clean up layers and sources when draw is removed

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/mapbox-gl-draw#169]
re: https://github.com/mapbox/mapbox-gl-draw/issues/159

**Comment by mcwhittemore** [comment]
@kelvinabrokwa can you link the upstream issue?

**Comment by kelvinabrokwa** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/1896

**Comment by mcwhittemore** [comment]
@kelvinabrokwa why do you need to know if the style/sources are loaded to remove them from gl-js? Can't you just do this cleanup in the remove function of the plugin?

**Comment by kelvinabrokwa** [comment]
@mcwhittemore yeah but the problem is that when you remove draw you also have to remove its layers (styles + sources) but you can't remove them until they are loaded and there is on way to tell when they are loaded

**Comment by kelvinabrokwa** [comment]
this is not actually upstream

**Comment by mcwhittemore** [comment]
@kelvinabrokwa - where are we on getting this to work?

**Comment by averas** [comment]
Removing draw now seems to work, however, adding it again does not.. or well.. the controls show up but it's throwing a low of errors when trying to draw.

**Comment by mcwhittemore** [comment]
@averas which version of gl-draw are you using? Are you following master or using npm to install it?

**Comment by averas** [comment]
I'm building <code>master</code>.

Basically I do:

<code>
draw = mapboxgl.Draw();
map.addControl(draw);
</code>
_.. drawing works fine._
<code>
draw.remove();
</code>
_.. controls disappear - no errors_
<code>
draw = mapboxgl.Draw();
map.addControl(draw);
</code>
_.. controls reappear - everything looks fine, however, when I try to draw:_
<code>
Uncaught TypeError: Cannot read property '_container' of null
y.onMouseDown @ mapbox-gl-draw.js:13
mapbox-gl-draw.js:13 Uncaught TypeError: Cannot read property 'featuresAt' of null
y.onClick @ mapbox-gl-draw.js:13
Evented.fire @ evented.js:87
Interaction._fireEvent @ interaction.js:134
Interaction._onClick @ interaction.js:117
</code>
