### ISSUE TITLE
rename event: draw.set => draw.add

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/mapbox-gl-draw#170]
In order to match the new API method naming scheme.

This will be a breaking change.

**Comment by mcwhittemore** [comment]
`draw.set` is more than just what happens with `draw.add()`. `draw.set` happens whenever a change is committed. While this does happen when `draw.add()` is called, its also happens at other times. Making these names will confuse this. Why do you want the change?

**Comment by kelvinabrokwa** [comment]
@mcwhittemore I was not aware that `draw.set` was fired on commit. I was just trying to keep the naming consistent. With that in mind, closing.
