### ISSUE TITLE
Not clear how to draw programmatically

### ISSUE THREAD

**Issue by kiRach** [mapbox/mapbox-gl-draw#173]
Hi guys, thank you for your work on this library.

But it's not clear how to use your API to draw/edit shapes programmatically. Could you please provide some examples?

For example, I want to draw polygon and set it's state to edit.

Thank you.

**Comment by mcwhittemore** [comment]
Can you explain what you expect a bit more?

**Comment by kiRach** [comment]
Sure. For example, using Leaflet.Draw plugin I can place polygon on map and set its state to "edit":

```javascript
var polygon = L.polygon(/*coordinates*/);
polygon.editing.enable();
polygon.addTo(map);
```
Result of this code is polygon created and placed to the map in edit state: user can change its form/coordinates etc. Is something like this is possible with your plugin?

**Comment by mcwhittemore** [comment]
Gotcha. gl-draw doesn't have constructors for geojson yet. I'm not sure we really want to do this as other libs do it well enough already such as turf.

```
var polygon = turf.polygon(/*coordinates*);
var id = Draw.add(polygon);
Draw.select(id);
```

If you're feature has an id Draw will use its id as of 0.1.4.

**Comment by kiRach** [comment]
@mcwhittemore Thank you for provided example. I assume that when I create a feature and add it to draw by `Draw.add(...)` method - it should be shown on the map immediately? I tried it and nothing is shown on the map.

**Comment by mcwhittemore** [comment]
@kiRach - can you check your version number? We pushed a fix for that problem recently #171.

**Comment by kiRach** [comment]
@mcwhittemore Just checked - I use latest version (0.1.4), but I use mapbox-gl-draw with webpack: I use the file `dist/mapbox-gl-draw.js` and as I see `dist` folder wasn't updated with your latest release. May be that's the issue.

**Comment by mcwhittemore** [comment]
Oh! Sorry, that was my fault. We use the non-built version internally so I forget about updating the distribution. I've just updated the package.json to build on publish so this won't happen in the future and I've pushed 0.1.5 to npm. Thanks for reporting this.

**Comment by kiRach** [comment]
I'm sorry to bother you again, but seems changes from #171 are not in master branch anymore. I'm looking at `src/api.js` in master branches and don't see it. Like it was overwritten.

**Comment by mcwhittemore** [comment]
Wow. This is going to be a sad point in git history. It looks like I force pushed to master when I wasn't up to date. Bad habits die hard. 0.1.6 is live in npm now. It has the commit from #171 in it. I hope we're good now.

**Comment by primozs** [comment]
I am using mapbox-gl-draw 0.17.0
When map is loaded I make an instance of draw 
const draw = new MapboxDraw()
add some point features
draw.add(f);

- Features are not visible until I click Line edit Point control button or press 1, 2.
- I tried to programmatically change draw mode to different modes also with features select but they don't appear. They only appear after line edit button click. It seams line control button runs
```ctx.events.changeMode(Constants.modes.DRAW_LINE_STRING)````

Any idea?
Cheers

**Comment by mcwhittemore** [comment]
@primozs - My guess is that you are adding features before the style has loaded. Draw only works after the map has loaded. There are some details about this at the top of [the api docs](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#api-reference)

**Comment by primozs** [comment]
Hi! @mcwhittemore 
Thx for suggestion. I am also guessing that features are somehow set too soon, but I am setting 
```map.addControl(draw);  on style.load```
I guess addControl is async so maybe this could be the problem.

**Comment by primozs** [comment]
@mcwhittemore 
It seams its like I said. If I do add on setTimeout then it works.

**Comment by primozs** [comment]
@mcwhittemore Is there some other way to find out draw is properly initialised? Maybe some mapbox event that I don't know of? map load, style.load are already done in my case.

**Comment by mcwhittemore** [comment]
@primozs - can you create a fiddle of this, so I can see what is going on here. Thanks

**Comment by primozs** [comment]
@mcwhittemore Hi my setup is a bit more complex with map wrapped in react component and data is being loaded in map child editing component. But here is a simple example.

Commented is the version that points are not displayed until you click some Draw control. setTimeout option is the one that is not reliable waiting and displaying points on load.

http://codepen.io/primozs/pen/bqmYLK?editors=0010
Thank you for looking into this.

**Comment by mcwhittemore** [comment]
@primozs - You were seeing no point until you clicked on the Draw control right?

If you change `style.load` to `load` the points are visible without a setTimeout.

Here is a fork of your codepen doing this: http://codepen.io/anon/pen/evQmJN?editors=0010

**Comment by primozs** [comment]
@mcwhittemore Ou, what a mistake by me. I was assuming that style.load happens later then load.
Thank you for help!
