### ISSUE TITLE
Draw.add method doesn't render objects

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-draw#174]
I may be doing something very wrong but when I use Draw.add nothing is generated on screen, although Draw.getAll() does return the object? Here is my test code with some simple functions to add, select and get data:

/*mapboxgl.accessToken = '';*/

var map = new mapboxgl.Map({
  container: 'map',
  style: 'styles/style2.json',
  zoom: 12,
  center: [40.388437, 49.864650]
});

map.addControl(new mapboxgl.Navigation());
var Draw = mapboxgl.Draw();
map.addControl(Draw)

function getAll(){
  console.log(Draw.getAll())
}

function addPoly(){
  var feature = { type: 'Polygon', coordinates: [[[40.349469867431736, 49.85518831547995],[40.3724724919434,49.8672502553388],[40.40457316943369,49.85452426804275],[40.376077380859414,49.84865811937618],[40.376077380859414,49.84865811937618],[40.349469867431736,49.85518831547995]]] };

  var featureId = Draw.add(feature);
  console.log(Draw.get(featureId));
}

function addPoint(){
  var feature = { type: 'Point', coordinates: [40.35976955004898, 49.86913120386518] };

  var featureId = Draw.add(feature);
  console.log(Draw.get(featureId));
}

function selectAll(){
  Draw.selectAll()
}

</script>

</body>
</html>

**Comment by mcwhittemore** [comment]
@joedjc - There was a bug introduced in 0.1.2 that caused Draw.add to stop rendering. This is solved in 0.1.6. Sorry for the inconvenience.
