### ISSUE TITLE
Cursor no longer changes when hovering over selected features

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-draw#180]
I think previously there was a crosshair on the nodes, and move cursor elsewhere which was useful to indicate interactivity.

**Comment by kelvinabrokwa** [comment]
@joedjc this was a regression as of https://github.com/mapbox/mapbox-gl-draw/commit/2c3d639b9970ecfdb0ea4773a2ae251ed17e61aa. Will fix in the testing PR.

**Comment by mcwhittemore** [comment]
Fixed in #279
