### ISSUE TITLE
Handle Editing Differently

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#182]
- [x] Squares need to be dropped from an editing POV as they cannot be recreated.
- [x] Its hard to know what handle you're going to select
- [ ] the current handle logic adds a lot to the rendering step
- [x] escape should cancel a draw - not end it. Maybe enter should end it? - #201
- [x] double click should stop drawing
- [x] remove nodes - #210

**Comment by joedjc** [comment]
It would be useful if you could also remove nodes/undo like in leaflet draw, and if this issue were fixed: https://github.com/mapbox/mapbox-gl-draw/issues/178.

Could be helpful to see which nodes exist and which would be added by clicking (again like leaflet draw - intermediate points are more transparent). 

This would avoid adding nodes by mistake, or at least being able to remove them if you do.

**Comment by mcwhittemore** [comment]
Not sure there is a solution to having a lot of handles. I'm going to punt on that for the hope that geojson support will get faster in mapbox-gl soon.
