### ISSUE TITLE
freezes mapbox gl js v0.13.1 (and 0.12.5)

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-draw#189]
My map with use of draw (version?) via:

```
    <script src="https://cdn.rawgit.com/mapbox/mapbox-gl-draw/master/dist/mapbox-gl-draw.js" type="text/javascript"></script>
    <link href="https://cdn.rawgit.com/mapbox/mapbox-gl-draw/master/dist/mapbox-gl-draw.css" rel="stylesheet"/>
```

used to work fine; but not anymore after updating mapbox gl js to v0.13.1 : the map freezes. When I comment out the draw code the map works fine, so it seems to be a draw issue.

**Comment by mcwhittemore** [comment]
@musicformellons - it looks like gl-draw has and invalid style. I'm working on a fix right now.

**Comment by musicformellons** [comment]
So I suppose it should be solved. I do not get the draw widget however; The links do not work anymore?
 <script src="https://cdn.rawgit.com/mapbox/mapbox-gl-draw/master/dist/mapbox-gl-draw.js" type="text/javascript"></script>
    <link href="https://cdn.rawgit.com/mapbox/mapbox-gl-draw/master/dist/mapbox-gl-draw.css" rel="stylesheet"/>

**Comment by mcwhittemore** [comment]
@musicformellons We dropped the distributions in github as having multiple people working on the code base and trying to keep the distributions up to date was creating conflicts and slowing us down.

We also aren't ready to support a CDN version of mapbox-gl-draw. That said, if this is something that you need, I can look into getting the CDN setup, but we do publish to NPM pretty frequently.

**Comment by musicformellons** [comment]
Ok. Thanks for the info. I will try the NPM version.

**Comment by mcwhittemore** [comment]
Thanks and sorry for the extra work.
