### ISSUE TITLE
features added via Draw.add don't ever have a draw.select.start event

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#193]

**Comment by kelvinabrokwa** [comment]
wow I'm surprised the test passed then... https://github.com/mapbox/mapbox-gl-draw/blob/master/test/events.test.js#L41-L51

**Comment by mcwhittemore** [comment]
oh! Wow. Why didn't that test catch this?

**Comment by mcwhittemore** [comment]
Oh! The circle tests are still just checking if it builds. We need to update that too.

**Comment by mcwhittemore** [comment]
Also, it looks like the spin up time for the map in the tests means putting the tests inside of `map.on('load', () => {})` often skips the tests.
