### ISSUE TITLE
Expose startDrawing to the public api

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#196]
Users should be able to opt out of our controls and still start drawing. This would be possible via a public version of `_startDrawing`. I think this should accept constant strings which we expose on Draw. Thoughts @kelvinabrokwa?

**Comment by kelvinabrokwa** [comment]
I agree. I can definitely see uses for this.

**Comment by mcwhittemore** [comment]
Wanna make it happen?

**Comment by kelvinabrokwa** [comment]
yes

**Comment by andrewharvey** [comment]
I have a use case for this, right now I'm just using the private api, but would be good to see this as part of the public api.
