### ISSUE TITLE
Holding shift should lock line drawing at 45 degree increments 

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-draw#2]

**Comment by mcwhittemore** [comment]
We should prototype this [via a custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw) and when its working well, bring it into MapboxDraw.

**Comment by just-ajs** [comment]
Was ever a custom mode developed for this?
