### ISSUE TITLE
Get tests running on circle-ci

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#200]
We need to find a way to get as many tests as we can to run on circle. Currently we're just pretending to have run our tests and this leads us to a false sense of security.

**Comment by mcwhittemore** [comment]
`mapbox-gl-draw` doesn't need gl it needs the `mapbox-gl-js` api. Currently our tests let gl leak in by depending on the real version of `mapbox-gl-js` but if we switched to fully fledged [mapbox-gl-mock.js](https://gist.github.com/mcwhittemore/a006581ca1913f36f6f4) we could drop the gl dependency completely. This will let us write tests that don't need browsers and can be run in our CI.

The one major call we need to confirm is working to get full test coverage is the `featuresAt`. I think we can fake this well enough to work for tests, but it does represent one tripping point. I'm sure there are others.

/cc @lucaswoj @kelvinabrokwa @tmcw

**Comment by lucaswoj** [comment]
I strongly recommend using `mapbox-gl-mock.js` for all unit tests. It shouldn't be too hard to build a stub implementation of `featuresAt` using [turf.js](http://turfjs.org/).

**Comment by mcwhittemore** [comment]
FYI, I'm going to be trying to get the current tests on `npm run test-unit` to work without a browser today.

**Comment by kelvinabrokwa** [comment]
@mcwhittemore :+1:
