### ISSUE TITLE
dist/mapbox-gl-draw.js disappeared

### ISSUE THREAD

**Issue by kiRach** [mapbox/mapbox-gl-draw#206]
`dist/mapbox-gl-draw.js` is not part of npm distribution anymore. How is it supposed to be used now?

**Comment by aemchuk** [comment]
Just run `npm run prepublish` command from repository clone folder and `dist/mapbox-gl-draw.js` will be generated.

**Comment by mcwhittemore** [comment]
@kiRach thanks for pointing this out. I removed it from git because it created a few unneeded conflicts but I forgot that npm uses the gitignore if it can't find npmignore. I'll fix this in the next release. In the mean time what @aemchuk says will work.

**Comment by mcwhittemore** [comment]
@kiRach 0.2.4 has shipped with dist/mapbox-gl-draw.js support reenabled.
