### ISSUE TITLE
Better zoom vs select UX

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#213]
Per @averas from https://github.com/mapbox/mapbox-gl-draw/pull/209#issuecomment-180500235

> when using shift-bbox-zoom over editable features both a bbox-zoom and selection of the features are triggered.

> Not sure what would be the best UX here.. not zooming in the case features are selected would probably be unintuitive (and probably a bit cumbersome to implement). Not being able to select multiple features at all would certainly be a loss of a valuable feature. Perhaps a different key? CTRL-bbox for selection?

**Comment by kelvinabrokwa** [comment]
I say no zoom on select. So maybe we find a way to prevent a box zoom when the zoom box encompasses features

**Comment by mcwhittemore** [comment]
Most bounding box zooming is when the bounding box encompasses features.

I think turning off bounding box zooming when gl-draw is enabled might be the best option.

**Comment by averas** [comment]
Either way, it depends on https://github.com/mapbox/mapbox-gl-js/issues/2173.

**Comment by averas** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/2173 is now resolved, however, while working on it I found a blocking bug instead... https://github.com/mapbox/mapbox-gl-js/issues/2237

**Comment by mcwhittemore** [comment]
Thanks for the update @averas!

**Comment by mcwhittemore** [comment]
Moving this to #339
