### ISSUE TITLE
Clicking on a draw button again before drawing anything will commit a premature feature

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#216]
If you click on any of the draw buttons and then, instead of drawing anything, you click on a draw button again - a feature will now have been committed with a geometry with 0-coordinates. If you continue clicking on the draw buttons you will continue adding premature features.

**Comment by mcwhittemore** [comment]
I love this issue. I just pushed a fix for this on a3f300669a2b37544296ea59b8a921f3f9c656ce. Hoping to have this out by the end of the day.
