### ISSUE TITLE
Event for when vertices are added/modified on LineString and Polygon

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#218]
I have a use case where drawing is limited to certain areas. For the Point type I immediately destroy the feature when created if it's out of bounds. For LineString and Polygon features I currently wait until it is committed before I can do any validation, which UX suffers from. I would love to see modification events both on committed and non-committed features so I can carry out validation on its current properties, immediately removing any vertices that are out of bounds.

**Comment by mcwhittemore** [comment]
@averas these events make sense to me but I think they should be combined into a `draw.edit` event. Do you think you could put together a PR to get this rolling?

I think the hard question here will be when to emit the event while moving a vertex. Do you think onMouseUp is a fast enough feedback loop? I worry that emitting this event any faster than that will flood the application with event data it doesn't need and lead to either bad UX or a frustrating developer experience.
