### ISSUE TITLE
v1 ROADMAP

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#220]
We are getting very close to a v1 of mapbox-gl-draw. Lets use this ticket to define what v1 is and set some timelines to get the remaining bits done.

Here is a list of things I currently have on my mind to get done for v1.

1. Crush all the bugs
2. Create tests that can be run on circle-ci
3. Go over the docs and make sure they are clear and true
4. Create the basic overview of mapbox-gl-draw page on mb-pages
5. Maybe get a few last features in

Is there anything that I'm missing here?

**Comment by joedjc** [comment]
@mcwhittemore I think its looking great and certainly has improved a lot recently. 

I'm not sure you can do much about it but I still find the performance a bit sluggish (though it has improved). It seems to me performance drops as the draw shape gets more complex with more nodes? It is also definitely affected by the size of the mapbox-gl instance. A full screen map (on a 13" laptop) is pretty slow, but with half the window size its perfectly fast. Will this be an issue in mapbox studio given that is full screen? I think both these factors have an impact.

Also this is not a big issue but i'm curious why the minified size of the library is so big, and actually bigger than mapbox-gl js itself (421kb vs 380kb)?

**Comment by mcwhittemore** [comment]
@joedjc Thanks for the comments. I'll look into the library size issue. We require in mapbox-gl-draw and it hasn't had too large of an impact on our bundles, but maybe I'm missing something.

Speed is definitely an issue. @lucaswoj is working on a few ideas to help speed up GeoJSON rendering in mapbox-gl-js. There are probably a few things we can do in mapbox-gl-draw to help, and maybe we should spend a bit more time hunting those down before v1, but I suspect these improvements will have very little impact on the total performance.

**Comment by lucaswoj** [comment]
Relevant upstream issue tracking performance improvements https://github.com/mapbox/mapbox-gl-js/issues/1504

**Comment by mourner** [comment]
> Also this is not a big issue but i'm curious why the minified size of the library is so big, and actually bigger than mapbox-gl js itself (421kb vs 380kb)?

I'd guess because it actually includes mapbox-gl in the build. We should fix this.

**Comment by mcwhittemore** [comment]
@mourner it looks like `mapbox-gl` is being used directly in two places currently. Created an issue to clean this up in #235. I think this is a good first PR issue, so I'm going to leave it alone for a while until we get closer to v1.

**Comment by mcwhittemore** [comment]
After working with this for the last few weeks internally and some of the interaction requests @mayagao has been making I think v1 is pretty far out so I'm closing this.
