### ISSUE TITLE
Passing option drawing: false throws error 

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-draw#223]
`Uncaught TypeError: Cannot read property 'style' of undefined`

Coming from https://github.com/mapbox/mapbox-gl-draw/blob/master/src/draw.js#L153

**Comment by drewbo** [comment]
Would the fix be better handled in the `_hideDeleteButton` method (check for drawing also) or `store.render`?

**Comment by mcwhittemore** [comment]
@drewbo I think this should be handled in the `_hideDeleteButton` code.
