### ISSUE TITLE
Find a clear way to disable all controls all the time

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#231]
Currently `mapbox-gl-draw` allows a user to pass `drawing: false` to the config object to disable all controls. We should find a better way to do this and deprecate `drawing: false` as drawing indicates that this stops the ability to draw, not the disabling of all controls.

One option is that we could expand the controls attribute on the user provided config to be either false, an objective or undefined. Where false turns off all controls, an object lets a user turn of some controls and undefined uses the defaults (all controls on).

Another option is that we could let the config look something like: `{controls: { off: true }}`.

@drewbo I know you are using this feature. Any suggestions to the best api?

**Comment by drewbo** [comment]
I prefer the first option (`controls: false`, `controls: [Object]`, or undefined); it also matches pretty closely what Leaflet.Draw does

**Comment by timjcook** [comment]
I agree that this needs a tweak. I would like to be able to disable the Control UI altogether and toggle shape drawing using my own UI elements. Even having a `displayControls` bool might be an option if the `controls` option will continue to play both of the roles of enabling shapes and listing them in the Control UI.

**Comment by mcwhittemore** [comment]
What about `displayControlsDefault` being a boolean so users can set the default for controls?

`displayControlsDefault: true` would mean all the controls **will show** by default but can be overwritten with something like `controls.marker = false`.

`displayControlsDefault: false`would mean all the controls **won't show** by default but can be overwritten with something like `controls.marker = true`.

**Comment by timjcook** [comment]
That seems quite logical. I like it.

**Comment by mcwhittemore** [comment]
The more I think about this the more I think `displayControlsDefault` is the right way to handle it. Lets do that and see how it goes.

This would be a great first PR issue for someone so I'm adding the `help wanted` label. If its not picked up in a few weeks I'll come back to it.
