### ISSUE TITLE
Remove direct mapbox-gl dependencies

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#235]
Currently `mapbox-gl-draw` include `mapbox-gl` as part of its build. This means end users are downloading `mapbox-gl` twice. Lets find ways to remove these dependencies.

- [ ] https://github.com/mapbox/mapbox-gl-draw/blob/33346ac48d33480eec3ef76400b1b82aa0a09e2e/src/api.js#L3
- [ ] https://github.com/mapbox/mapbox-gl-draw/blob/85141d0c812862c92398e2cf051eddab09abeb79/src/util.js#L3

**Comment by kelvinabrokwa** [comment]
@mcwhittemore for the second one could we just replace `mapboxgl.Point` with [point-geometry](https://github.com/mapbox/point-geometry)?

**Comment by lucaswoj** [comment]
We should make upstream changes to avoid the need to inherit `mapboxgl.Control`. Until then you can read from `window.mapboxgl` or copy-paste the implementation.

**Comment by mcwhittemore** [comment]
@kelvinabrokwa - do we even need a module for this?

@lucaswoj - Are you thinking of breaking Control out of mapbox-gl-js? It feels like this could lead to the just another dependency problem.

**Comment by lucaswoj** [comment]
> Are you thinking of breaking Control out of mapbox-gl-js? It feels like this could lead to the just another dependency problem.

I'm thinking about removing the need to subclass something to create a control. We can move all the logic from `Control` to `Map`.
