### ISSUE TITLE
Removing draw and adding it again makes it unusable

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#236]
Continuing on #169 ...

Demo: http://codepen.io/anon/pen/KVJvJB

1) Add draw with Add draw-button (works)
2) Draw something (works)
3) Remove draw with Remove draw-button (works)
4) Add draw again with Add draw-button (works)
5) Try to click on any of the draw feature buttons and watch the console...
6) Click somewhere on the map and watch the console...

**Comment by averas** [comment]
Ah, maybe one should not reinitialize draw with <code>draw = mapboxgl.Draw()</code> again.. then it works..

**Comment by averas** [comment]
Perhaps this is more related to how mapboxgl.Control works with add/remove rather than this plugin in particular...? @lucaswoj @mourner @jfirebaugh ?

**Comment by mcwhittemore** [comment]
@kelvinabrokwa do you have any insight here?

**Comment by kelvinabrokwa** [comment]
@mcwhittemore @averas I think this has to do with adding event listeners when we instantiate draw and not removing the when we remove draw. I'm working on it now.
