### ISSUE TITLE
Create performance benchmarks

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-draw#243]
We should create some performance benchmarks for mapbox-gl-draw that are quantifiable and repeatable. 

Ideally, these benchmarks would be runnable in a headless environment using something like http://karma-runner.github.io. 

It probably makes sense to work on the upstream mapbox-gl-js performance benchmarks first, and use the lessons and infrastructure from those to build the mapbox-gl-draw benchmarks.

ref https://github.com/mapbox/mapbox-gl-js/issues/954
ref https://github.com/mapbox/mapbox-gl-js/issues/1362

**Comment by mcwhittemore** [comment]
Like tests, should these use mapbox-gl-js or mapbox-gl-js-mock? Using a mock would let us know the perf of gl-draw. Using the real thing, would help us catch when gl-draw is using a slow gl-js function.

**Comment by lucaswoj** [comment]
The performance tests should use the real `mapbox-gl-js`.

**Comment by lucaswoj** [comment]
Highly relevant stuff moving in https://github.com/mapbox/mapbox-gl-js/pull/2231
