### ISSUE TITLE
Make feature selection easier to do in the code

### ISSUE THREAD

**Issue by mayagao** [mapbox/mapbox-gl-draw#247]
I want to add different cursors styles when I'm hovering over a feature's vertex/boundaries. Right now this is really hard to do, especially when two features overlap or two vertexes are near each other. It's not clear which one will be selected.

**Comment by mcwhittemore** [comment]
This should be an abstracted function so that all places we do this in the code work the same way. #230 mentioned options for picking the right feature. Lets merge that issue with this one.
