### ISSUE TITLE
Make drawing better

### ISSUE THREAD

**Issue by mayagao** [mapbox/mapbox-gl-draw#248]
Create a feature: 

<img src="https://cloud.githubusercontent.com/assets/5186564/13516813/8868de7c-e172-11e5-9d0a-5aa7434a5338.png" width="550">

Select a feature

<img src="https://cloud.githubusercontent.com/assets/5186564/13516748/dd8eb17a-e171-11e5-8cab-6789440206a4.png" width="550">

edit a feature

<img src="https://cloud.githubusercontent.com/assets/5186564/13516755/e7d669fc-e171-11e5-900d-c330d053f123.png" width="420">

**Comment by mcwhittemore** [comment]
I think the path towards these kind of UI interactions lies in removing the draw logic from the features. @tmcw has pointed me at some of the docs for how iD does this.

I think it also means empowering users to create more complex styles than we currently have. Right now features are styled by which of the two style buckets they fall into. While these buckets are important for performance, there is no reason why we should limit users in this way. I think the second task to get towards better UI is move away from this bucket based styling and letting users style based on a set of properties as well as creating a set of css classes for mouse styling.

This doesn't solve the delete problem though unless mouse styling is how you want to show that `Delete` ui.

**Comment by joedjc** [comment]
@mcwhittemore I know I asked about this before, and you've probably thought about, it but wanted to check how symbols are going to be dealt with.

My suggestion would be to use a 'crosshair' of some sort to indicate the symbol is selectable and when moving it. I think it would be the most intuitive approach but i'm sure not easy to implement.

<img width="285" alt="screen shot 2016-04-02 at 13 24 45" src="https://cloud.githubusercontent.com/assets/13920398/14226304/9212cde0-f8d6-11e5-8975-ff747716f533.png">

**Comment by mcwhittemore** [comment]
@joedjc - we are using the cursor to indicate hover state. 

Here is an active example. You can replace the dots with symbols.

![](https://cloud.githubusercontent.com/assets/5186564/14217839/649db57c-f81e-11e5-8be5-234ca77c8aae.gif)

**Comment by mcwhittemore** [comment]
#279 moved us very close to being done with this ticket. The last thing is to drop midpoints for adding vertices. Moved that to #281.
