### ISSUE TITLE
'interactive' option is broken

### ISSUE THREAD

**Issue by kiRach** [mapbox/mapbox-gl-draw#249]
As it stated in documentation:

option | values | function
--- | --- | ---
interactive | boolean | Keep all features permanently in selected mode - default: `false`

But it doesn't work. When I create mapbox.Draw with `interactive: true` - I still can leave selected mode if I click somewhere outside of shape.

**Comment by mcwhittemore** [comment]
@kiRach - are you using this for styling reasons or do you want the always editable functionality?

In #109 we've been talking about how the `being edited` and `not being edited` states are pretty limiting. There is also a conversation about supporting some pretty complex styling rules #248 just for context.

**Comment by kiRach** [comment]
@mcwhittemore I just want to always have 'editable' state. No styling reasons.

**Comment by mcwhittemore** [comment]
@kiRach for all features or just some?

**Comment by kiRach** [comment]
@mcwhittemore  Well, I think both of options would work for me, because I place only one shape to the map and want it to always be in "interactive" mode. So it can can be either 'all features' or I can specify it only for one shape that I place.

**Comment by mcwhittemore** [comment]
Thanks - one way to do this without some sort of config in gl-draw is to have an event handler on draw.select.end that reselects the feature if it gets unselected. Does this work for you? My fear here would be that there could be a flicker between styles.

I'm trying to drop extra features that complicate the code so if we can find a good way to achieve this that would be great.

**Comment by kiRach** [comment]
@mcwhittemore Thank you for your suggestion. I've tried it and it works, but as you expected - there is a flicker even though I've made both styles (for selected and not selected shape) same:
![screenshot](https://i.gyazo.com/d37b92ffcb0bf18c166c17aa96736173.gif)

It can be temporary solution, but it's definitely not what we would go with in production :(

**Comment by mcwhittemore** [comment]
Currently `setData` isn't part of the mapbox-gl-js batch command, I think this might fix the flicker.

@lucaswoj what do you think?

**Comment by lucaswoj** [comment]
The `batch` command is for methods on `Style`. `setData` is a method on `GeoJSONSource`.

This flicker is due to an async delay on `setData`. The correct solutions to this problem, IMO, are 

 - faster `setData` calls (i.e. https://github.com/mapbox/mapbox-gl-js/issues/1504)
 - synchronous `setData` calls (i.e. `skipWorker`)

**Comment by kiRach** [comment]
Hey guys, wouldn't it be simpler just to keep `interactive` option and if it's `true` - just ignore when user clicks outside of shape?

**Comment by mcwhittemore** [comment]
@kiRach - having flags that limit the way internal state works is pretty weird and I think asking users to maintain this kind of state is the right move as it empowers different types of control without adding complicity to an already complex library. The `permanent` flag @drewbo is talking about in #109 is another example.

In the last incarnation of gl-draw these two options we handleable, but as we look to enabling more advanced selection tools and styling options (#248 via #257 in progress in #258) these kinds of options quickly becoming limiting to both the library and the end-developer.

If the path forward that #258 is taking us on isn't right for you, lets talk about it on that PR.
