### ISSUE TITLE
Defer events, separate draw modes

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#257]
https://github.com/mapbox/mapbox-gl-draw/blob/master/src/draw_events.js#L140

https://github.com/mapbox/mapbox-gl-draw/blob/master/src/draw_events.js#L5

An ideal architecture would let us separate draw modes so that the logic for each type of drawing is separate. Something like

* There's a global click handler that does featuresAt
* Each mode can subscribe to specific types of clicks and on specific features

**Comment by mcwhittemore** [comment]
@tmcw - wanna take a look at #258 and see if its going in the direction we've talked about.
