### ISSUE TITLE
Make data URIs in the CSS instead of referencing the standalone SVGs

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#261]
Like it's parent project (mapbox-gl-js) the necessary icons should be inline data URIs in the CSS rather than references to the standalone files. This provides for far easier dependency management in client projects, only having to depend on the .js and the .css.

I assume this could be accomplished as part of the build process, but I don't even think mapbox-gl-js does that, I think the icons are managed manually in the CSS there.

**Comment by averas** [comment]
I can see that this was actually already adressed and solved as of https://github.com/mapbox/mapbox-gl-draw/commit/e045b96db52a7c43dd2e0a50e9d6664924384b14, however, it was then reverted as part of https://github.com/mapbox/mapbox-gl-draw/commit/fcfffeb72581966daf9999f8bbb9f869c92de687.

Since the latter commit was actually for the benefit of better CSS name spacing and did not mention the icons, can I assume the revert was unintentional?

@mayagao @kelvinabrokwa @mcwhittemore

**Comment by averas** [comment]
It may that @mayagao took the opportunity to act on #118. I think, as mentioned on that issue, as long as it's name spaced (and follow the same convention as its parent project!) it's fine.

**Comment by mcwhittemore** [comment]
@averas Nice catch. I think some wires got crossed here. Lets get these back into data uris.

**Comment by averas** [comment]
Cool, I'll go ahead and fix a PR.

**Comment by mcwhittemore** [comment]
Thanks @averas

**Comment by mcwhittemore** [comment]
Closed by f39f59f3960a42716c9f15a27098fa67c1d73382
