### ISSUE TITLE
events need to be objects not strings or arrays

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#271]

**Comment by davidtheclark** [comment]
@mcwhittemore Is this done as of #407? I don't really know what this issue is addressing.

**Comment by mcwhittemore** [comment]
`map.fire('meh', 'string')` and `map.fire('meh', ['value'])` don't work well with how mapbox-gl does events. I'm pretty sure you've fixed this, but I'm not 100%

**Comment by mcwhittemore** [comment]
@davidtheclark double checked through the code to make sure this was fixed in #407, it was. Closing.
