### ISSUE TITLE
simple_select vs direct_select is not intuitive

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#276]
The goal of simple select is to be able to quickly select and drag multiple features.

The goal of direct select is to edit the shape of a single feature

Currently moving from simple to direct is done by clicking on the feature. This isn't clear.

Not being able to drag a feature when in direct select is also a problem.

Leaving direct_select is hard and doesn't seem to happen for a clear reason.

---

If we show the vertices in simple select mode than clicking on one of those would move us into direct_select mode.

**Comment by kiRach** [comment]
Hey @mcwhittemore, just checked the new version (0.6.0-rc4) of `mapbox-gl-draw` - great progress!

I have an issue with it and I think it's related with this topic so I decided to not create new issue. So the main problem in new version for me is having these two separate modes - `simple` when you can only move feature and `direct` when you change the shape of feature but can't move it. It could be helpful to have smth like a `mixed` mode - when you can do both: move feature and change its shape. Any plans about this? Do you need any help that I can contribute to this library?

**Comment by mcwhittemore** [comment]
@kiRach - I'd love the help.

I'm trying to model this off of how drawing tools like illustrator and sketch work which is why there is a break between these two modes. The modes shipped with Draw should adhere to those interaction paradigms. That said, I agree that this isn't the only kind of paradigm that one might want with this kind of tool. Both you and @drewbo have brought up different kinds of paradigms a few times now.

Longterm I'd love the modularity provided by a mode system to be exposed to end-users so they can replace out the default interactions with their own. Maybe people will even make their own interaction modules. I think this is how we should support something like a `mixed` mode. Does this sound like something you'd like to take on?

I just opened an issue on this at https://github.com/mapbox/mapbox-gl-draw/issues/289 so we can move a more detailed convo to that ticket.

**Comment by samanpwbb** [comment]
I just reworked cursor states with https://github.com/mapbox/mapbox-gl-draw/pull/336 and I think we're in better shape. 

simple_select:
- Always shows a crosshair when hovering over polygon areas, line lines, to let the user know they can move on drag.
- Always shows a pointer when hovering over polygon lines / vertexes, line vertexes to let user know they can click to enter another mode

direct_select:
- Always shows default grab on polygon areas, line lines, to let user know a drag or click will result in default behavior (pan the map).
- Always show a crosshair when hovering over polygon vertexes, midpoints, and line vertexes to let user know they can move on drag.

A further step would be to style features differently depending on which mode they're in, but I don't think that's necessary.

**Comment by mcwhittemore** [comment]
@samanpwbb thanks! I think this should help a lot. I'm going to close this for now, we can reopen it if we find we need to do more work to help make the transition between these modes feel seamless.
