### ISSUE TITLE
Continue drawing a line or polygon after you have stopped

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#278]
When editing a feature you should be able to re-enter the draw mode

**Comment by bensleveritt** [comment]
Vaguely related: It'd be nice if you could select an existing line and then continue.

Particularly I'd like to start the line drawing from an existing point.

**Comment by mcwhittemore** [comment]
@bensleveritt I think we're saying the same thing.

Just to make sure.

There is a line on the map but it is in complete. I want to click on the last node and be back in the drawing mode so I can add a few more segments. Does that sound right?

**Comment by bensleveritt** [comment]
Pretty much.

I'd also like to select a point, which changes the mode to 'draw_line_string', and carry on creating a line string, with the first point already pre-populated.

Here's an example I hacked Draw to do (passing an origin to the opts, that creates the 1st point before starting):

![example](https://zippy.gfycat.com/SlowBiodegradableGoldenmantledgroundsquirrel.gif)

Seems like passing in an existing feature to the changeMode options, could continue a feature, rather than starting anew.

**Comment by bensleveritt** [comment]
Not related, but should the map zoom in on completion? Should I disable and re-enable on interaction?

**Comment by mcwhittemore** [comment]
Turning a point into a line_string is out side of what draw should do, but I agree that passing a feature its draw mode should continue drawing. This will also need a way to indicate which direction to continue drawing such as 'first' or 'last'.

For the Draw UI this continue drawing should happen by reclicking on selected node. For line strings this will be the start and end positions. For polygons, this will be any position.

**Comment by bensleveritt** [comment]
Sounds good to me

**Comment by mcwhittemore** [comment]
Line works, polygon does not. We should prototype this as a [custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw) and if the functionality works well, bring it into draw.

**Comment by heaven** [comment]
Hi @bensleveritt @mcwhittemore, we're building an indoor navigation map, can you please point me to the docs on how I can continue an existing line? We're defining routes inside a building and need the ability to connect to an existing line. Thank you!

**Comment by mcwhittemore** [comment]
@heaven It sounds like you are trying to a graph which GeoJSON does not support sadly. To continue drawing a line, you call `draw.changeMode` with the `draw_line_string` options and the feature you want to edit. Here is where this can be found in the docs: https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/API.md#changemodemode-string-options-object-draw.

**Comment by pieteroskam** [comment]
What I did is, when editing a line, and when a user then clicks on the "draw_line_string" control, It continues editing the existing line.

`map.on('draw.modechange', function(e){
    console.log(e);
    //if there already is a line continue editing this line
    if(e.mode === "draw_line_string" && draw.getAll().features.length > 0){
        let feature  = draw.getAll().features[0];
        draw.changeMode('draw_line_string', {
            featureId: feature.id,
            from: feature.geometry.coordinates[feature.geometry.coordinates.length - 1]
        });
    }


});`
