### ISSUE TITLE
Support mapbox-gl-js v0.16.0

### ISSUE THREAD

**Issue by timiyay** [mapbox/mapbox-gl-draw#282]
`mapbox-gl-draw` 0.4.0 fails to `npm install` if the same project includes `mapbox-gl-js` 0.16.0

**Background**

My project is including `mapbox-gl-js` and `mapbox-gl-draw` in our `package.json`, rather than loading it via the Mapbox CDN. 

We're doing this so we can build our project using the `earcut-final` branch of `mapbox-gl-js`, which fixes a critical bug in our app (see https://github.com/mapbox/mapbox-gl-js/issues/2300)

`earcut-final` was recently rebased on 0.16.0, which forced us to move versions, and is causing our builds to break due to `mapbox-gl-draw` failing to install.

**Comment by mcwhittemore** [comment]
mapbox-gl-js@0.16.0 has a few breaking changes that mapbox-gl-draw@0.4.0 does not handle. 0.6.0 is getting close to being ready to move past being experimental, so it might be worthwhile to upgrade.

If you aren't comfortable with making this upgrade, I'm also open to accepting PRs against the 0.4 branch until 0.6.0 is out of the experimental stage.

**Comment by timiyay** [comment]
@mcwhittemore thanks for suggestions.

Our immediate issue was solved by rolling back to `mapbox-gl-js` 0.14.2 (https://github.com/mapbox/mapbox-gl-js/issues/2401).

We'll be taking to 0.16.0 upgrade a bit slower now, so we can hopefully wait until `mapbox-gl-draw` 0.6.0 is ready. If not, I'll look at the 0.4 compatibility PR at the time we need to upgrade.

**Comment by mcwhittemore** [comment]
Sounds great @timiyay
