### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-draw#285]
I can’t figure out how to respond to events. I have successfully added the controls and can draw polygons on the map. However, I can’t seem to understand how to respond to events.
 
I am currently doing this:
 
that.map.once("draw.deleted", e => {
                console.log("hi");
});
 
But I whenever I make anything using Draw and delete it using the GUI controls, that function never gets called. If it helps, I called draw.delete(id) on my draw object and it says that delete is not a defined method on that object. Is this a bug, or am I doing something wrong. I am using the latest mapboxgl.

**Comment by mcwhittemore** [comment]
@stackTom what version of Draw are you using?

**Comment by stackTom** [comment]
@mcwhittemore According to my package.json file, it is version 0.4.0.

**Comment by mcwhittemore** [comment]
Ah, in 0.4 the event is called 'draw.delete' - https://github.com/mapbox/mapbox-gl-draw/blob/0.4/API.md#drawdelete

**Comment by stackTom** [comment]
Okay that worked. However, the event only seems to fire when the first feature is created. For example, I create a square polygon, and the event fires. It doesn't fire anymore regardless how many new polygons I create until I refresh the page.

**Comment by mcwhittemore** [comment]
@stackTom can you provide a link to an example?

**Comment by mcwhittemore** [comment]
Closing this for now. @stackTom 0.6 is getting close to releasing and when it does I'm going to drop support for 0.4 so making the upgrade soon would be good.

**Comment by stackTom** [comment]
Upgraded to the latest mapboxgl js and Draw as well as changed map.once to map.on, and it always fires off events now. Thanks again for the help.
