### ISSUE TITLE
Show/hide individual controls after Draw has been initiated

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-draw#286]
I think this would be useful but don't think it's possible right now.

Use case is if a user is editing a Polygon layer, I only want the Polygon button to show. If they then edit a LineString feature, I want to hide the polygon button and show the line button. So I want to dynamically show/hide buttons depending on the feature being edited.

There is a workaround by directly enabling/disabling the controls.

**Comment by mcwhittemore** [comment]
This kind of functionality is out side of the scope of this lib. If you want to do dynamic things with the control buttons, you should disable Draws and create your own.
