### ISSUE TITLE
Changing a feature's properties and updating via draw.add does not work

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#287]
Currently draw does not seem to consider mutation of properties a change so the "needsUpdate" is not triggered when passing in a feature with an existing id with non-updated coordinates but with updated properties. 

If you want to update the properties of an existing feature in the store you have to delete it and add it again...

**Comment by mcwhittemore** [comment]
@averas draw does not use the properties when rendering a feature. Are you saying that if you do a get after adding you get the old props? Which version is this for?

**Comment by averas** [comment]
This is for v0.6.0-rc4.

Exactly as you describe.

```
var feature = { type: 'Point', properties: {}, coordinates: [0, 0], id: '123' };
Draw.add(feature);
feature.properties.foo = 'bar';
Draw.add(feature);
Draw.getAll(); // Feature returned without the property set
```

**Comment by mcwhittemore** [comment]
Draw makes its own copy of a feature so editing properties in place like this won't work.

I think you should be able to re-add the feature though.

**Comment by averas** [comment]
> I think you should be able to re-add the feature though

Which is what I do (as shown in the example above). I think the coordinates have to change for Draw.add() to merge in modifications on a feature that is already present in the store.

**Comment by mcwhittemore** [comment]
Sorry, I was traveling when I made that comment and read too quickly :(.

I'm going to grab this today, but in the future please feel free to just submit PRs when you see an error. I generally find that to be a much faster way to make fixes and this project is very open to PRs. Getting more hands on this project is a great way to help stabilize it.

**Comment by averas** [comment]
@mcwhittemore Of course! Sometimes when time is limited it's handy to just create an issue as a reminder...

I hope I didn't come off as passive aggressive or something. :-)

**Comment by mcwhittemore** [comment]
@averas nbd. I feel really far behind on this so I'm likely to read too much into comments :( Thanks for clarifying. 

I just opened a PR to fix this. A review would be great. :)

**Comment by averas** [comment]
I'm on it!
