### ISSUE TITLE
Custom styles do not work

### ISSUE THREAD

**Issue by kiRach** [mapbox/mapbox-gl-draw#288]
In API.md there is an info about using custom styles - `Styling Draw`, but it doesn't work. I've tried all examples - no success. Also, in API.md there is an example which says that option name for custom styles is `style` (singular) when you initialize the new Draw. But in code, here: https://github.com/mapbox/mapbox-gl-draw/blob/master/src%2Foptions.js I see that options name is `styles` (plural). So it's not clear what is the right option name.

**Comment by kiRach** [comment]
Ok, I've found a way to customize styles:
```
this._map.setPaintProperty('gl-draw-active-polygon.hot', 'fill-color', '#000000');
```

It works, but it's not clear - should I change the both layers `hot` and `cold` or not, also I think would be nice to have more convenient way of doing this. But for now this works.

**Comment by mcwhittemore** [comment]
@kiRach, this is working for me. Can you create an example of this problem on jsbin so I can take a look at it?

Thanks for pointing out the naming error.

**Comment by mcwhittemore** [comment]
@kiRach can you paste in your styles here? I'd love to take a look at this soon.

**Comment by kiRach** [comment]
@mcwhittemore Hey, sorry for long reply. I've tried to create example of this in jsbin but I didn't find any published  `mapbox-gl-draw.js` to include it in example. But basically the problem was when I created `new mapboxgl.Draw()` object:

```javascript
let Draw = mapboxgl.Draw({
    drawing : false,
    keybindings : false,
    displayControlsDefault: false,
    style: [{
      'id': 'custom-polygon',
      'type': 'fill',
      'filter': ['all', ['==', 'active', 'true'], ['==', '$type', 'Polygon']],
      'paint': {
        'fill-color': '#f16852',
        'fill-opacity': 0.1
      },
      'interactive': true
    }]
});
```

Then I've put a polygon into map and set it to active state - and colors still were default. I tried to change `style` to `styles` - same result. THe only way I've managed it to work was override default theme properties using `map.setPaintProperty(...)` as in my second reply in this thread,
