### ISSUE TITLE
Custom Modes

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#289]
The modularity provided by a mode system should be exposed to end-users so they can replace out the default interactions with their own.

**Comment by drewbo** [comment]
@mcwhittemore any ideas on how to implement this? It seems pretty tricky because the modes are so closely tied to some of the api methods ala https://github.com/mapbox/mapbox-gl-draw/blob/master/src/api.js#L129 instead of falling back to the larger mode modules. Happy to kick around some ideas + code as we're looking to use this again in another project with some custom behavior

**Comment by drewbo** [comment]
Actually, the more I look; the file I mentioned is really the only place where the modularity of the mode system breaks down a little (nice job!). Would the next steps to implementing this feature be something like:
- Abstract the API checks for other custom modes
- Document required methods for a custom mode module/object
- Provide a method or option for loading those custom modes

**Comment by mcwhittemore** [comment]
@drewbo sorry for just seeing this.

Those bullet points seem right to me.

We'll want to make sure the API for these modes is really pretty solid. Asking people to write custom modes and then breaking the API a few times won't be good. My key concern is cleaning up how events are handled/registered.

**Comment by mcwhittemore** [comment]
Here is a ticket where @davidtheclark and I are talking about this problem - https://github.com/mapbox/mapbox-gl-draw/issues/459

**Comment by BhavanPatel** [comment]
@mcwhittemore @drewbo I think GeoJSON support rectangle... as I have seen in this [Demo](http://geojson.io/) and map seems mapbox.

**Comment by mcwhittemore** [comment]
@BhavanPatel GeoJSON supports Polygons and thus you can create GeoJSON rectangles. My comments in #604 aren't trying to say this isn't possible, but that Rectangles are out of the scope of Draw. It should be noted, that Draw used to have Rectangle support and it caused unexpected functionality multiple times so it was removed. Around this same time, we decided that Draw would only support the code [GeoJSON Spec](https://tools.ietf.org/html/rfc7946) and that custom modes could provide for extra functionality such as Rectangles and Circles.

Personally, I really want a mode that lets me Draw hexagons. Sadly I don't have a lot of time for this project currently. @drewbo has shown interest in getting Custom Modes to happen, but more help from others in the community would be great too.
