### ISSUE TITLE
Added vs is about to be added

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#294]
From #292

There is no way of determining in the event callbacks or via the get()/getAll() methods which features are actually added and which are about-to-be-added

@averas can you provide an example here along with some thoughts on how you think this should work.

**Comment by averas** [comment]
Yes, I will check the status of this on <code>master</code>.. may be related to one of the issues you closed earlier today.

**Comment by averas** [comment]
As I suspected, this is not a problem in <code>master</code> anymore. The <code>draw.changed</code> event is not fired when starting to draw like it was before.

For my personal use case I am not dependent on the ability to interact with features that have not yet been added/committed but there might be other use cases where it is of interest, but you may close this issue for now if you want to.

**Comment by mcwhittemore** [comment]
Gotcha. Yea, I just made sure the feature isn't emitted until it is valid geojson. I'll close this for now and see if anyone else brings up this problem.
