### ISSUE TITLE
Finding out coordinates of a polygon

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-draw#299]
If this isn't the place to ask questions, please close this, and direct me to the right place. However, is there a way to get the coordinates of a polygon? I need to be able to draw a square polygon, and then query mapbox for points within that polygon. Using the draw.changed event leads to me receiving feature objects whenever a polygon's points and lines are being drawn, not at the very end when it is fully drawn. I tried using draw.mode.default.selected.start, but I can't get this event to fire. Shouldn't this fire when, after the polygon has been created, I select the polygon with the mouse? Thanks for any help, and forgive me if this is the wrong place to ask questions like this.

**Comment by mcwhittemore** [comment]
`draw.mode.default.selected.start` is the old name for `draw.mode.simple_select.selected.start`. Sorry, this name change was missed in the docs. I've updated this in 974d5ea247a0e4bee074c9174725e8a6a6dead69.

This should help you do what you want. You can also use the `draw.modechange` event to track these kinds of things.

**Comment by mcwhittemore** [comment]
This was a docs problem fixed by 974d5ea
