### ISSUE TITLE
Selecting the feature you want to select is not always possible.

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#300]
![image](https://cloud.githubusercontent.com/assets/32314/14959036/87c2ba98-105b-11e6-9933-47d066fcf3d7.gif)

![image](https://cloud.githubusercontent.com/assets/302992/14900690/bade5cce-0d46-11e6-8d2a-d9264c5e3f42.gif)

This is a pretty complicated interaction. One solution that @scothis has put forth is to sort the features by size so that the smallest feature is always on top. I think this is the next attempt we should try to fix this.

**Comment by tmcw** [comment]
Initial approach:

* Lines and points on top
* Polygons in area-sorted order

Stretch goal:

* Successive clicks on the same spot select the different geometries under the click target
