### ISSUE TITLE
mapbox-gl-draw is slow on retina display

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/mapbox-gl-draw#303]
Using mapbox-gl-draw on retina display causes ~ 6FPS (with ~ 30FPS on non-retina display with the same setup)

OS X 10.11.4
Google Chrome 50.0.2661.94 (64-bit)
mapbox-gl-draw e7321784f63dd8bd336c75117c27d47faf535a99

![kstf78x4sm](https://cloud.githubusercontent.com/assets/533564/15070592/90065e30-139e-11e6-867c-7671a3a0aa1d.gif)

**Comment by mcwhittemore** [comment]
Thanks for reporting this @stepankuzmin. I'm pretty sure this is an upstream issue, so I'm going to close it in favor of #296 which is tracking how Draw degrades the performance of mapbox-gl-js. I've noted this issue over there to make sure we remember to think about retina displays.
