### ISSUE TITLE
draw.deleted emits featuresIds that are really features

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#307]
I'd expect `featureIds` to be a list of featureIds, but it is a list of features.

**Comment by samanpwbb** [comment]
Where does this happen? The getFeatureIdsAt API method returns IDs.

**Comment by samanpwbb** [comment]
Just dug around for all cases of variables with names like, `featureId`, `featureIds`, and there are no cases where we emit features, only Ids.

**Comment by davidtheclark** [comment]
I think that in `delete()` features are being emitted, not ids: https://github.com/mapbox/mapbox-gl-draw/blob/master/src/store.js#L45.

Studio deals with it by mapping here: https://github.com/mapbox/studio/blob/dev-pages/src/datasets_components/editor/index.js#L296

**Comment by davidtheclark** [comment]
As of #407 `draw.deleted` emits features that really are features, so this is cleared up.
