### ISSUE TITLE
`getFeatureIdsAt` returns a bunch of undefined ids

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#308]
This should only return real feature ids.

**Comment by samanpwbb** [comment]
This was fixed with https://github.com/mapbox/mapbox-gl-draw/commit/e0583ebbb3603adf8f1cc802e7c1f3c03a02bbb1

Lines 46-48 here: https://github.com/mapbox/mapbox-gl-draw/commit/e0583ebbb3603adf8f1cc802e7c1f3c03a02bbb1#diff-da9897b34675d9a204d14f65d85a9b42R46
