### ISSUE TITLE
Removed window.usedClasses

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#309]
https://github.com/mapbox/mapbox-gl-draw/blob/5c6d051650b9f0de8fbe3d14934d530cf7c4f419/src/ui.js#L23-L25

Global variables will consistently cause bugs with multiple instances

**Comment by mcwhittemore** [comment]
Closed via 33fd39674fe1b76dfb65fd6fd4718b0b6148e7aa
