### ISSUE TITLE
Advanced draw operations for squares

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-draw#31]
- [ ] Click and dragging with the __alt key__ should draw a shape with fixed width+height with center pinning (i.e. the drawn layer expands in size across the canvas in both directions)
- [ ] Click and dragging with the __shift key__ should draw a shape with fixed width+height with top-left  pinning.

**Comment by tmcw** [comment]
This should be post-v1.

**Comment by mcwhittemore** [comment]
We're going to drop squares past the creation phase as they aren't something that can be added as they aren't GeoJSON.
