### ISSUE TITLE
Invalid LngLat object: (undefined, undefined) after direct_select Point feature

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/mapbox-gl-draw#310]
Changing mode to `direct_select` with id of feature with `Point` geometry type causes `Uncaught Error: Invalid LngLat object: (undefined, undefined)`

![2016-05-16 14 01 39](https://cloud.githubusercontent.com/assets/533564/15285111/c94cb00e-1b6e-11e6-9c9d-a30082de4e87.png)

**mapbox-gl-draw v0.6.2**

**Comment by mcwhittemore** [comment]
@stepankuzmin this is because `direct_select` doesn't handle Points. A different error message should be thrown that explains this though.
