### ISSUE TITLE
"draw.changed" event is no longer emitted after adding a new feature

### ISSUE THREAD

**Issue by kiRach** [mapbox/mapbox-gl-draw#316]
It should be due to latest changes in 0.6.4 version, because it used to work fine before.

When you initially add a new feature to the Draw - you expect that `draw.changed` will be fired.

**Comment by mcwhittemore** [comment]
@kiRach any chance you can get the PR in for this? A test for it would be great so it doesn't happen again.

**Comment by kiRach** [comment]
@mcwhittemore Ok, will try to investigate and make an PR for this in next couple days

**Comment by mcwhittemore** [comment]
@kiRach This bug turned out to be pretty big for us so I hunted it down but I didn't write tests... :(

https://github.com/mapbox/mapbox-gl-draw/commit/6860a3b548e41327e44db38058cb3d9ced7bdf7a#diff-855b05ea6fe92e5b91d6da40f15dae9fR58 provides the fix.

**Comment by davidtheclark** [comment]
@mcwhittemore What's the status on this? Here's what I see happening with `draw.changed` in relation to new feature creation:

- Fired when you click to create a new point.
- Not fired when you click to create a new line, but fired as soon as you move the mouse (and the line starts growing).
- Not fired when you click to create a new polygon, nor when you move the mouse. UNTIL you create the next vertex (still not fired) then move the mouse to start growing the second line.

**Comment by mcwhittemore** [comment]
@davidtheclark this was fixed by the commit I clicked above. I just forgot to close this. Closing it now.
