### ISSUE TITLE
Add hover properties

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#318]
According to https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#styling-draw there is a "hover" property. I expect something like this in my theme to display a cyan circle when hovering over a point:

``` json
  {
    "id": "gl-draw-hover-point",
    "type": "circle",
    "filter": ["all",
      ["==", "$type", "Point"],
      ["==", "hover", "true"],
      ["!=", "meta", "midpoint"]
    ],
    "paint": {
      "circle-radius": 7,
      "circle-color": "#0ff"
    },
    "interactive": true
  }
```

**Comment by mcwhittemore** [comment]
Currently hovered is only supported via the cursor classes. We should either get hover to be a style level detail or remove this from the API docs.

**Comment by samanpwbb** [comment]
I want to see if I can hover support to features in Gl draw.

**Comment by samanpwbb** [comment]
@mcwhittemore how do you feel about removing hover from the API? I don't think it's necessary.

**Comment by mcwhittemore** [comment]
Yea, we should remove it as its not implemented. If we want to bring it back, we can bring it back.
