### ISSUE TITLE
Stop invalid polygons from happening

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#319]
![image](https://cloud.githubusercontent.com/assets/1551510/15722343/2ec7e4e6-280b-11e6-9b63-a32d817e66e9.png)

With mapbox-gl-js@0.19.0 Draw needs to make sure it is creating valid Polygons...

**Comment by samanpwbb** [comment]
To do this right, i think we'll need to add a notification event to mapbox-gl-draw that sends out error notifications.

**Comment by mcwhittemore** [comment]
@samanpwbb are you going to use one event or two for this? We need to mention when a feature goes from valid to invalid and from invalid to valid.

**Comment by samanpwbb** [comment]
Hm, yeah, we'll need two events.

**Comment by mcwhittemore** [comment]
@tmcw just mentioned that GeoJSON doesn't guarantee that Polygons aren't self intersecting.

> A LinearRing is closed LineString with 4 or more positions. The first and last positions are equivalent (they represent equivalent points).

> For type "Polygon", the "coordinates" member must be an array of LinearRing coordinate arrays. For Polygons with multiple rings, the first must be the exterior ring and any others must be interior rings or holes.

Opening an upstream issue.

**Comment by samanpwbb** [comment]
I think we can close this. This is entirely as an issue in the renderer, since these features aren't invalid geoJSON.
