### ISSUE TITLE
Increase grabsize

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#322]
.5 is too small:
https://github.com/mapbox/mapbox-gl-draw/blob/e818634859aab8e324f2d85ff3e65a08aac28192/src/lib/features_at.js#L24

I want a value of closer to 2 for the project I am working on now. Should I make this value configurable of just set it to 2? cc: @mcwhittemore

**Comment by mcwhittemore** [comment]
@samanpwbb Lets up it to two for now (.5 was just picked randomly). Lets keep this issue open though and see if different style want a different size.
