### ISSUE TITLE
every single mouse move sets gl container class

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#335]
This seems bad:

![screen shot 2016-06-08 at 5 06 55 pm](https://cloud.githubusercontent.com/assets/108094/15910937/565948ca-2d9b-11e6-8f8c-8d7f308383de.png)

Coming from https://github.com/mapbox/mapbox-gl-draw/blob/99e6ac6195f2e9ca5f3a8c6c42137db0fc5afebc/src/ui.js#L42-L45

**Comment by mcwhittemore** [comment]
@samanpwbb is this updating the class every time or just looking to see if it needs to be updated?

**Comment by samanpwbb** [comment]
Appears to be updating constantly.
