### ISSUE TITLE
immediately double clicking with polygon tool breaks the map 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#340]
All features disappear and this error shows up:

![screen shot 2016-06-09 at 12 02 34 pm](https://cloud.githubusercontent.com/assets/108094/15936739/1cf86170-2e3a-11e6-8488-f37d0a77db46.png)

We need to prevent user from completing polygons with less than 3 points.

**Comment by mcwhittemore** [comment]
feature.isValid() should be used to know if there are enough points.
