### ISSUE TITLE
Sometimes final point in polygon ends up with many vertices

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#345]
I clicked 4 times to create a polygon. Then, I tried to drag the top corner of the polygon. I was able to pull a 5 new vertices out of what seemed like one vertex:

![screen shot 2016-06-10 at 10 16 00 am](https://cloud.githubusercontent.com/assets/108094/15967148/68a1f928-2ef4-11e6-8a95-e8c194c1c42d.png)

I do not have a consistent way to reproduce this bug.

**Comment by mcwhittemore** [comment]
Do we know if points are equal?

**Comment by samanpwbb** [comment]
This happens after moving a shape.
