### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#353]
Draw _mostly_ works via touch right now. There are three outstanding issues:
- No way to delete nodes
- No way to move features or nodes or create new nodes.
- Difficult to complete shapes.

Solutions:
- Add touch + hold, then drag to drag things.
- Make the delete button delete nodes, not shapes, if a node is selected.
- touch + hold to complete shapes

**Comment by samanpwbb** [comment]
Just editing the initial post after playing with GL draw on mobile safari for a while. Getting to full touch support is definitely within reach.

**Comment by davidtheclark** [comment]
> Make the delete button delete nodes, not shapes, if a node is selected.

@samanpwbb Is that an issue with Studio's delete button, or with Draw's trash?

**Comment by mcwhittemore** [comment]
`Draw.trash()` does what @samanpwbb wants.

**Comment by davidtheclark** [comment]
That's what I was thinking — so that particular point must apply to Studio's delete button.

**Comment by mcwhittemore** [comment]
People who read this repo must have such an interesting mental modal of Studio. :)

**Comment by mcwhittemore** [comment]
We should prototype this as a [custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw).
