### ISSUE TITLE
Create and split mulit-line / multi-polygons

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#355]
Make it possible for user to select more than one polygon and join them into a single multipolygon, or to select a multi-* and split it into components.

Doesn't need UI. Could be a keybinding, and a `polygonJoin` method exposed in the API that lets user pass in an array of features.

**Comment by tmcw** [comment]
Is this about joining multiple polygons into a multipolygon, or about merging polygons geometrically? Joining polygons (unioning) is super difficult algorithmically and is something Turf is still struggling to implement in a robust way. Upstream difficulty/risk level is high.

**Comment by samanpwbb** [comment]
> Is this about joining multiple polygons into a multipolygon

I don't have a geometric merge in mind. It's relatively straightforward to take a bunch of polygons and stick them in a multi-poly right?

I see a merge feature useful in cases where many related polygons share the same properties and user wants to manage all these features as a single feature.

I see a un-merge feature useful in cases where user has imported data but wants to adjust only one component of the multipolygon.

**Comment by mcwhittemore** [comment]
@samanpwbb I see this as two controls

- merge: converts multiple features of the same type into one Multi* feature
 - split: converts a Mulit* feature into many features

With merge MultiPolygon should be treated as a Polygon when decided if you can merge or not. This way you can merge polygons into an existing multi polygon.

The merge should emit a delete event for all features that have been collected together.

Should this be part of simple_select? Do we want this in any other mode? If we do, than we really need to find a better way to handle 'selected'.

**Comment by samanpwbb** [comment]
> Should this be part of simple_select?

I think it can be part of simple_select, yep.

**Comment by ghoshkaj** [comment]
I'd like to start working on this.  @mcwhittemore is https://github.com/mapbox/mapbox-gl-draw/issues/355#issuecomment-225923314 still an accurate way to approach this problem?

**Comment by samanpwbb** [comment]
@ghoshkaj yeah, i think that makes sense, ultimately, we will want four actions:

![web 1920 1](https://cloud.githubusercontent.com/assets/108094/17978395/dfa8abb0-6ac3-11e6-899c-d890a3b195d8.png)

**Comment by mcwhittemore** [comment]
@ghoshkaj What @samanpwbb has outlined is a good start. Ideally this will be something exposed on the api that takes a list of feature ids. Draw should then emit an update and deleted event for the features that are affected.

This should also be able to be done via a Draw control (like starting to draw a line or polygon).

**Comment by ghoshkaj** [comment]
Sounds good! Will get cracking on this now.

**Comment by ghoshkaj** [comment]
Opening a new ticket about the interior ring: https://github.com/mapbox/mapbox-gl-draw/issues/518
