### ISSUE TITLE
Arrow keys should nudge shape if selected

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#359]

**Comment by davidtheclark** [comment]
@samanpwbb, do you have an idea already about what would be an appropriate number of degrees to shift with an arrow key nudge?

**Comment by samanpwbb** [comment]
No, that's a good question. Don't have a good sense, but ideally we make it zoom-level dependent.

**Comment by mcwhittemore** [comment]
Yea, we should make this zoom-level dependent. [map.unproject({x, y})](https://www.mapbox.com/mapbox-gl-js/api/#Map#unproject) will let us move a constant number of pixels.

**Comment by mcwhittemore** [comment]
This is a great idea. It should probs be in v2. But for now it should happen as a [custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw)
