### ISSUE TITLE
Don't throw errors when polygons have duplicate positions and make sure coordinates is always valid

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#360]
Per https://github.com/mapbox/mapbox-gl-draw/pull/356#issuecomment-225919262

- [x] remove the position validation errors
- [x] use comments to clarify the intent of `incomingCoords` and `setCoordinates`
- [ ] write tests against the buildFeatureCoords function so it doesn't regress

**Comment by samanpwbb** [comment]
Added comments here: https://github.com/mapbox/mapbox-gl-draw/pull/377

Testing this is a serious lift, we either need to refactor our code so modes are less stateful, made up of less stateful functions that cna be tested individually, or we need integration tests that allow us to actually  dragging a feature in draw and check the geometries before and after drag.

**Comment by mcwhittemore** [comment]
Our tests cover this pretty well now.
