### ISSUE TITLE
Better selection support

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#365]
Currently an end user needs to listen to the `draw.modechange`, `draw.simple_select.selected.start` and `draw.simple_select.selected.end` events to know what is selected. This came out of removing the general concept of 'selected' internally. With #361 Draw will knows what is selected at the store level rather than at that mode level again, meaning we can provide ways for users to get information about what is selected.

At first lets stay away from unselected features as this gets into forcing renders and switching modes.

1. `Draw.getSelectedIds` should return all selected feature ids of valid features.
1. `draw.selected` should fire when a feature is selected and is valid or when a selected feature becomes valid.
1. `draw.unselected` should fire when a valid feature is unselected.

For the events we want to make sure we don't trash `draw.unselected` and `draw.selected` with the same ids. To do this, I think we want to the events to fire with the render cycle rather than when their state has changed.

/cc @davidtheclark

**Comment by davidtheclark** [comment]
> draw.selected should fire when a feature is selected and is valid or when a selected feature becomes valid.

Does this mean that you can select invalid features, with no event, and then if they become valid while they are selected an event is fired?

**Comment by mcwhittemore** [comment]
@davidtheclark that comment was about how selection might work. I don't think Draw should emit invalid geojson, so its just a comment about that.

**Comment by davidtheclark** [comment]
Closed by #368.
