### ISSUE TITLE
Standardize verb form of events

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#367]
Right now we have -ed forms ("deleted") and plain forms ("modechange"). In the mapbox-gl-js API it seems that they are all plain forms ("rotate", "move", "mousestart", etc.). I think we should probably make all the draw events plain form verbs as well.

- [ ] Change `deleted` event to `delete`.
- [ ] Change `changed` event to `change`.
- [ ] Change `modified` event to `modify`. *I'll also add that the ambiguity between `changed` and `modified` is pretty confusing. There should be more distinction here, and if we're changing the form we may as well change the word to be more precise.*
- [ ] Change `selected` to `select`. This could be done as part of #365.

**Comment by mcwhittemore** [comment]
I'm good with matching up with mapbox-gl-js.

The `change` vs `modify` events are really hard to distinguish in a short name because the only difference between them is how often they are fired. TBH, if we can get `draw.modify` to work well we could look at replacing `draw.change` with it.

Another name option is `draw.update`.

**Comment by davidtheclark** [comment]
I think the shortness of the name is less important than having a clear semantic distinction between the events. Change and modify are essentially synonyms.

**Comment by davidtheclark** [comment]
I don't see `draw.update` anywhere ... could you point to it in the code?

**Comment by mcwhittemore** [comment]
@davidtheclark `draw.update` was a suggestion to replace `draw.modify`

**Comment by davidtheclark** [comment]
Ah! Sorry :) Sure that's more clear. I guess I don't know what the actual distinction between events is yet, so not sure I'm the best judge.

**Comment by davidtheclark** [comment]
Done in #407.
