### ISSUE TITLE
Add unit tests for lib files

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#370]
I plan to do this soon, just wanted to file issue so work doesn't overlap.

Is there a rationale distinguishing the functions in `lib/` with their own file and the functions exported by `lib/util.js`? I'd like to know so that I add things to the right place, if I were to add things.

**Comment by mcwhittemore** [comment]
@davidtheclark `lib/util` was partial taken from Leaflet I think. Please feel free to break it up.

**Comment by mcwhittemore** [comment]
The only thing really left here is the polyfill... and a few edge cases in mode_handler and StringSet.

![image](https://cloud.githubusercontent.com/assets/1551510/16421095/d20b4ece-3d21-11e6-8661-0a6dd2346816.png)

**Comment by davidtheclark** [comment]
Addressed the polyfills lack with #427, and addressing mode_handler with #436.
