### ISSUE TITLE
Draws adds mapbox-gl-js to the global scope even when complied with browserify

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#373]
![image](https://cloud.githubusercontent.com/assets/1551510/16163350/baadd608-34a6-11e6-9b21-e133a5bc2dc1.png)

**Comment by mcwhittemore** [comment]
https://github.com/mapbox/mapbox-gl-draw/blob/b475035bded39942eb53ec34734c54027b007200/index.js#L30-L31

**Comment by davidtheclark** [comment]
Is the idea here that we definitely want to remove Draw from the global scope but only in v1 because it's a breaking change?

**Comment by mcwhittemore** [comment]
@davidtheclark feel free to fix this whenever. Its just in the 1.0.0 milestone because we're not going to 1.0.0 until it is closed.

**Comment by davidtheclark** [comment]
I don't know how to fix this because I'm not sure what our intended output should be. Do we want a UMD build that exposes a variable like `MapboxGLDraw` if there is no module system? If there *is* a global `window.mapboxgl` do we want to attach `Draw` to it?

**Comment by bensleveritt** [comment]
A UMD module definition would be appreciated. I understand it would probably break your current implementation, but it would help with compatibility with Webpack. I'm currently accessing Draw from `window.mapboxgl.Draw`, despite using ES2015 modules and `import`.

Just feels.. dirty...

**Comment by mcwhittemore** [comment]
@benjamintd - we don't use Webpack in any projects currently. I'm more than happy to improve the support for Draw, but we will need an outside contributor to do that. Are you up for it?

**Comment by bensleveritt** [comment]
Tada! PRs are worth a dozen words or something: https://github.com/mapbox/mapbox-gl-draw/pull/525

This is just a case of [setting Browserify to export a standalone module](https://github.com/substack/browserify-handbook#standalone).

Should be compatible with existing usage, but allows for more module loading configs. I've tested it with my setup (Webpack module loading), but I'd recommend trying it out to check it's still compatible with how you normally use it.

**Comment by bensleveritt** [comment]
Read through the un-uglified build and it seems to make sense. My concern mostly lies with the uglified version (not sure how well uglifying works with UMD modules).

**Comment by mcwhittemore** [comment]
Closed by #548
