### ISSUE TITLE
Why is opts opts

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#385]
https://github.com/mapbox/mapbox-gl-draw/blob/dd49728c885f6833c98949cb5a663b21ed510911/API.md#drawmodechange

```js
{
  mode: `direct_select`
  opts: '123123123'
}
```

Is opts a feature ID? If so, can we call it feature id?

**Comment by mcwhittemore** [comment]
@tmcw - for `simple_select` this is an array of feature ids. I've also thought about having the `draw_*` modes continue drawing by passing in the feature id and the position to start at.

**Comment by davidtheclark** [comment]
As of #407 this information is no longer in the event data.
