### ISSUE TITLE
deleteAll is documented to return the Draw object but doesn't

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#386]
https://github.com/mapbox/mapbox-gl-draw/blob/f7a1167ddebb0be1e626cf2320be271ae90642c0/src/api.js#L87

https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#deleteall---draw

This function can't be chained: it returns undefined.

**Comment by davidtheclark** [comment]
Replaced by the more general #413.
