### ISSUE TITLE
Events re-vamp

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#397]
I think that it may be worth our while to think through and re-vamp all of the events that get emitted by Draw. We could tackle #395, #393, #367, #316, #271, #307, #385, and other undocumented confusions all at once in a little overhaul. 

Issues, questions, and debugging difficulties keep coming up as a result of one of the following:

- An event that seems like it should exist not existing (e.g. add/create).
- Events are firing in unintuitive or unclear ways.

*I think we need to more clearly define our intentions, in documentation and tests, about exactly when each event is going to fire*. The event timing should make intuitive sense, and should be useful for Studio.

I'm going to draft proposed docs for re-vamped events below, and if you think this isn't a silly effort we can alter it according to your feedback, then I'll work on a PR to make it happen.

**Those of you with more experience trying to use Draw's events in Studio ( @mcwhittemore , @samanpwbb , @ghoshkaj , @tmcw ) please chime in about whether the proposal below would fulfill the needs and make things better** (or if it's not worth trouble).

---

I'm thinking maybe all these events should fire *only as a result of user interaction tracked by Draw* — i.e. not when Draw's API is used to programmatically do things like change modes, or add and delete features. (Which would avoid weirdness like this: https://github.com/mapbox/studio/blob/dev-pages/src/datasets_components/editor/index.js#L214)

### `draw.selectionchange`

Fired when the selection is changed (i.e. something is selected or deselected) as the result of a user interaction. The following interactions will trigger this event:

- Click on a feature to select it.
- Create a box-selection that includes at least one feature.
- When a feature is already selected, shift-click on another feature to add it to the selection.
- Click outside the selected feature(s) to deselect.
- Finish creating a feature.

The event data is an object with the following shape:

```js
{
  // Array of GeoJSON objects representing the features 
  // that are selected, after the change
  features: [{..}, {..}, ..]
}
```

### `draw.create`

Fired when a feature is created as the result of a user interaction. The following interactions will trigger this event:

- Finish drawing a feature. Simply clicking will create a Point. A LineString or Polygon is only created when the user has finished drawing it — i.e. double-clicked the last vertex or hit Enter — and the drawn feature is valid.

The event data is an object with the following shape:

```js
{
  // Array of GeoJSON objects representing the features that were created
  features: [{..}, {..}, ..]
}
```

### `draw.delete`

Fired when one or more features are deleted as the result of a user interaction. The following interactions will trigger this event:

- Click the Trash button when one or more features are selected in `simple_select` mode.
- Hit the Backspace or Delete keys when one or features are selected in `simple_select` mode.

The event data is an object with the following shape:

```js
{
  // Array of GeoJSON objects representing the features that were deleted
  features: [{..}, {..}, ..]
}
```

### `draw.update`

Fired when one or more features are updated as the result of a user interaction. The following interactions will trigger this event, with different `type` properties in the event data:

- Finish moving one or more selected features in `simple_select` mode. The event will only fire when the movement is finished — i.e. when the user releases the mouse button or hits Enter. Type: `'move'`.
- Finish moving one or more vertices of a selected feature in `direct_select` mode. The event will only fire when the movement is finished — i.e. when the user releases the mouse button or hits Enter. Type: `'change_coordinates'`.
- Delete one or more vertices of a selected feature in `direct_select` mode, which can be done by hitting the Backspace or Delete keys or clicking the Trash button. Type: `'change_coordinates'`.
- Add a vertex to the selected feature by clicking a midpoint on a selected feature in `direct_select` mode. Type: `change_coordinates`.

This event will not fire when a feature is created or deleted. To track those interactions, use `draw.create` and `draw.delete`.

The event data is an object with the following shape:

```js
{
  // Array of GeoJSON objects representing the features that were updated
  features: [{..}, {..}, ..],
  type: 'move' // or 'changes_coordinates'
}
```

### `draw.modechange`

Fired just after the current mode stops and just before the next mode starts. A render will not happen until after all event handlers have been triggered, so you can force a mode redirect by calling `Draw.changeMode()` inside a `draw.modechange` handler. For information about when modes change, read about the modes.

The event data is an object with the following shape:

```js
{
  // The next mode, i.e. the mode that Draw is changing to
  mode: 'direct_select'
}
```

**Comment by tmcw** [comment]
Speaking exclusively from the Studio perspective:

Instead of `select` and `deselect` with one saying the newly-selected features and the other saying the ones that left the selection, could we have a single `selectionchange` event that emits the complete selection every time it changes? From Studio's perspective, this would be simpler than our current system with no information loss.

Besides that potential change, I'm 👍 here except for opts which I agree needs a rename.

**Comment by davidtheclark** [comment]
> could we have a single selectionchange event that emits the complete selection every time it changes

Yes! I'd be fine with replacing `select` and `deselect` with `selectionchange`.

**One question I forgot to raise above: Is it more useful for these events to include complete features in their data, or just ids?**

**Comment by tmcw** [comment]
I think features definitely make sense, we already have them and passing around references to the objects is free.

**Comment by ghoshkaj** [comment]
Yes. We absolutely need this. At least for Studio.

For draw.update, we can be more fine grained and break it down to four types of updates: 

- drag a feature (simple_select)
- add vertex  to a feature  (direct_select)
- move vertex in a feature (direct_select)
- delete vertex in a feature (direct_select)

Is there a reason that we shouldn't break down  into these four events?

**Comment by davidtheclark** [comment]
@ghoshkaj Does it help Studio to differentiate between those updates? Or are you just thinking it might help generally?

I imagine we could have both a general `draw.update` and more specific update events fire at the same time — so if you drag a feature you get `draw.update` and `draw.featuremove` (or something).

**Comment by ghoshkaj** [comment]
Mostly I'm thinking about History events. But I'm okay if there's a good reason not to.

**Comment by davidtheclark** [comment]
> Mostly I'm thinking about History events. 

That makes sense. I don't know any reason not to.

**Comment by ghoshkaj** [comment]
So this is what I'm talking about: https://github.com/mapbox/studio/issues/7039

**Comment by tmcw** [comment]
Yep, so two things came up w voice:

- I totally forgot about vertex selection states: that's the missing link in the most recent refactor and super important. Could be captured as a vertex index in the `selected` event object
- On the Studio side, we _could_ do a diff to determine whether a vertex was moved, removed, added, or deleted. But also on the draw side, we already have this information, so maybe we can include it as a property in the changed event?

**Comment by davidtheclark** [comment]
Based on the discussion, how about adding these events and removing select/deselect:

---

### `draw.selectionchange`

Fired when the selection is changed (i.e. something is selected or deselected) as the result of a user interaction. The following interactions will trigger this event:

- Click on a feature to select it.
- Create a box-selection that includes at least one feature.
- When a feature is already selected, shift-click on another feature to add it to the selection.
- Click outside the selected feature(s) to deselect.

The event data is an object with the following shape:

```js
{
  // Array of GeoJSON objects representing the features 
  // that are selected, after the change
  features: [{..}, {..}, ..]
}
```

### `draw.featuremove`

Fired when one or more features are moved as the result of a user interaction. The following interactions will trigger this event:

- Finish moving one or more selected features in `simple_select` mode. The event will only fire when the movement is finished — i.e. when the user releases the mouse button or hits Enter.

Note that the same interaction will also trigger a `draw.update` event.

The event data is an object with the following shape:

```js
{
  // Array of GeoJSON objects representing the features that were moved
  features: [{..}, {..}, ..]
}
```

### `draw.vertexcreate`

Fired when a new vertex is created as the result of a user interaction. The following interactions will trigger this event:

- Click a midpoint on a selected feature in `direct_select` mode.

Note that the same interaction will also trigger a `draw.update` event.

The event data is an object with the following shape:

```js
{
  // GeoJSON object representing the feature with the new vertex
  feature: {..},
  // Dot-notation path to the newly created vertex
  vertex: "1.3" // example
}
```

### `draw.vertexselect`

Fired when a vertex is selected as the result of a user interaction. The following interactions will trigger this event:

- Click a vertex or midpoint on a selected feature in `simple_select` mode (thereby entering `direct_select` mode).

The event data is an object with the following shape:

```js
{
  // GeoJSON object representing the feature whose vertex is selected
  feature: {..},
  // Dot-notation path to the selected vertex
  vertex: "1.3" // example
}
```

### `draw.vertexmove`

Fired when a vertex is moved as the result of a user interaction. The following interactions will trigger this event:

- Finish moving a vertex in `direct_select` mode. The event will only fire when the movement is finished — i.e. when the user releases the mouse button or hits Enter.

Note that the same interaction will also trigger a `draw.update` event.

The event data is an object with the following shape:

```js
{
  // GeoJSON object representing the feature whose vertex was moved
  feature: {..},
  // Dot-notation path to the moved vertex
  vertex: "1.3" // example
}
```

### `draw.vertexdelete`

Fired when a vertex is deleted as the result of a user interaction. The following interactions will trigger this event:

-  Delete the vertex of a selected feature in `direct_select` mode, which can be done by hitting the Backspace or Delete keys or clicking the Trash button.

Note that the same interaction will also trigger a `draw.update` event.

The event data is an object with the following shape:

```js
{
  // GeoJSON object representing the feature whose vertex was deleted
  feature: {..},
  // Dot-notation path to the deleted vertex
  vertex: "1.3" // example
}
```

**Comment by mcwhittemore** [comment]
> On the Studio side, we could do a diff to determine whether a vertex was moved, removed, added, or deleted.

Are we talking about `vertex changed` events here because we don't trust the `feature changed` events? Why do we care if one vertex was moved vs the full feature?

What use case do we have that makes us what to know which vertex (position) is selected?

> opts needs a rename

The goal of opts is selection. So maybe we should rename `opts` to `select`?

**Comment by mcwhittemore** [comment]
> Why do we care if one vertex was moved vs the full feature?

Ah, we care about these because we don't want to parse the change when trying to create annotations for what has happened.

Should draw emit these annotations? A bunch of disparate `change` events seems like the wrong move here.

**Comment by davidtheclark** [comment]
I updated the docs in the first comment to reflect what I'm planning after our conversations today. Please have another look.

I think the changes were basically these:

- Add `type` properties to `draw.selectionchange` and `draw.update`.
- Change `opts` to `features` in the event data of `draw.modechange`.
- Add `draw.vertexselect` to the list.

**Comment by mcwhittemore** [comment]
@tmcw - if we have a `draw.set` method do we need the `draw.vertexselect` event? I'd prefer to not add this if we don't need it. If we do need this, we should use `draw.positionselect` and drop `vertex` from our lingo.

`draw.create` and `draw.delete` still seem like a subclass of `draw.update`.

Couldn't `create` just be

```
{
  // Array of GeoJSON objects representing the features that were updated
  features: [{..}, {..}, ..],
  type: 'create'
}
```

And then `delete` would be

```
{
  // Array of GeoJSON objects representing the features that were updated
  features: [{..}, {..}, ..],
  type: 'delete'
}
```

Or is there a value in breaking these up into their own events that I'm missing?

**Comment by davidtheclark** [comment]
> draw.create and draw.delete still seem like a subclass of draw.update.

I think that's a pretty establish distinction (e.g. CRUD). And I can envision use-cases of wanting to do things on creation and deletion that you don't do on other updates. Enough divergence that they justify different events.

What do we lose by having different events?

**Comment by mcwhittemore** [comment]
Ya, ok. I was thinking we'd need to have three code paths that kind of do the same thing but thinking about it a bit more I don't think I'm correct. Three events is good to me.

**Comment by davidtheclark** [comment]
We will see how it pans out when we try to implement

**Comment by davidtheclark** [comment]
> if we have a draw.set method do we need the draw.vertexselect event? I'd prefer to not add this if we don't need it.

I am just not going to build in `draw.vertexselected` yet, until there's agreement on its need.

**Comment by davidtheclark** [comment]
I'm also going to delete the `opts` property from the `modechange` event data until I understand its use-case.

**Comment by davidtheclark** [comment]
Done in #407
