### ISSUE TITLE
There should be a way to give Draw a feature collection and have it do a patch update of its internal state to match

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#402]
Currently the easiest way to know Draw's internal features match some external values is to do `Draw.deleteAll()` followed by `Draw.add({})`. While this is good for knowing that Draw has the right features, its bad for performance. To fix this we should add a `Draw.set` function that takes a feature collection and performs a batch update on Draw so that only the features changed, added or deleted are rendered.

A few quick questions that come to mind.

- Should this fire `draw.modified` and `draw.deleted` events?
- Per #397, should this fire the new `draw.selectionchange` event if selected features were deleted?
- If a Position is added or removed from a feature, and that set of positions has a selected vertex, what should we do? Doing nothing will move the active vertex (if the position was added before the vertex) and could make the active vertex undefined if the last vertex was selected.

/cc @tmcw @ghoshkaj @davidtheclark

**Comment by davidtheclark** [comment]
Closed by #409.
