### ISSUE TITLE
Box select can't select more than 1000 features?

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#403]
Currently simple select's box select implementation will only run if the box covers less than 1000 features. https://github.com/mapbox/mapbox-gl-draw/blob/cf67277f18b64dd7f3462d5344bca48f4d3b35c5/src/modes/simple_select.js#L32

This seems weird to me. I'm guessing its done for performance fears, but I don't think a user who wants to select 1000 features is going to be too happy about it and I doubt a user who doesn't want to select 1000 features is going to understand what has happened. This will just look like a bug.

@samanpwbb was there another reason for this?

**Comment by samanpwbb** [comment]
No reason besides performance. We can take off the limit.
