### ISSUE TITLE
Should draw use immutable?

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#408]
I've had this thought a few times. The man question is what comparisons would this speed up and what set operations would this slow down. Is the trade off worth it?

**Comment by davidtheclark** [comment]
Where is a place in the code where there is diffing or other comparisons that you thought might be sped up with Immutable?

**Comment by mcwhittemore** [comment]
@davidtheclark one place we just blindly update is in the render pipeline. In `store.sources.cold` and `store.sources.hot` were immutable objects we could call `map.setData` only when the sources have really changed.

I'm also running into this in `Draw.add()`, though I doubt that is a good reason to change.

**Comment by mcwhittemore** [comment]
Closing this. Bad idea.
