### ISSUE TITLE
Standardize code style

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#412]
I think it's probably a worthwhile exercise to refactor the library so that it all follows, as much as reasonable, a more consistent code style (e.g. using `var`/`let`/`const`, using default params, using arrow functions, etc.). Seems like a few fairly dissimilar code styles have accumulated over time.

Though this is of course not a vital fix, I think it will make the library a little easier to read and build on over time.

**Comment by mcwhittemore** [comment]
We haven't talked much about what code style to pick. I say we go full ES2015. There are a few places where this might be hard. My only real concern is that `api.js` doesn't expose private properties.
