### ISSUE TITLE
Normalize and test return values for API functions

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#413]
Right now I'm not confident that all the API functions have deliberate return values. We should check, normalize, test, and document those.

**Comment by davidtheclark** [comment]
#386 documented the inconsistency with `Draw.deleteAll()`.

**Comment by davidtheclark** [comment]
@mcwhittemore Do you have a preference for the return values that we should just make consistent? Right now `add` and `set` return feature IDs, but other non-get functions return `undefined`. Seems if we wanted to make the API's return values 100% consistent we should try to either make all non-get functions return the draw instance for chaining, or make all the non-get functions return the IDs of affected features (though this would be uncertain with `trash` and `changeMode`). What if we just made `add` and `set` return the Draw instance?

**Comment by mcwhittemore** [comment]
Feature ids aren't required in GeoJSON so providing them back seems like a good idea. If we don't do this, we should require users to create their own ids. This is a much harder thing to check for though.

All the functions that return `undefined` should return Draw.

**Comment by davidtheclark** [comment]
Sounds good. Thanks for clarifying.

**Comment by davidtheclark** [comment]
This has been done for all existing API functions.
