### ISSUE TITLE
0.11.0+ changelog

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#421]
I published the recent changes to Draw as 0.11.0 but did not update npm to point to this version on a simple install `npm install mapbox-gl-draw`.

This can be seen via `npm dist-tags ls`
![image](https://cloud.githubusercontent.com/assets/1551510/16419958/8d4b8118-3d1d-11e6-8ea4-a180b896e4fb.png)

I'd like to keep 0.11.x under the next tag until we've tested this branch a bunch internally and are sure its stable.

To publish changes to 0.11.x without making it latest, run `npm publish --tag=next`. If this gets out of sync, don't worry, we can reset `latest` rather easily.

/cc @davidtheclark  @samanpwbb 

## Adds

- Draw.set()
- Draw.getMode()
- `draw.selectionchange`
- `draw.update`
- `draw.render`
- `draw.create`
- `static` mode which is accessible via `Draw.changeMode('static')`.

## Renames

- `draw.deleted` to `draw.delete`

## Drops

- `draw.modified`
- `draw.changed`
- `draw.simple_select.selected.start`
- `draw.simple_select.selected.end`

## Changes

- Draw.add to always return an array
- Draw.add will now change a features type on update if required
- Draw.delete accepts a single id or an array of ids.

**Comment by mcwhittemore** [comment]
Also, lets use this issue to track what is changing between 0.10.x and 0.11.x so we can write a decent changelog when the time comes.

**Comment by davidtheclark** [comment]
Sounds good.

**Comment by mcwhittemore** [comment]
The action item for this issue is to create a change log with an upgrade from 0.10.x to the 0.11.x branch.

**Comment by mcwhittemore** [comment]
We've moved npm to 0.11.x now. This issue captures the major changes to help people make the migration.
