### ISSUE TITLE
Add `getSelected()` function that returns GeoJSON

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#423]
As we're trying to fine tune the API for v1, I was wondering about this.

Why not return GeoJSON of the selected features? Then `get` and `getSelected` would return equivalent data.

**Comment by mcwhittemore** [comment]
`getSelected` serves the case where you don't have to request your own application for the feature references while `getSelectedIds` serves the case where you need to get your applications representation of the selected features. I'd say we should have them both.

**Comment by davidtheclark** [comment]
Sure. I'll change the issue name to adding the new one.
