### ISSUE TITLE
Support GeometryCollection

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#425]
We should be able to do this without too much work.

It should work much like multi_feature except that the features should be built by looping over geometries rather than coordinates.

**Comment by mcwhittemore** [comment]
I've been going back and forth about supporting these. I think for now I'm going to say we don't support GeometryCollection as most of the use cases I've seen with GeometryCollections could be done with FeatureCollections and the fact that GeometryCollections be nested makes this harder than I think it's worth.

My future self might disagree with this.

**Comment by BAByrne** [comment]
It would be nice to have a `FeatureCollection` of `Features` with different `properties` contain a collection of `geometries`. The ability to assign different properties to each GeometryCollection makes this part of the spec valuable. I may be overlooking a better way, though.
