### ISSUE TITLE
Box selecting starts when you shift+double-click to zoom out, does not stop

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#440]
If you shift+double-click to zoom out, then click somewhere else on the map, you'll see that box select has started with the shift+double-click and now you have to finish it.

**Comment by mcwhittemore** [comment]
It looks like anytime you use shift in simple_select your next interaction is box select.

I'm seeing this right now when I select two features (shift down) and than drag the map (shift up)

**Comment by davidtheclark** [comment]
Closed by #447.
