### ISSUE TITLE
make it easier to finish polygons and lines

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#448]
Right now double click on first/last point or return finish polygons. Fundamentally this is solid. There is a problem. The hit area for first/last point are tiny. I see two improvements:

While drawing, create circle features at each node and use them to give first/last point bigger hit area.

While hovering over first/last feature, change the cursor to something that communicates: "finish drawing".

**Comment by mcwhittemore** [comment]
@samanpwbb I'll add an starting pos marker and have the `pointer` cursor show up when you hover over it for polygons.
