### ISSUE TITLE
Not working on OS X 10.11

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-draw#451]
Gl-draw is broken for me at the moment on OS X 10.11(.5) for all tested browsers (Safari, Firefox and Chrome). Though maybe the issue has nothing to do with the OS X, but is rather a shader issue. 

message:"WARNING: 0:10: 'mapbox' : unrecognized pragma 
WARNING: 0:14: 'mapbox' : unrecognized pragma 
ERROR: 0:16: 'color' : undeclared identifier 
ERROR: 0:16: 'assign' :  cannot convert from 'lowp float' to 'FragColor mediump 4-component vector of float'
"

What I did:
git clone git@github.com:mapbox/mapbox-gl-draw.git
npm install
npm start & open http://localhost:9967/debug/?access_token=<apikey_from_gl-js-examples>

**Comment by mcwhittemore** [comment]
@benstadin thanks for filing this. Can you also provide your version of node?

As this complaining about shader's I'm guessing its a problem with mapbox-gl-js. Have you have you tried to build that project as well?

**Comment by mcwhittemore** [comment]
@drewbo is this what you were seeing as well?

**Comment by benstadin** [comment]
Hi @mcwhittemore 

node --version
v4.4.4

I haven't tried building a recent version of mapbox-gl-js itself. I was just using what is packaged with gl-draw.

**Comment by drewbo** [comment]
Yup, I think this was the same thing I saw. Ended up just including the api endpoint version of `mapbox-gl-js` in script tags instead of the local copy (for `debug/index.html`)

**Comment by mcwhittemore** [comment]
@benstadin Looking into this a bit more, my guess is that your shader and mapbox-gl-js dependencies are out of sync. Either way, this is an mapbox-gl-js issue so I'm going to close this issue.
