### ISSUE TITLE
East-west pan can take you to otherworldly longitudes you can't create features at

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#458]
If you pan the map east-west, you can pass the +/-180 bounds of longitude _indefinitely_. The trouble is that once you're past +/-270, you can't actually create a feature without causing an error.

It seems weird to me that mapbox-gl-js would allow you to pan to longitude 4000 but then not understand when we try to create a point there ... So I'm not sure what the right way to fix this is — to patch things up on our end, or to look upstream.

**Comment by mcwhittemore** [comment]
@davidtheclark what you have in #457 is great for simple_select.

We also need to solve this problem for direct_select.

**Comment by mcwhittemore** [comment]
Solved. Merged.

**Comment by davidtheclark** [comment]
@mcwhittemore I don't think this is solved. At least, my PRs didn't solve this. With the recent PRs we can now drag a feature around and around and around the globe. But if you pan around the globe a couple of times and try to *create* a feature, you will hit an error.

**Comment by mcwhittemore** [comment]
oh, wow. That is kind of bad.

**Comment by davidtheclark** [comment]
I've poked around in this problem a little and I'm not sure what to do. There seem to be some inescapable problems.

I think that mapbox-gl-js won't understand longitudes exceeding +-270, so it's not possible for us to render lines or polygons that try to stretch around the globe.

One approach I tried was to always transform every coordinate added to a feature so that it fell within this range. But, because of the limitation above, for continuous shapes that can mess with what you'd expect to happen as you draw, as they may end up wrapping around the globe the wrong way.

We may want to use gl-js's `map.setMaxBounds` and restrict the map to -270/270. That would eliminate these problems. It would also block a few edge-case features somebody might want to draw — but I don't know of any solution that doesn't require trade-off.

Any thoughts?

**Comment by mcwhittemore** [comment]
I think I'm going to need to play with this before I have any ideas.

**Comment by samanpwbb** [comment]
May be over-complicating things, but here are some diagrams that might help us think about this:
![wrapping](https://cloud.githubusercontent.com/assets/108094/17194399/cf35d1cc-5425-11e6-802f-f3ea358eac06.png)

**Comment by davidtheclark** [comment]
I think it is really helpful to visualize. Thanks.

- Halfway in the zones outside +-180 should be +-270, right? Then +- 360 on the edges?
- We'll need to account for lines/polygons crossing multiple zones, e.g. `[[0, -30], [540, 30]]`.

If you or @mcwhittemore are interested, I pushed the branch `otherworldly`, where I was experimenting with constraining longitude of all positions as they're created. Feel free to tinker with it.

**Comment by mcwhittemore** [comment]
I don't think we need to support shapes that expand greater than 720 degrees. If a user wants a line that wraps the world multiple times, they could draw a multiline (which we should support). 

I could be 100% wrong on this, but I think starting to limit drawing at -360 to 360 should be ok.

**Comment by davidtheclark** [comment]
> starting to limit drawing at -360 to 360

It's worth noting that I think GL JS won't yet render outside +-270, and I ran into problems with backend tools when coordinates were outside +-180. So even if we pull off recalculations that make sense in Draw, it might not be all that's necessary to solve the problem. We still might need Unearthly Longitudes Quest.

**Comment by mcwhittemore** [comment]
> Unearthly Longitudes Quest

Yea... I'm currently looking at geojson-vt (which is where these problems are in mapbox-gl-js) and seeing what I can do to fix this problem there rather than doing what we mentioned above.

I've been able to fix the problem you documented in https://github.com/mapbox/mapbox-gl-js/issues/2912. Now I'm working on plotting points from a world far far away

**Comment by mcwhittemore** [comment]
After my geojson-vt PR gets merged we should have good support from -540 to 540 in mapbox-gl-js (if that was the only issue).

With this in mind, I think what we should do for draw is not let the user drag the map past +/-540.

Thoughts?

**Comment by davidtheclark** [comment]
I'm happy to defer to people more experienced with cartographer's needs. Pinging @tmcw, who the other day expressed some dismay at the idea of restricting panning.

**Comment by andrewharvey** [comment]
@davidtheclark is this still present post https://github.com/mapbox/mapbox-gl-js/pull/4451 ?

**Comment by mcwhittemore** [comment]
@andrewharvey - you can still pan into work -1 and 1 right?

**Comment by andrewharvey** [comment]
when on the edge of world 0, you can still see world -1 and 1, and on maps which have a very large width but very small height you might still see many worlds, but for most maps you can't get to world <-1 or >1.

I tried to replicate this issue with https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/ and can't seem to, so I'm guessing it's only going to show up in the small height large width kind of maps where many worlds are visible.

**Comment by mcwhittemore** [comment]
My guess is that this is still possible if you have a wide enough screen to get to worlds -2 or 2. But with the change in mabpox-gl-js and the fix in earcut I think this is as solved as we're going to get to without adding odd and hard to understand limitations on drawing.

Thanks for bringing this up @andrewharvey.
