### ISSUE TITLE
API functions are not emitting events

### ISSUE THREAD

**Issue by kiRach** [mapbox/mapbox-gl-draw#460]
Hi guys, I'm not sure if it's an actual issue for you, but just wanted to ask you: what is the point of not emitting events when using API methods? (changes are in this commit: https://github.com/mapbox/mapbox-gl-draw/commit/2de14b4b8638d04c05826af8f51495ca00726ae8#diff-e1d62d8c4965edf0e532dfa19da0891f)

For example now it's not possible to catch the moment when all features are deleted from draw if I use `deleteAll` method. I think it's a bit confusing, because I expect event is triggered no matter how the feature was actually deleted: by user or calling any of the API method. I just want to know that it was deleted and handle this situation in my code. I think using `{silent: true}` option should be optional and it should be options for the actual API methods, so when I call `draw.deleteAll` for example, I can specify `{silent: true}`. But it shouldn't be by default. What do you think?

**Comment by mcwhittemore** [comment]
@kiRach - events causing circular data flow is the main reason we dropped this support with that commit. I think mapbox-gl-js solves this problem by exposing an `originalEvent` attribute when the event comes from a mouse/keyboard interactive and not including the `originalEvent` when an API method is what triggers the event. I'm open to this option as it connects us closer to mapbox-gl-js api standards.

**Comment by davidtheclark** [comment]
@mcwhittemore Seems like a worthy experiment before v1.

**Comment by mcwhittemore** [comment]
This missed v1's boat. Maybe there will be a v2, but until there is more effort on this project, I'm going to close this.
