### ISSUE TITLE
Support to draw circle

### ISSUE THREAD

**Issue by aravind741** [mapbox/mapbox-gl-draw#468]
Can I expect a future support for drawing a circle from you guyz??? I have done the same by using turf to calculate the distance between two points(radius) and add a circle layer converting the distance to pixels.

Ref : http://stackoverflow.com/questions/37599561/drawing-a-circle-with-the-radius-in-miles-meters-with-mapbox-gl-js/37601549

**Comment by mcwhittemore** [comment]
@aravind741 Draw is a GeoJSON drawing tool. As GeoJSON does not have support for circles we are not planning on adding them to the core set of drawing tools.

 That said, I do hope to see movement on https://github.com/mapbox/mapbox-gl-draw/issues/289 soon which will let 3rd parties create custom modes so one could create a `circle_mode` and publish it so others can use it if they please.

**Comment by bwyss** [comment]
FYI: https://bl.ocks.org/enjalot/0912e1962ed512093895
