### ISSUE TITLE
Unable to style finished features

### ISSUE THREAD

**Issue by timiyay** [mapbox/mapbox-gl-draw#472]
I'm using `mapbox-gl-draw` for a basic use case: 

1. users can draw a line to for measure between 2 points on the map
2. user clicks a `start` button to activate drawing mode
3. user draws their line(s)
4. during drawing, the lines are styled black
5. user double-clicks to finish their drawing
6. the feature switches styles, to green lines
7. the user can no longer edit the line

We are currently on v0.4.0 of this library, and are attempting to upgrade to the latest, but we're having trouble figuring out the new flow.

I'm able to get steps 1-5 working, but steps 6 and 7 are eluding me.

I'm unable to figure which mode I should be switching to, to achieve step 7. I'm trying to switch to `static` but, depending on my approach, it fails in a few ways:

1. if I'm listening for `draw.create` or `draw.modechange` events, and then call `changeMode('static')`, it causes an infinite loop. The event listener calls `changeMode('static')` which triggers the event listener which...

2. the line feature disappears (no styling).

What is the process for implementing this basic use case?

**Comment by timiyay** [comment]
I'm able to achieve most of what I want, by copying the style examples from `test/fixtures/style_with_sources.json`.

In my case, I'm able to achieve my styling goals (steps 4 and 6 above) by adding the following styles:

```js
        // Lines: inactive (already drawn, not static)
        {
            "id": "gl-draw-line-active.cold",
            "type": "line",
            "filter": [
              "all",
              ["==", "$type", "LineString"],
              ["==", "active", "true"]
            ],
            "layout": {
              "line-cap": "round",
              "line-join": "round"
            },
            "paint": {
              "line-color": "#34C981",
              "line-width": 3
            },
            "interactive": true,
            "source": "mapbox-gl-draw-cold"
        },

        // Lines: active (being drawn)
        {
            "id": "gl-draw-line-active.hot",
            "type": "line",
            "filter": [
              "all",
              ["==", "$type", "LineString"],
              ["==", "active", "true"]
            ],
            "layout": {
              "line-cap": "round",
              "line-join": "round"
            },
            "paint": {
              "line-color": "#000",
              "line-dasharray": [0.2, 2],
              "line-width": 2
            },
            "interactive": true,
            "source": "mapbox-gl-draw-hot"
        }
```

If I remove `id`, nothing is rendered. If I remove `source`, then my custom styles are rendered _in addition to_ the default styles.

I'm finding this very confusing - the API docs clearly state:

> The GL Style Spec requires each layer to have a source. DO NOT PROVIDE THIS for styling draw.

...but I have to supply the source or my features aren't styled.

The doc also says:

> The GL Style Spec also requires an id. Draw will provide this for you.

...but it fails if I don't provide the `id` myself.

My current styles give me most of what I want, except that the user is able to grab the features and drag them around the map, which I don't want. I'm assuming that changing the mode to `static` is the answer, but then I hit the missing styling / infinite event listener issues described above.

I'm assuming user error here, but I'd love to be guided along this very confusing workflow. I'd be happy to contribute a docs PR once I get my head around it.

**Comment by mcwhittemore** [comment]
@timiyay listing to `draw.modechange` is the right idea. As part of the event, a `mode` attribute is emitted. This will tell you which mode you are moving to. Use this to not continue to escape the loop.

Using sources and id's in your style is definitely not good. Above, both of your styles are filtering on the same thing.

```
"filter": [
  "all",
  ["==", "$type", "LineString"],
  ["==", "active", "true"]
]
```

This means that the style will only be applied to active LineStrings. In static mode, nothing is active. Active tells you if the feature is currently selected by the user. If you make your `cold` style select LineStrings where active is false you should be good. You can also use the mode attribute as part of the filter.

**Comment by timiyay** [comment]
@mcwhittemore Thanks for the extra details.

Static mode sounds like what I'm after, I'm trying out a circuit breaker where `if (e.mode !== 'simple_select')`, then I ignore. Otherwise, I bump the mode to `static`.

This relies on the assumption that completing a drawn feature will always transition to `simple_select` mode. Is this a safe assumption?

**Comment by timiyay** [comment]
@mcwhittemore I accept that sources and ids should not be declared. However, if I don't declare them, my styles aren't applied.

Is there a reference for the style filters that are required?

For example, what's a minimal example for these 2 styles?

1. red dashed lines, when drawing a line in `draw_line_string` mode
2. solid black lines, when a line is in `static` mode

**Comment by mcwhittemore** [comment]
> This relies on the assumption that completing a drawn feature will always transition to simple_select mode. Is this a safe assumption?

Yep

> The last-declared style takes effect, the preceding ones don't

Ah, the docs around ids are wrong. You must supply an id but the id will have `.hot` added to it for the hot source and `.cold` added to it for the cold source.

**Comment by timiyay** [comment]
@mcwhittemore OK thanks for your explanations and patience.

I've opened a docs update PR here (https://github.com/mapbox/mapbox-gl-draw/pull/476), with intent of clarifying these issues for future developers (aka future me).

Happy to change as needed.
