### ISSUE TITLE
Split up interaction_events.test.js into smaller independent units`

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#473]
Right now any modifications to `interaction_events.test.js` can be a huge pain, because most of the tests in there rely on continuous shared state — so if you modify something towards the top, you'll need to modify stuff below. This was a mistake I made.

Those tests should be split up into smaller, independent units that can be modified without requiring modification of other unrelated tests.

**Comment by mcwhittemore** [comment]
I ran into this problem I bit more today.

**Comment by mcwhittemore** [comment]
Closing this for now. When we do another test refactor I'm sure we'll hit this.
