### ISSUE TITLE
Incompatible with IE11

### ISSUE THREAD

**Issue by timiyay** [mapbox/mapbox-gl-draw#479]
I'm attempting to upgrade to `mapbox-gl-js` 0.21.0 and `mapbox-gl-draw` 0.11.13.

My draw tools crash out on IE11. When I change to a drawing mode, the cursor doesn't change into the crosshairs. Then, when I click on the map to start drawing, nothing renders.

When I look into the console, I see a crash:

```
TypeError: Argument not optional

vendor/npm/mapbox-gl-draw/dist/mapbox-gl-draw.js:3 · exports
vendor/npm/mapbox-gl-draw/dist/mapbox-gl-draw.js:2 · t.exports
vendor/npm/mapbox-gl-draw/dist/mapbox-gl-draw.js:2 · r.mouseup
js/util/evented.js:97:12 · Evented.fire
js/ui/bind_handlers.js:126:8 · fireMouseEvent
```

__UPDATE__:

Summarised from comments below:

`mapbox-gl-draw` is calling `DOMTokenList.remove()` and `DOMTokenList.add()` at https://github.com/mapbox/mapbox-gl-draw/blob/master/src/ui.js#L42.

In cases where no arguments are supplied to these methods, IE11 blows up. Casual testing indicates this situation is encountered on every click event, rendering `mapbox-gl-draw` incompatible with IE11.

PR: https://github.com/mapbox/mapbox-gl-draw/pull/481

**Comment by timiyay** [comment]
FWIW I'm aware this issue is light on detail at the moment. I'm aiming to collect more data on Windows machines when available, so I can share here. I'm also planning to make a Codepen repro as well.

**Comment by timiyay** [comment]
Here is a Codepen to repro the issue in IE11: http://codepen.io/timiyay/pen/AXGRkx

I had to paste the `mapbox-gl-draw` JS in, due to lack of CDN. For similar reasons, the CSS and image assets aren't included in the repro.

Nonetheless, you can repro the issue by:

* opening the IE11 Dev Tools
* clicking the top-left white button to enable drawing a LineString
* attempt to draw a LineString
* observe that nothing happens, and the console error output

Here's a screen grab:
![draw_crash](https://cloud.githubusercontent.com/assets/1470250/17954072/bf536038-6abb-11e6-9e7b-e8f2a192dfa7.png)

Combined with my original stack draw, it appears that `mapbox-gl-draw` isn't receiving an expected argument from an IE11 click event.

**Comment by mcwhittemore** [comment]
Closed by #481

**Comment by timiyay** [comment]
thanks for the quick reponse @mcwhittemore and @samanpwbb. Appreciate it. Excited to try out the new versions.

**Comment by mcwhittemore** [comment]
Thanks for tracking this down 😄.

**Comment by mcwhittemore** [comment]
@timiyay - FYI, @mollymerp got Draw onto our CDN https://github.com/mapbox/mapbox-gl-js/pull/3070
