### ISSUE TITLE
rewrite tests

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/mapbox-gl-draw#48]
I butchered them in https://github.com/mapbox/gl-draw/pull/40

**Comment by kelvinabrokwa** [comment]
- [x] API
- [x] draw
- [x] draw store
- [x] edit store
- [ ] util
- [ ] geometry
- [x] point
- [ ] line
- [ ] polygon
- [ ] square

Punting on:
- testing that the appropriate methods are listening to appropriate events at appropriate times

**Comment by mcwhittemore** [comment]
This issue is stale and has been replaced by #155
