### ISSUE TITLE
Docs Page

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#489]
Draw has gotten to the point where a docs page would be helpful.

As of right now, I think the page should cover three concepts.
1. Setup
2. Controls
3. Events
4. Styling

Events and Styling should be grouped with demos so users can see what the docs describe.

@timiyay, you brought up needed better docs for styling in #476. What thoughts do you have for a full-fledged docs page?

**Comment by davidtheclark** [comment]
I think it probably also needs a "Usage" section, covering how to draw things when the control is active.

**Comment by mcwhittemore** [comment]
hmmm... while I agree that drawing still needs a bunch of work, I'm not sure we can solve this problem via docs as only developers implementing Draw will see them...

**Comment by davidtheclark** [comment]
Maybe I wasn't clear enough ... developers implementing Draw, like their users, will need to know how to interact with the map. How to draw a line? How to close a polygon? What happens when I push Escape? What does the "Trash" button do? Stuff like that.

**Comment by mcwhittemore** [comment]
ah, controls! I'll add them to the things that need to be covered.

**Comment by mcwhittemore** [comment]
Per how to draw, I wonder if we could ship a walkthrough UI for Draw, that walked users through how to do things or if this is something that different users would want to customize so much that having the UI as part of the project would just take up space.

**Comment by timiyay** [comment]
@mcwhittemore I'm generally in favour of improving the docs. Do you have an example of what format you're thinking?

For example, are you looking at HTML-based docs, like the MapboxGL docs webpages (https://www.mapbox.com/mapbox-gl-js/examples/), or the Mapbox API docs (https://www.mapbox.com/api-documentation/)?

Or are you thinking a GH wiki?

Or simply adding a `/docs` directory, with separate Markdown files, to keep the `README.md` size reasonable?

**Comment by mcwhittemore** [comment]
@timiyay I'm thinking HTML based docs. My gut says like the mapbox-gl-js docs, but I'm open to other options.

**Comment by timiyay** [comment]
Sounds good to me. The mapbox-gl-js docs are top-shelf.

I'm happy to contribute my linestring / polygon examples into that structure, developing a working example that can be viewed in-browser.
