### ISSUE TITLE
How to draw with draw walkthrough ui?

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#490]
Per how to draw (ref #489), I wonder if we could ship a walkthrough UI for Draw, that walked users through how to do things or if this is something that different users would want to customize so much that having the UI as part of the project would just take up space.

**Comment by davidtheclark** [comment]
Even if the buttons are dropped I think that there'd still be a need for instructions about the map interactions in each mode.

**Comment by mcwhittemore** [comment]
> Even if the buttons are dropped

yea... but is this something you'd have Draw do for you? Would we use this in Mapbox Studio? I think we'd design a walkthrough that fits with the design of our app. Users who keep the default controls might want this, but I'm not sure.

**Comment by joedjc** [comment]
I think this would be useful if it just covered the mechanics of drawing each shape - i.e. if there was a small animation that appeared when a user selects a draw mode. 

For example, when polygon mode is selected/started, an animation (in the top right of the screen or something) shows how to draw, move, edit and complete the shape itself (maybe this could change depending on where the user is in the 'drawing process' - start/edit/complete etc.). 

Everything else (like how drawing mode is started) is likely to be specific to each project as is pretty straightforward anyway, but the drawing process is usually the same and a bit of prompting/guidance would help.

**Comment by mcwhittemore** [comment]
I think this is something that needs to be implemented by applications. Too much of how this is explained will depend on context.
