### ISSUE TITLE
Event firing broke in v0.11.18

### ISSUE THREAD

**Issue by contrasam** [mapbox/mapbox-gl-draw#491]
I upgraded from v0.11.15 to v0.11.18 and the draw events are not being fired (I am using 'draw.create' and 'draw.update' in my code), the version of mapbox-gl being used in v0.22, even tried it with v0.23.

Is there any breaking changes in the version I need to know about?

**Comment by timiyay** [comment]
**mapbox-gl-js:** 0.22.1
**mapbox-gl-draw:** 0.11.19

I'm having a similar issue in my code, where my draw events are not being fired, and my `draw.modechange` listener is not being called.

In my case, I've traced the issue to a recent change I made. I switched to initialising my `Draw` object in a `map.on('load')` callback, where previously is was using `map.on('style.load')`.

I'm currently digging through the `mapbox-gl-js` source code, to try and understand the namespaced event system. Recent Github issue traffice for `mapbox-gl-js` suggests that `style.load` has been deprecated; however, `mapbox-gl-draw` won't initialise without it.

**Comment by mcwhittemore** [comment]
@contrasam are you using `map.on('style.load')` or `map.on('load')`.

I'm looking into what could change in Draw to let it work with `map.on('load')`.

**Comment by contrasam** [comment]
@mcwhittemore I am using draw under map.on('load')

**Comment by contrasam** [comment]
Sorry! my bad, I am not doing it on map.on('load'), I was adding draw just after map initialization ;-), after adding map.addControl(Draw) under map.on('load'), the event firing works on v0.11.18.

**Comment by mcwhittemore** [comment]
@contrasam - no problem. I just double checked and the `debug.html` is using `map.on('load')` and is functioning.

@timiyay - I'm not sure why this wasn't working for you but you should try not to use `style.load`.
