### ISSUE TITLE
How to update styles on current Draw instance?

### ISSUE THREAD

**Issue by sanjin-saric** [mapbox/mapbox-gl-draw#497]
I am currently styling separate features filtering them by id. And that works ok, but the bad thing is that I have to know the ids in advance and create styles for each one. That is also ok, I can work with that. 

But the problem arises when I add a new feature (say polygon) and I want it to have custom style. Currently what I am doing is hacky and isn't working well which is manually creating hot and cold layers with set respective sources and adding them to map. 

Is there a way to add a new style to current Draw instance? (Which in turn should add new layers to map).

**Comment by mcwhittemore** [comment]
@sanjin-saric - Do these different features look different or are you applying the same style to different IDs with no change? If the styles are the same then you should consider looking styling draw based on feature type and mode. There are some docs [on this here](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#styling-draw). There are also some examples [here](https://github.com/mapbox/mapbox-gl-draw/blob/master/EXAMPLES.md) that should help you.

**Comment by sanjin-saric** [comment]
@mcwhittemore Yes I have different features with different ids, and I am able to style them by applying the "id" filter in styles. However, this is only possible when creating an instance of Draw. 

My goal here is to style different features by their ids. 

Consider adding a new feature, via lets say draw-polygon. How do I style that feature differently, when I am only able to style them when creating a Draw instance?

Currently, when I create a new feature, I retrieve its ID then create two new styles (hot and cold) with filters set to apply only to that feature ( by its ID and then I add them as layers. I also push the styles to Draw.options.styles. This works well, but I find this very hacky. There should be an easier way to style a feature when I add after I instanced Draw.

**Comment by mcwhittemore** [comment]
@sanjin-saric - sorry. I don't think my question was very clear. Other than the id, what is different in the styles you are applying to the features? Can you post an example?

**Comment by sanjin-saric** [comment]
@mcwhittemore oh. Well depends. I am developing a feature that will enable user to style its feature upon creating it. I am finishing polygon feature, and user will be able to style fill color, opacity and stroke. 
```
 const polygonStrokeActive = {
            id: `polygon_stroke_${polygon.id}_active`,
            type: 'line',
            filter: ['all', ['==', '$type', 'Polygon'], ['==', 'id', `${polygon.id}`], ['!=', 'mode', 'static'], ['==', 'active', 'false']],
            layout: {
                'line-cap': 'round',
                'line-join': 'round',
            },
            paint: {
                'line-color': polygon.strokeColor,
                'line-width': StrokeWeight[polygon.strokeWeight.toUpperCase()],
            },
            interactive: true,
        };

        const polygonStrokeActiveSelected = {
            id: `polygon_stroke_${polygon.id}_active_selected`,
            type: 'line',
            filter: ['all', ['==', '$type', 'Polygon'], ['==', 'id', `${polygon.id}`], ['!=', 'mode', 'static'], ['==', 'active', 'true']],
            layout: {
                'line-cap': 'round',
                'line-join': 'round',
            },
            paint: {
                'line-color': polygon.strokeColor,
                'line-dasharray': [0.2, 2],
                'line-width': StrokeWeight[polygon.strokeWeight.toUpperCase()],
            },
            interactive: true,
};
```
Here is a snippet of dynamic style I create. Notice the placeholder for ID. I get that from newly created feature, and then do the procedure I wrote in my last post.

**Comment by mcwhittemore** [comment]
hmmm... I didn't realize that `feature.id` was exposed on the properties...

I think the best way to let a user style different features would be to use the [data-driven styling functions](https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/) from mapbox-gl-js. This way you could have a few layers and avoid the pain (ie: performance loss) of having a lot of layers. The problem is that Draw doesn't pass through the user defined properties currently. I'm for supporting this.

I think the best way to allow user properties without worrying about overwriting Draws, would be to add a `usr:` prefix to all the properties so they didn't clash with the draw properties. We'd want this off by default to lower the amount of work done at the rendering step.

If you want to put together a PR that did this, that would be great.

**Comment by sanjin-saric** [comment]
@mcwhittemore I would be glad to do this. The example you sent is using a layer to style different dots. Can you post an example how would you after you created an instance of Draw, style a specific feature?
(Style object and function calls)
I think I understand the concept, but I want to be sure before I start coding.

**Comment by mcwhittemore** [comment]
@sanjin-saric - the example I sent is using the data from the features to style the features themselves. This means you'd set up a few layers that follow the same rules for all the features. These rules will reference properties on the features so that the result per feature is feature specific. With that done, you then can update the properties of the features and it should update the style.

Here is an info to [data-driven styling](https://www.mapbox.com/blog/data-driven-styling/) (just covering circle-color). Here is another [blog post about fill-color](https://www.mapbox.com/blog/data-driven-fill-color/). I'm not too sure how many of the properties are available for data-driven as of now. You should be able to figure that out from the mapbox-gl-js repo.

**Comment by mcwhittemore** [comment]
@sanjin-saric - The new `Draw.setFeatureProperty()` and `opts.userProperties` might help you do more advanced styling. This will be live in 0.15.0.

**Comment by benjaminhon** [comment]
@mcwhittemore Im also experiencing this issue, i am trying to style based on filtering on userProperties, but it doesn't seem to work.

I am on v0.14.0

my feature colllection
```
'type':     'FeatureCollection'
'features': staticDevices
            .map ({id, lat, lng}) ->
              'type':           'Feature'
              'geometry': 
                'type':         'Point'
                'coordinates':  [parseFloat(lng), parseFloat(lat)]
              'properties':
                'user_title':   id
                'user_type':    'static-device'
```

my style
```
styles={[
  {
    'id':     'point-stroke'
    'type':   'circle'
    'filter': ['all',
        ['==', '$type', 'Point']
        ['!=', 'user_type', 'static-device']
      ]
    'paint':
      'circle-radius':  6
      'circle-opacity': 1
      'circle-color':   '#fff'
  },
  {
    'id':     'point'
    'type':   'circle'
    'filter': ['all',
        ['==', '$type', 'Point']
        ['!=', 'user_type', 'static-device']
      ]
    'paint':
      'circle-radius':  4
      'circle-color':   '#3bb2d0'
  },
  {
    'id':     'static-devices'
    'type':   'symbol'
    'filter': ['all',
        ['==', '$type', 'Point']
        ['==', 'user_type', 'static-device']
      ]
    'layout':
      'icon-image':   'monument-15'
      'text-field':   '{user_title}'
      'text-font':    ['Open Sans Semibold', 'Arial Unicode MS Bold']
      'text-offset':  [0, 0.6]
      'text-anchor':  'top'
  }
]}
```

the filter based on ['==', 'user_type', 'static-device'] doesn't seem to catch it and it defaults to the above 2 styles.

is this only possible in 0.15.0?

thanks

**Comment by sanjin-saric** [comment]
I implemented this in my own way:

```javascript
api.updateFeatureStyle = function(feature) { //!
    const featureLayers = ctx.store.get(feature.id).layers;
    Object.keys(featureLayers).forEach(layerId => { //!
      var layer = featureLayers[layerId]; //!
      if (layer.type === 'fill') {
        if (feature.paint['fill-color'] !== undefined) { //!
          ctx.map.setPaintProperty(layerId, 'fill-color', feature.paint['fill-color']); //!
          ctx.map.setPaintProperty(layerId, 'fill-outline-color', feature.paint['fill-color']); //!
        } //!
        if (feature.paint['fill-opacity'] !== undefined) ctx.map.setPaintProperty(layerId, 'fill-opacity', feature.paint['fill-opacity']); //!
      } //!
      if (layer.type === 'line' && feature.paint) { //!
        if (feature.paint['line-color'] !== undefined) ctx.map.setPaintProperty(layerId, 'line-color', feature.paint['line-color']); //!
        if (feature.paint['line-width'] !== undefined) ctx.map.setPaintProperty(layerId, 'line-width', feature.paint['line-width']); //!
        if (feature.paint['line-opacity'] !== undefined) ctx.map.setPaintProperty(layerId, 'line-opacity', feature.paint['line-opacity']); //!
      } //!
      if (layer.type === 'circle') { //!
        if (feature.paint['circle-opacity'] !== undefined) ctx.map.setPaintProperty(layerId, 'circle-opacity', feature.paint['circle-opacity']); //!
      } //!
      if (layer.type === 'raster') { //!
        if (feature.paint['raster-opacity'] !== undefined) ctx.map.setPaintProperty(layerId, 'raster-opacity', feature.paint['raster-opacity']); //!
        if (feature.url !== undefined) { //!
          ctx.map.removeSource(layer.source); //!
          const imageSource = { //!
            type: "image", //!
            url: feature.url, //!
            coordinates: feature.coordinates, //!
          }; //!
          ctx.map.addSource(layer.source, imageSource);
          const polygonCoordinates = feature.coordinates.slice(0);
          polygonCoordinates.push(polygonCoordinates[0]);
          ctx.store.get(feature.id).setCoordinates([polygonCoordinates]);
        } //!
        if (feature.url === undefined && feature.coordinates !== undefined) {
          const polygonCoordinates = feature.coordinates.slice(0);
          polygonCoordinates.push(polygonCoordinates[0]);
          ctx.store.get(feature.id).incomingCoords([polygonCoordinates]);
        }
      } //!
      if (layer.type === 'symbol') { //!
        if (feature.paint) { //!
          if (feature.paint['text-color'] !== undefined) ctx.map.setPaintProperty(layerId, 'text-color', feature.paint['text-color']); //!
          if (feature.paint['text-opacity'] !== undefined) ctx.map.setPaintProperty(layerId, 'text-opacity', feature.paint['text-opacity']); //!
          if (feature.paint['text-halo-color'] !== undefined) ctx.map.setPaintProperty(layerId, 'text-halo-color', feature.paint['text-halo-color']); //!
          if (feature.paint['text-halo-width'] !== undefined) ctx.map.setPaintProperty(layerId, 'text-halo-width', feature.paint['text-halo-width']); //!
          if (feature.paint['text-halo-blur'] !== undefined) ctx.map.setPaintProperty(layerId, 'text-halo-blur', feature.paint['text-halo-blur']); //!
          if (feature.paint['text-translate'] !== undefined) ctx.map.setPaintProperty(layerId, 'text-translate', feature.paint['text-translate']); //!
        } //!
        if (feature.layout) { //!
          if (feature.layout['text-field'] !== undefined) ctx.map.setLayoutProperty(layerId, 'text-field', feature.layout['text-field']); //!
          if (feature.layout['text-rotate'] !== undefined) ctx.map.setLayoutProperty(layerId, 'text-rotate', feature.layout['text-rotate']); //!
          if (feature.layout['text-size'] !== undefined) ctx.map.setLayoutProperty(layerId, 'text-size', feature.layout['text-size']); //!
          if (feature.layout['text-anchor'] !== undefined) ctx.map.setLayoutProperty(layerId, 'text-anchor', feature.layout['text-anchor']); //!
          if (feature.layout['visibility'] !== undefined) ctx.map.setLayoutProperty(layerId, 'visibility', feature.layout['visibility']); //!
        } //!
      } //!
      if (feature['minzoom'] !== undefined && !isNaN(feature['minzoom'])) ctx.map.setLayerZoomRange(layerId, feature['minzoom']); //!
      if (feature['maxzoom'] !== undefined && !isNaN(feature['maxzoom'])) ctx.map.setLayerZoomRange(layerId, undefined, feature['maxzoom']); ///!
    }); //!
  }; //!
```

This is the method I use to change the color of a feature.

I modified the store as well to reflect this: 

```javascript
/**  //!
 * Assigns layer associated with the feature,  //!
 * to layers object within the feature.  //!
 * This enables styling functions to easily  //!
 * see which layers it needs to update in order  //!
 * to update the whole feature style. //!
 * @param {Object} [id] //!
 * @return {Store} this //!
 */
Store.prototype.assignFeatureLayer = function(id, layer) { //!
  const feature = this._features[id]; //!
  feature.layers[layer] = feature.ctx.map.getLayer(layer); //!
  return this;  //!
}; //!
```
Also when I add draw, I pass no styles for features. Instead i create the styles dynamically when I add a feature:

```javascript
function generateHotAndColdLayers(styles, featureId, layerBefore = 'draw_polygon_polyline_active.hot') { //!
    const hotStyles = styles.map(hs => { //!
      const hotObject = JSON.parse(JSON.stringify(hs)); //!
      hotObject.id = `${hotObject.id}.hot`; //!
      hotObject.source = 'dragonfly-draw-hot'; //!
      return hotObject; //!
    }); //!

    const coldStyles = styles.map(cs => { //!
      const coldObject = JSON.parse(JSON.stringify(cs)); //!
      coldObject.id = `${coldObject.id}.cold`; //!
      coldObject.source = 'dragonfly-draw-cold'; //!
      return coldObject; //!
    }); //!

    const combinedStyles = hotStyles.concat(coldStyles); //!
    combinedStyles.forEach(style => { //!
      const existingStyle = ctx.options.styles.find(s => s.id === style.id); //!
      if (existingStyle !== undefined) { //!
        ctx.options.styles[ctx.options.styles.indexOf(existingStyle)] = style; //!
      } else { //!
        ctx.options.styles.push(style); //!
      } //!
      if (!ctx.map.getLayer(style.id)) { //!
        ctx.map.addLayer(style, layerBefore); //!
      } //!
      if (featureId !== undefined) ctx.store.assignFeatureLayer(featureId, style.id); //!
    }, this); //!
  } //!

  api.setInitialFeatureStyle = function(feature) { //!
    switch (feature.type) { //!
    case 'Polygon': //!
    { //!
      const styles = generatePolygonStyle(feature); //!
      generateHotAndColdLayers(styles, feature.id); //!
      break; //!
    } //!
    case 'Polyline': //!
    { //!
      const styles = generatePolylineStyle(feature); //!
      generateHotAndColdLayers(styles, feature.id); //!
      break; //!
    } //!
    case 'Marker': //!
    { //!
      const styles = generateMarkerStyle(feature); //!
      generateHotAndColdLayers(styles, feature.id); //!
      if (feature.label) {
        feature.label.id = `${feature.id}_label`;
        const labelStyles = generateLabelStyle(feature.label); //!
        generateHotAndColdLayers(labelStyles, feature.label.id); //!
      }
      break; //!
    } //!
    case 'Label': //!
    { //!
      const styles = generateLabelStyle(feature); //!
      generateHotAndColdLayers(styles, feature.id); //!
      break; //!
    } //!
    } //!
  }; //!
```

**Comment by mcwhittemore** [comment]
@sanjin-saric - This is impressive, but this kind of functionality is above and beyond the scope of draw. What would you need to have this kind of functionality in a library outside of draw? I agree styling is something that could be imporved and I'd love to start pointing people to good options like this via our docs.

**Comment by mcwhittemore** [comment]
@sanjin-saric - how are you thinking about [data driven styling](https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/) when it comes to this?

Have you used the non-gl [simplestyle spec](https://github.com/mapbox/simplestyle-spec) before?

**Comment by sanjin-saric** [comment]
@mcwhittemore I understand what you are saying. One should create a feature with data containing feature style which then layer would read and render dynamically. I just started using data driven props, and I think i might be able to refactor this. I'll get back to you if I come up with something neat.

**Comment by mcwhittemore** [comment]
Cool, I'm excited to see what comes of it.

**Comment by igal1c0de4n** [comment]
2 years later... bumped into this issue while searching how to do exactly that.
Does anyone know of an official way to achieve this? 
@ssaric Is adding the code snippet above still my best bet?

**Comment by ssaric** [comment]
> 2 years later... bumped into this issue while searching how to do exactly that.
> Does anyone know of an official way to achieve this?
> @ssaric Is adding the code snippet above still my best bet?

Don't know what happened in mean time, haven't used this library in 2 years :D
