### ISSUE TITLE
Precision of coordinates

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/mapbox-gl-draw#498]
I'm trying to add back a previously exported feature but I'm running to this error: 

[Error] Error: precision of coordinates should be reduced
	add (mapbox-gl-draw.js:2:12057)

Does this mean that mapbox-gl-draw export points at a higher precision than the one it accept in input ?

**Comment by mcwhittemore** [comment]
@vincentsarago - that is possible. We've had a lot of problems with the new GeoJSON lint as it follows the improved spec. The solve this you can clean up your GeoJSON before adding it to the map.

I'm not sure what Draw should do here. Having more than 6 decimal points is pointless but I'm not sure we want to clean up all lngLat's passed into the module. I guess we are already checking for this so the effective perf change wouldn't be much.

**Comment by tmcw** [comment]
To be a little clearer, this is the only problem, though it's an annoying one :)

geojsonhint v2.0.0-beta2 makes the coordinate warning an opt-in, via https://github.com/mapbox/geojsonhint/pull/50 - I'd recommend upgrading.

**Comment by mcwhittemore** [comment]
@tmcw - Good point. I've seen this problem in a bunch of places, but it is just one problem. I'm leaning towards truncating the input to follow the GeoJSON spec. Disabling this check will be good.

**Comment by vincentsarago** [comment]
@mcwhittemore I mean I'm just trying to add back something I got from draw, so I believe there are two options: 
- draw handle 15 decimals in Output/Input
- draw cast Input geojson to 5 decimals directly so no more Input/Output differences 

I agree that having more than 6 decimals is pointless, but maybe someone at the time will need higher precision. 

Maybe we can add a general option to handle higher precision by default?

**Comment by mcwhittemore** [comment]
> The size of a GeoJSON text in bytes is a major interoperability
   consideration, and precision of coordinate values has a large impact
   on the size of texts.  A GeoJSON text containing many detailed
   Polygons can be inflated almost by a factor of two by increasing
   coordinate precision from 6 to 15 decimal places.  For geographic
   coordinates with units of degrees, 6 decimal places (a default common
   in, e.g., sprintf) amounts to about 10 centimeters, a precision well
   within that of current GPS systems.  Implementations should consider
   the cost of using a greater precision than necessary.
> -- https://tools.ietf.org/html/rfc7946#section-11.2

@vincentsarago - good point. I was thinking the spec limited the number of decimal points to 6 but it only begs implementors to consider precision.

I think this is what we want to do. If it seems wise, I'll work on a PR today.

1. Accept Positions with any number of decimal points.
1. Create Positions with <= 6 decimal points.
1. Export Positions as imported unless modified by the user.

**Comment by vincentsarago** [comment]
@mcwhittemore seems good to me! 
Thanks
