### ISSUE TITLE
Trash controls overrides all delete actions

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#499]
If the trash control is enabled that delete key press does not do its default action for other mapbox-gl-js plugins. Draw should be smart about taking over this event and only do so when there is not an input box in the bubble path of the event.

https://github.com/mapbox/mapbox-gl-geocoder/issues/57#issuecomment-247612228

**Comment by cristianstu** [comment]
Sstill having this issue with version 0.17

Any workaround?

http://plnkr.co/edit/qYFG38Qq6g6kWavqMclb?p=preview

**Comment by mcwhittemore** [comment]
I think we need to confirm that the map is the target of the event to fix this.

https://github.com/mapbox/mapbox-gl-draw/blob/master/src/events.js#L134

**Comment by cristianstu** [comment]
Looking at the source code I realize that key bindings can be disabled with the option `keyBindings: false`.

Not a solution, but that way I can use draw and geocoder together.

**Comment by mcwhittemore** [comment]
Fixed as of 471fdfa89eb26d90fbe16791f5fc56a33b9026dc.
