### ISSUE TITLE
Restrict longitude to +/- 180 for internals features

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/mapbox-gl-draw#500]
When drawing a point or any geometries over longitudes > +/- 180 should the coordinates get transformed directly between +/- 180 ? 

I believe user will expect features with longitudes between +180 and -180 when using draw.

**Comment by mcwhittemore** [comment]
@vincentsarago You cannot draw across the antimeridian if you box GeoJSON as suggested above.

Check out https://github.com/mapbox/mapbox-gl-draw/issues/458 for a more detailed discussion on this problem.

**Comment by mcwhittemore** [comment]
I should note, that for the Mapbox Studio Dataset editor we are limiting the map to +/- 180 degrees to effectively do what you've asked above. If this is something you need, I suggest doing that.

**Comment by vincentsarago** [comment]
@mcwhittemore not sure to understand, do you want to force the map object between +/-180 or do you think about normalizing the coordinates between +/- 180 ?

**Comment by vincentsarago** [comment]
ah good I understand, didn't think about the possibility! 
thanks @mcwhittemore

**Comment by mcwhittemore** [comment]
@tmcw talked about this problem in a blog post today. http://www.macwright.org/2016/09/26/the-180th-meridian.html

Might be worth thinking about enforcing the MultiFeature approach as things cross the +/- 180 line.

**Comment by mcwhittemore** [comment]
Moving this convo to #535
