### ISSUE TITLE
Impossible to add control while tiles are loading

### ISSUE THREAD

**Issue by ezheidtmann** [mapbox/mapbox-gl-draw#502]
Steps to reproduce:
1. Load mapbox-gl and gl-draw
2. `map.addControl(draw)` -- control buttons visible, drawing works
3. `draw.remove()` -- control buttons go away, as expected
4. `map.removeSource('x'); map.addSource('x', source_spec)` -- change URL of a tile source
5. While the tile is `map.addControl(draw)` -- control buttons visible, but clicking a tool does not enable the tool. Drawing never fully enables.
## 

Possible explanation: At [line 44 in setup.js](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/setup.js#L44), we register a `load` handler if `map.loaded()` is false, but the `load` event only gets fired once when the "first visually complete rendering of the map has occurred" [(api docs)](https://www.mapbox.com/mapbox-gl-js/api/#Map.event:load).

**Comment by mcwhittemore** [comment]
@ezheidtmann - thanks for pointing this out. It sounds like we need to figure out a better way to know the Draw setup process will work with the current set of mapbox-gl-js. If we can find someway to do this with getters rather than events we should be able to drop this one-time event.
