### ISSUE TITLE
Build error when using webpack 

### ISSUE THREAD

**Issue by wanyanyan** [mapbox/mapbox-gl-draw#504]
The error message:
`SyntaxError: Unexpected token punc «(», expected punc «:» [./~/mapbox-gl-draw/sr
c/lib/common_selectors.js:12,0]`
I found the file `common_selectors.js`, the code is like this:
![image](https://cloud.githubusercontent.com/assets/12003895/18613037/9831c5ae-7da2-11e6-8280-7d2ecdcb0895.png)
I don't know whether the function `isShiftMousedown(e)`  should be `isShiftMousedown:function(e){}`.

**Comment by mrblueblue** [comment]
@wanyanyan are you compiling the source with the webpack babel plugin?

`isShiftMousedown(e)` is just a shorthand of `isShiftMousedown:function(e)` in ES6.

However it does seem odd that the rest of the methods are not written using shorthand style.

It should probably be `isShiftMousedown:function(e)` for consistency.

**Comment by lukes** [comment]
+1 for this change. We've run into it too, during from within the webpack.optimize.UglifyJsPlugin step.
