### ISSUE TITLE
Point movements are very jerky

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#508]
In this GIF you can see the point jerking around as I drag it. I do not think this was a problem before, and it does not seem to be a problem currently in the Studio Dataset Editor in production. Were there recent changes that may have hurt performance?

![sep-27-2016 07-58-20](https://cloud.githubusercontent.com/assets/628431/18879219/51cdb180-8488-11e6-8cd6-f09a107ace83.gif)

**Comment by mcwhittemore** [comment]
@davidtheclark - what version of Draw and what version of mapbox-gl-js are you using?

**Comment by davidtheclark** [comment]
I pulled the latest master and ran the dev server. So this is cutting-edge Draw and mapbox-gl-js 23.

**Comment by mcwhittemore** [comment]
master has commits that aren't published. Did you say you say this in the Mapbox Studio dataset editor as well? I'm just trying to find where to start git-bisecting.

**Comment by davidtheclark** [comment]
> Did you say you say this in the Mapbox Studio dataset editor as well?

I *do not* see this in the Studio dataset editor, not in production and not in staging.

**Comment by mcwhittemore** [comment]
I'm not seeing this anymore. My guess is that it was a passing bug in render order of gl-js.
