### ISSUE TITLE
Draw plugin breaks when map style changes

### ISSUE THREAD

**Issue by Naimikan** [mapbox/mapbox-gl-draw#512]
When I draw something on map and I change the map style, draw plugin breaks and I can't draw anything more. Draw plugin throws me this error:

`"The layer 'gl-draw-polygon-fill-inactive.cold' does not exist in the map's style and cannot be queried for features."`

Example:
http://codepen.io/Naimikan/pen/JRJOVN?editors=1111

I want to draw a polygon on style, save it, change style and continue drawing other polygons on other styles. I think I have to create style's layer on style change because style change won't do it by itself.

**Comment by mcwhittemore** [comment]
@Naimikan your codepen is not working for me. That said, you cannot use `map.setStyle` with Draw as of right now. Moving from satellite to streets destroys the layers added by Draw. This could be handled by Draw if Draw listened to style change events and rebuilt the layers needed by Draw if they had been destroyed.

**Comment by guillec** [comment]
@Naimikan @mcwhittemore is there a work around for this? 
I have the same problem and need.

Best,

**Comment by mcwhittemore** [comment]
@guillec - I don't think I'll have the space to do this in the next few weeks, but I am more than willing to work with someone on a PR and get this merged.

**Comment by jisaacks** [comment]
@mcwhittemore I am having this issue as well. Can you describe to me what is causing the problem and how I may address it. Happy to work on a PR.

**Comment by mcwhittemore** [comment]
@jisaacks - When the style of the map is changed the custom map layers that Draw requires are destroyed but Draw doesn't know this so it keeps trying to reference them which results in the above errors. The solution is to listen to the style change event and make sure that after it is fired, the map still has the required layers. If it does not, they should be added.

**Comment by guillec** [comment]
@jisaacks @mcwhittemore thank you guys!

**Comment by Naimikan** [comment]
@jisaacks @mcwhittemore thanks!

**Comment by jisaacks** [comment]
@mcwhittemore There doesn't seem to be any events fired when the [style is changed](https://github.com/mapbox/mapbox-gl-js/blob/eeecd37c055875d9ca018da891d017ba53ca3241/js/ui/map.js#L640-L664) Do you have any advice on how to listen for the style change. Should I make a PR to mapbox-gl-js to add an event?

**Comment by mcwhittemore** [comment]
@jisaacks - The [render](https://www.mapbox.com/mapbox-gl-js/api/#Map.event:render) event looks like the best option right now.

@lucaswoj - is there a better way to detect style changes than the `render` event?

**Comment by mcwhittemore** [comment]
I just talked with @lucaswoj. The [data](https://www.mapbox.com/mapbox-gl-js/api/#Map.event:data) is what we should use.

**Comment by lucaswoj** [comment]
:+1: note that we're going to be adding a `styledata` event very soon which will be even more specific to style changes

**Comment by jisaacks** [comment]
@mcwhittemore @lucaswoj I added a PR #540 or are y'all wanting to wait until mapbox/mapbox-gl-js#3578 is released and use that?

**Comment by samanpwbb** [comment]
Here's a solution that has worked well for the Mapbox team in the past – use two maps: https://github.com/mapbox/mapbox-gl-draw/issues/494#issuecomment-244266768

**Comment by jisaacks** [comment]
@samanpwbb that would require everyone who uses multple styles to unnecesarily have to do this duplicate map hack. What if they wanted to use several styles, etc. It just seems like we should fix the issue and not force users to use work-arounds. PR #540 fixes the errors and even keeps the polygons when changing map.

**Comment by mcwhittemore** [comment]
@jisaacks - sorry for the delay here, I've been out on family leave. I'll get to reviewing this today.
