### ISSUE TITLE
Is there a way to draw within and existing polygon boundary?

### ISSUE THREAD

**Issue by dulubi** [mapbox/mapbox-gl-draw#517]
Hi, 

I'm trying to prevent drawing outside a polygon. Is there a way to do this with mapbox gl Draw?
Basically when the map is loaded, it shows a polygon, then user can only draw within the polygon.
Is this current possible?

Thanks,
dulubi

**Comment by mcwhittemore** [comment]
@dulubi - This would require a validation step outside of Draw. Currently, the best way to do that is during the transition to `simple_select`. An event handler on the [`draw.modechange` event](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#drawmodechange). In this handler you can validate that the new feature falls within the starting polygon and delete it if it does not.

This is also a good idea for a custom mode. I keep saying Draw should support custom modes (#289), but we need to standardize modes a bit more to make that possible.
