### ISSUE TITLE
determine what is directly selected

### ISSUE THREAD

**Issue by jisaacks** [mapbox/mapbox-gl-draw#520]
When switching to a **direct_select** mode you can select individual points of a polygon. However the `getSelected/getSelectedIds` still returns the entire polygon. Is there anyway to determine if the entire polygon or just some of it's points are selected?

I am building my own controls. When I call `draw.trash()` when in **direct_select** mode it only deletes points if points are selected. It does nothing if no points are selected, it will not delete the selected polygon.

What I would like to do is, if in **direct_select** mode and a polygon is selected entirely (not just some of it's points) and the user clicks trash, then delete the entire polygon (as opposed to do nothing) but there seems to be no way to make that distinction.

Or possibly hide the trash button when in **direct_select** mode unless a point is selected.

Either way I need to be able to make the distinction.

**Comment by mcwhittemore** [comment]
@jisaacks - selected coordinates is managed by the direct_select mode rather than by Draw. I'm up for a PR that finds a good way to manage this in the store like we do with selected features.

`trash` in direct_select will always only deleted the selected coordinates. When this happen it will result in the feature being updated. `Draw.delete(id)` will delete a feature. You could do some sort of check to see if `trash` updated a feature and if it did not, delete the feature.

**Comment by jisaacks** [comment]
@mcwhittemore I happy to work on a PR for this.

I think there are two possible solutions:

* Expose a function like `getSelectedCoordinates()` with an `draw.coordselectionchange` event

Or

* Make `trash()` return a boolean indicating if there were side effects
* Add a method like `trashable()` that indicates if `trash()` will produce side effects
* Add an event like `draw.trashablechange` that fires when the result of `trashable()` for the current mode changes.

I think I am in favor of the `trashable` solution because I think at the end of the day, that's what is hidden/cared about across modes.

Let me know what you think.

**Comment by mcwhittemore** [comment]
So, we should keep `combineFeatures()` and `uncombineFeatures()` features in mind while we think about any solutions that change `trash`. All three of these functions are mode dependent. A way for the api to give developers a way to access what the mode/draw does itself.

Having `trash()`, `combineFeatures()` and `uncombineFeatures()` return false if they had no effect and return true if they had an effect seem like a good idea to me.

I'm not 100% sure what you mean with `trashable()`. Is this a function on `Draw` like `trash`?

All of these things are controls. Another option we've floated around is having a `draw.controls_changed` event. This event would fire any time a control becomes available or unavailable.

**Comment by jisaacks** [comment]
> I'm not 100% sure what you mean with trashable(). Is this a function on Draw like trash?

Basically `trashable` tells you what `trash` will do without actually invoking trash. For example, I do not want to show a trash icon if the result from `trash()` will be false (no side effects). It would be confusing for the user to click trash and nothing happens.

So I need a way to test it without actually trashing anything. Kind of like a **dry-run** for trash, to see if it will produce any side effects. Am I making sense?

**Comment by mcwhittemore** [comment]
Gotcha. So its a function like `Draw.trashable` that returns `true` or `false` based on if `Draw.trash` will have an effect if nothing else changes.

I'm not a fan of this idea. It will result in Draw having a bunch of `___able` handlers. One might argue Draw could have something like `Draw.can('verb')` but this is weird as well.

What do you think about the event idea that tells you which controls are currently active (ie, would have an effect if used?)

**Comment by jisaacks** [comment]
@mcwhittemore ,

> Gotcha. So its a function like Draw.trashable that returns true or false based on if Draw.trash will have an effect if nothing else changes.

> I'm not a fan of this idea. It will result in Draw having a bunch of ___able handlers. One might argue Draw could have something like Draw.can('verb') but this is weird as well.

That's fair.

> What do you think about the event idea that tells you which controls are currently active (ie, would have an effect if used?)

Not exactly sure how that would work. Can you explain a bit?

Also, I will go ahead an get started on a PR for adding the return value for `trash()`, `combineFeatures()` and `uncombineFeatures()`

**Comment by mcwhittemore** [comment]
Draw has a bunch of `controls`. Users can turn off the key bindings and UI representations of these when they init Draw, but the controls are still very much active.

Here is a list of them:

- line
- polygon
- point
- trash
- uncombine
- combine

Half of these controls are always active. Meaning, if you call the related Draw function something will happen. But `trash`, `uncombine` and `combine` are only active when Draw is in a specific state. Here is an explanation of those states.

- trash: active all the time for all modes except direct_select. Active in direct_select if coordinates are selected.
- uncombine: active in simple_select if a MultiLineString, MultiPoint or MultiPolygon is selected
- combine: active in simple_select if all features are of the same type.

The event that I proposed above would fire when the active state of any of these controls changed. The body of the event would look like this:

```js
{
  line: true
  polygon: true
  point: true
  trash: true
  uncombine: false
  combine: false
}
```

Where controls that are `true` can be used and controls that are `false` cannot be used.

What I like most about this solution is that it lets users disable their custom control buttons (and it would let Draw disable the default ones). In your use case, it would let you know when your trash can button should call `Draw.trash()` or `Draw.delete()`.

**Comment by jisaacks** [comment]
@mcwhittemore Yes that sounds great! I am not sure how I would implement that though. I may just not be familiar enough with the code base. What would be in charge of firing the event? The active mode or the active feature? I do not see a `control` object anywhere in the code.

Also I have the return values from `trash()`, `combineFeatures()` and `uncombineFeatures()` ready for a PR, but this is a breaking change. Since before these methods were chainable and this will make then no longer chainable. But it seems like this `activecontrolchange` (or whatever it'll be named) event may alleviate the same need. Your call.

**Comment by mcwhittemore** [comment]
@jisaacks - the modes would be in charge of firing this event.

[Here is an example](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/simple_select.js#L23-L26) of simple select firing an event.

Let's call the event something like `draw.actionable` and always include `trash`, `combineFeatures` and `uncombineFeatures`. The other three we can add later if we want to. They are also modes so I don't want to set a precedent unless we're sure we need it.

Thanks! I think this could be a really good solution for custom controls going forward.

**Comment by jisaacks** [comment]
@mcwhittemore I added a PR #522 with the `Draw.actionable` events. Please take a look and see if it looks correct or needs changes. Thanks
