### ISSUE TITLE
draw.actionable not firing after simple_select trash event

### ISSUE THREAD

**Issue by jisaacks** [mapbox/mapbox-gl-draw#523]
When in simple_select, and invoking `trash()` I should get a new actionable event indicated that trash is now false. This does not happen.

I believe the problem is because simple_select's trash method does not invoke `fireActionables()`. I did not add it there because I was under the impression that a call to `trash()` would always propagate to another `render()` which also calls `fireActionables()`. But that does not seem to be the case?

direct_select mode doesn't seem to be affected by this.

**Comment by mcwhittemore** [comment]
@jisaacks - render must be getting called if the feature is dropping off the map. Maybe the selected features in rendered isn't being updated?

**Comment by jisaacks** [comment]
> Maybe the selected features in rendered isn't being updated?

@mcwhittemore Not sure. How can I check that? Adding the `fireActionables()` to the end of the trash method does fix it, so if render is definitely being called my guess would be that we are invoking `fireActionables()` too soon in the render method (currently ~middleish of the method) maybe that should be called at the very end of the render method.

**Comment by jisaacks** [comment]
@mcwhittemore Yeah I just tested locally. It seems moving the `fireActionables()` to the very last line of the render method fixes it. Not sure why I didn't put it there originally.

**Comment by jisaacks** [comment]
Oh I remember, because that [`if`](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/simple_select.js#L272-L273) statement short circuits the function. Hmmm. If the function exited early [here](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/simple_select.js#L272-L273) would it matter if fireActionables did not get called? I am not sure what that if statement is checking.

**Comment by mcwhittemore** [comment]
Render gets called for each feature that needs to be rendered. If you just deleted a feature it is possible that there are no features to render and thus render won't be called. My guess is that is the difference you are seeing and that moving the function invocation down a few lines has no effective change.

Looks like we should move this out of render. There is no need for it to be called for each feature anyway.

**Comment by jisaacks** [comment]
> Looks like we should move this out of render.

Sure, what do you think makes sense, in `start()` and `trash()`?

**Comment by mcwhittemore** [comment]
It will need to happen in a few places.

1. When the mode starts
2. When delete happens
3. When selection changes

What I liked about the render option is that is made this rather straight forward. I'm worried this is going to be a bit more complex now.

**Comment by jisaacks** [comment]
> What I liked about the render option is that is made this rather straight forward.

Are you sure we can't still keep it in the render function. Can you tell me what `createSupplementaryPoints` does. It did seem to work when I called `fireActionables` after that.

Also, we are already invoking it in start, render combine and uncombine. The only other method is trash, so it seems like if we just added it to trash we would have all the bases covered I think. Especially since you have a check in place that prevents it from double firing.

Let me know.

**Comment by mcwhittemore** [comment]
Adding it to trash and keeping it in render should work. Good thought!

The reason it's not working currently is that render is only called if there are features in the store. This function is called for each feature in the store and can `push` as many sub features to the `mapbox-gl-js` render as it likes. For example, the `createSupplementaryPoints` function creates the handles you click on.

**Comment by jisaacks** [comment]
OK I'll add a PR that adds the call to the `trash()` methods for simple and direct select.
