### ISSUE TITLE
ES6 require error on constrain_feature_movement.js

### ISSUE THREAD

**Issue by jdu** [mapbox/mapbox-gl-draw#526]
Getting a source mapping error on `constrain_feature_movement.js` for version 0.13.1

```
Error: Invalid mapping: {"generated":{"line":19322,"column":11},"source":"constrain_feature_movement.js","original":{},"name":null}
```

any idea why this might be an issue?

**Comment by jdu** [comment]
So this is how I got around this, in case anyone else has this problem, it's a hack to be sure, but it was the only way I could get this to work by using require

```
var mapboxgl = require("mapbox-gl");
window.mapboxgl = mapboxgl;
var mapboxgldraw = require("mapbox-gl-draw/dist/mapbox-gl-draw";
```

If I try to require just `mapbox-gl-draw` the whole thing dies on compilation. If I don't map mapboxgl to window, the mapboxgldraw require attempts to modify window.mapboxgl instead of importing, so I basically have to get mapboxgl into the window namespace before mapbox-gl-draw modifies it.

**Comment by mcwhittemore** [comment]
Meh. That sucks. mapbox-gl-js is going through a refactor on how it handles components which will drop the use of a global mapboxgl, once that lands I'll make sure to kill the need for global.
