### ISSUE TITLE
Moving a polygon while zoomed in causes deformation

### ISSUE THREAD

**Issue by ChrisBellew** [mapbox/mapbox-gl-draw#527]
Ready for a funny bug? :)

![zoommovebug](https://cloud.githubusercontent.com/assets/4590802/19756415/03d9b0a8-9c4f-11e6-8636-ecac628c1c73.gif)

Zoom in to max zoom level and draw a polygon. Then simple select and move the polygon. Notice the deformities that arise. 

Rounding error?

**Comment by jingsam** [comment]
That's funny indeed!

**Comment by apkoponen** [comment]
I can confirm this.

**Comment by apkoponen** [comment]
I've traced this problem to the precision defined in https://github.com/mapbox/mapbox-gl-draw/blob/master/src/lib/truncate_point.js#L1

The higher you set the number (e.g. 1e8) the less deformations the feature will have.

**Comment by apkoponen** [comment]
The deformations no longer appear if you don't execute truncatePoint for the moveCoordinate in https://github.com/mapbox/mapbox-gl-draw/blob/master/src/lib/move_features.js#L13.

**Comment by ChrisBellew** [comment]
Nice find :) so I'm guessing it has a purpose and we can't do away with the
rounding entirely?

**Comment by tmcw** [comment]
So, I know the intended purpose: RFC 9746 GeoJSON recommends coordinates have 6 decimal digits of precision. But this is the wrong place to implement that recommendation. We should remove `truncatePoint` in mapbox-gl-draw. Thanks for the research @apkoponen !

**Comment by apkoponen** [comment]
@ChrisBellew the only function is to make the features smaller by not storing "redundant" decimals.
