### ISSUE TITLE
Dragging Distorts and Simplifies Features

### ISSUE THREAD

**Issue by BellisJ** [mapbox/mapbox-gl-draw#530]
So I noticed that when a feature is dragged, shape is no longer maintained. If you draw a complex geometry, points will jump around on drag. This occurs with both line and polygon drag actions. It is most noticeable while dragging imported bezier curves, but also can easily be observed on complex irregular polygons drawn via the native mapbox-gl-draw tools.

For example, after a drag event a feature such as the following:
![screen shot 2016-11-02 at 4 21 26 pm](https://cloud.githubusercontent.com/assets/6764706/19946080/4c14a480-a119-11e6-94ed-2715ca0088bd.png)

Becomes this:
![screen shot 2016-11-02 at 4 22 00 pm](https://cloud.githubusercontent.com/assets/6764706/19946087/51fca226-a119-11e6-83ec-dacf7e1dbcff.png)

I'm not sure if this simplification/distortion is intended or a known error. I did not see any references to something similar when I searched issues, so curious what is up.

My example is with mapbox-gl-js 0.26.0 and mapbox-gl-draw 0.12.1.

**Comment by tmcw** [comment]
Hi,

Thanks for the bug report! We're already tracking this issue in #527, so closing this issue to consolidate.

- Tom
