### ISSUE TITLE
Make precision configurable

### ISSUE THREAD

**Issue by apkoponen** [mapbox/mapbox-gl-draw#534]
Before making any code I would like to ask, if you would accept an option for precision. In the discussion at https://github.com/mapbox/mapbox-gl-draw/issues/498 the precisions over 6 were seen redundant. However, even if the precision 6 is enough in many cases, it is problematic when you want to draw new features to maps that have features with higher precision than 6. E.g. with objects with precision 8 it is impossible to draw features so that they align with other objects on the map:

![mapbox-gl-draw](https://cloud.githubusercontent.com/assets/5046650/20054698/b2cfbdb0-a4e6-11e6-8db1-e3fc26f7b6b4.gif)

**Comment by tmcw** [comment]
mapbox-gl-draw simply shouldn't handle precision. Truncating coordinates, if it needs to be done, should be performed outside of the library.

**Comment by apkoponen** [comment]
I agree.
