### ISSUE TITLE
How can I do a leaflet style draw?

### ISSUE THREAD

**Issue by juliantai** [mapbox/mapbox-gl-draw#542]
I'm currently trying to draw polygons without closing the final edge. Is there a way to do that? In my screenshot the last stroke isn't drawn displayed until I click the first point.

![screen shot 2016-11-14 at 1 32 06 am](https://cloud.githubusercontent.com/assets/790478/20259555/73ecc786-aa0a-11e6-9fc6-6b59a0de0710.png)

**Comment by mcwhittemore** [comment]
@juliantai - There is not a way to styling Draw to not include the border you are talking about. To do this we'd need to move to using LineStrings for our border styling which would add a lot of data to the map and make Draw slower.
