### ISSUE TITLE
draw.getall() interation between polygon and linestring difference

### ISSUE THREAD

**Issue by beelo** [mapbox/mapbox-gl-draw#543]
//creating draw tools.
var draw = mapboxgl.Draw({
    drawing: true,
    displayControlsDefault: true
});
map.addControl(draw);

After enabling draw function,

the getall() function works for Polygon as intended, however not for lines,

if i draw a polygon and do this

var data = draw.getAll();
    if (data.features.length > 0) {
	var area = turf.area(Data);
        var rounded_area = Math.round(area*100)/100;

works

but if i draw a line and do this

var data = draw.getAll();
    if (data.features.length > 0) {
	var area = turf.lineDistance(data);
        var rounded_area = Math.round(area*100)/100;

it will not work...

Please help me

Thanks

**Comment by mcwhittemore** [comment]
[turf.lineDistance](http://turfjs.org/docs/#linedistance) takes a `Feature` while `Draw.getAll()` returns a `FeatureCollection`.

[turf.area](http://turfjs.org/docs/#area) on the other hand takes either a `Feature` or a `FeatureCollection`.
