### ISSUE TITLE
Preview line does not appear on Firefox

### ISSUE THREAD

**Issue by ChrisBellew** [mapbox/mapbox-gl-draw#544]
Visit this link in firefox.

https://jsfiddle.net/19c9g2gz/

Start drawing a polygon using the tool in the top left. See that the preview line does not appear. The polygon appears after two vertices have been placed. All other browers show a line that moves with the mouse.

**Comment by mcwhittemore** [comment]
Hmmm... this is an interesting bug. It looks like the mousemove event isn't doing the same thing in firefox as the other browsers.
