### ISSUE TITLE
initialisation of control and consistency between core Mapbox plugins

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-draw#555]
The README advises to initialise the Draw control with:

    var Draw = mapboxglDraw();

However the Geocoding plugin uses,

    var Geocoder = new MapboxGeocoder();

and the Directions plugin [will soon use](https://github.com/mapbox/mapbox-gl-directions/pull/98/files#diff-f8c408fd257ff44ce4b01e5f8422b1e1R29),

    var Directions = new MapboxDirections();

To ensure consistency between all the core Mapbox plugins, reducing confusion for plugin users should Draw follow this format and use,

    var Draw = new MapboxDraw();

?

**Comment by mcwhittemore** [comment]
I'm good with this change. It will be breaking (for script tag users) but I'll target it for the next CDN release. Thanks for the suggestion.

**Comment by mcwhittemore** [comment]
Closed by #556
