### ISSUE TITLE
double click anywhere on line or polygon outline to add a node

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-draw#558]
If user is zoomed in, there's no way to add additional points to a line unless user zooms far out. It's a common pattern in drawing tools to double-click on lines anywhere on the line to add an additional node.

**Comment by mcwhittemore** [comment]
MapboxDraw's functionality is locked. To do this, please use [custom modes](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw).
