### ISSUE TITLE
How to add a custom style without deleting all the default styles

### ISSUE THREAD

**Issue by benjaminhon** [mapbox/mapbox-gl-draw#564]
Hi,
when i create a new style 
```
new MapBoxDraw(
...
styles: [
 ...
]
)
```
all the default styles are gone, only the style i add exists, is there any way i can just add 1 style without affecting the normal behaviour? it seems to be a pain to rewrite all the default styles to just add my custom style

thanks

**Comment by mcwhittemore** [comment]
@benjaminhon - There is not a way to do what you are asking for via the Draw api. I'd suggest taking the style used by Draw and adding your style to it and then passing that to Draw.

https://github.com/mapbox/mapbox-gl-draw/blob/master/src/lib/theme.js

**Comment by benjaminhon** [comment]
i see, ok thanks for the reply

**Comment by eddydg** [comment]
Is overwriting the default style the wanted behavior? I feel that extending the style would be more natural.
Not sure if it's enough, but by adding:
```javascript
withDefaults.styles = defaultOptions.styles.concat(withDefaults.styles);
```
just before this line:
https://github.com/mapbox/mapbox-gl-draw/blob/c14acde0af91c236e4d67ac9ddb69df11c063fc2/src/options.js#L62
we can then add the custom style over (without removing) the default one.

**Comment by andrewharvey** [comment]
What about when you want to completely replace the style, how would that work?

In the past I've used
```js
var defaultTheme = require('@mapbox/mapbox-gl-draw/src/lib/theme.js')
```

Allow you to modify or append to it and use that as your styles object.

**Comment by eddydg** [comment]
Yup I thought about this too after using the custom styles a bit more. It's probably better to leave as is.
Thanks for that line, it will come in handy.
