### ISSUE TITLE
No drawing across the dateline

### ISSUE THREAD

**Issue by MortenHofft** [mapbox/mapbox-gl-draw#566]
It is not possible to draw across the dateline if the world is spun more than 1 round
Go west a couple of rounds and draw and you will not be able to see what you have drawn.

![screen shot 2016-12-16 at 11 10 19](https://cloud.githubusercontent.com/assets/6759267/21259147/72fcc0b2-c380-11e6-9046-3b3628807570.png)

try it here: http://codepen.io/hofft/pen/xRmZRX
copied from https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/
only difference is that it starts rotated

Thanks you for a nice product

**Comment by mcwhittemore** [comment]
@MortenHofft Our current recommendation is to limit the map to the `+/- 180` world. You can do this by using [map.jumpTo](https://www.mapbox.com/mapbox-gl-js/api/#Map#jumpTo).

This is an upstream limitation in [geojson.vt](https://github.com/mapbox/geojson-vt/pull/69#issuecomment-235935837). There are some plans to use [stacker-of-worlds](https://github.com/mapbox/stacker-of-worlds) to solve this problem but this requires us solving [splitting non-simple polygons](https://github.com/mapbox/stacker-of-worlds/issues/6).

For more back story see: https://github.com/mapbox/mapbox-gl-draw/issues/535.

**Comment by MortenHofft** [comment]
thanks for the prompt response. I'll see what I can do with jumping, it might actually be enough for my use case.
