### ISSUE TITLE
Feature request to draw vertex points

### ISSUE THREAD

**Issue by kkdd** [mapbox/mapbox-gl-draw#568]
Feature request to draw vertices of an inactive line-string (or polygon) when specified as follows, for example:

```
var draw = new MapboxDraw({
    displayControlsDefault: false,
    controls: {
//        line_string: true,  //  vertices are not drawn
        line_string_with_vertices: true,
        trash: true
    });
```

**Comment by mcwhittemore** [comment]
@kkdd - Are you saying you want Points to be created as well as the LineString?

**Comment by kkdd** [comment]
Yes. I hope to draw a LineString with Points at its vertices, not only during editing.
(Example pictures in https://en.wikipedia.org/wiki/Linestring)

**Comment by mcwhittemore** [comment]
Oh, we drop the vertices while drawing to help improve performance. Why do you want to see them?

**Comment by kkdd** [comment]
I hope to draw a linestring with the vertices for emphasizing. In other words, an ordered series of points with a connecting line.

**Comment by mcwhittemore** [comment]
This is something that we're going to add directly. My hope is that we will have custom mode support. For more info on that, here is where I've ticked it out. https://github.com/mapbox/mapbox-gl-draw/issues/289
