### ISSUE TITLE
Draw removes boxZoom but never restores it on removal

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#571]
During setup Draw removes boxZoom (to be able to provide shift-box-selections instead):

https://github.com/mapbox/mapbox-gl-draw/blob/78fddb17520f2869902b2e6dbf93c1bf888cf421/src/setup.js#L39

But when draw is removed it never tries to enable it again.

**Comment by andrewharvey** [comment]
I tried to implement this in https://github.com/andrewharvey/mapbox-gl-draw/commit/1d72e54a85e82539970b9cc33606c3a826e6e2c1, but it's not ready for PR because when testing it seems like the map becomes stuck in pan mode...

**Comment by averas** [comment]
Probably related to https://github.com/mapbox/mapbox-gl-js/issues/2237

**Comment by andrewharvey** [comment]
> Probably related to mapbox/mapbox-gl-js#2237

That sounds like the exact issue, will have to wait for that to be resolved before this issue can be addressed.

**Comment by mvl22** [comment]
Can anyone suggest a workaround for this?

**Comment by kibala145** [comment]
As a workaround call `map.boxZoom.enable()` after `removeControl` manually
