### ISSUE TITLE
Changing the draw mode while in draw_polygon mode stops browser execution.

### ISSUE THREAD

**Issue by LarryFix** [mapbox/mapbox-gl-draw#582]
I am looking for way to allow a user who started drawing a polygon to click a Cancel button and exit "edit" mode. The goal is to imitate the effects of the Esc key.

When I call Draw.setMode() in the click handler for the Cancel button, I end up getting numerous modeChanged events until Chrome stops executing my app. This happens whether I set the mode to static or to simple_select.

The API document does not detail any restrictions on changing the mode via calls to changeMode() while in draw_polygon mode.

Should this mode change work?

**Comment by mcwhittemore** [comment]
@LarryFix,

Using `Draw.changeMode` is the right way to do what you want, so my guess is that something else is going on here. Do you have event listeners triggering `Draw.changeMode`? Maybe an event you don't expect to see fired is being fired?

If that doesn't sound right, can you post code that reproduces this problem so we can confirm its a bug?

Thanks,
Matthew

**Comment by LarryFix** [comment]
You are correct Matthew. I do have a listener for the `Draw.create` event which also calls `Draw.changeMode`. My create listener gets triggered if there are 4 or more vertices defined for the polygon and `Draw.changeMode` is called by the Cancel button click listener. 

So I really did not expect that. If there are 3 or fewer vertices, the event is not fired.

Is it expected behavior that a shape will be created if 4 or more vertices have been defined and the mode is changed?

If so, there does not seem to be a safe way my app to provide a cancel button.

**Comment by LarryFix** [comment]
Sorry, it took me a little more time fully understand your comments. The problem was my 'Draw.create` listener was calling `Draw.changeMode`. The browser is much happier now that I removed that line.

But it leaves me wondering if it is possible to implement a Cancel button that prevents the creation of the current polygon regardless of the number of vertices defined and ends up in `static` mode.

Any suggestions?

**Comment by mcwhittemore** [comment]
Larry,

If you call [`Draw.trash()`](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#trash---draw) rather than `Draw.changeMode()` for your cancel event you should be good.

Matthew

**Comment by LarryFix** [comment]
Matthew,

That works great. Looks like I need to read the entire API manual again.

Thanks so much!

Larry

**Comment by mcwhittemore** [comment]
Sounds great!
