### ISSUE TITLE
After removing a feature, I can't select other ones

### ISSUE THREAD

**Issue by BrunoSalerno** [mapbox/mapbox-gl-draw#590]
(Using Mapbox GL Draw 0.16.0 and Mapbox GL 0.31)

If I remove a feature using the trash control, and then I try to select another feature I get and error. What my code does when I remove a feature is listening to the remove event, updating the FeatureCollection, and using `Draw.set(featuresUpdated)`.

The error I get when I try to select a feature after doing this is:
```
TypeError: undefined is not an object (evaluating 'e.toGeoJSON')
```
And if I try again, then:

```
TypeError: undefined is not an object (evaluating 'e.store.get(i).type')
```

Any advice?

**Comment by mcwhittemore** [comment]
@BrunoSalerno do you have a stack trace for this error? It sounds like the feature has been deleted from Draw but has not been deleted from the map... I haven't seen this recently, but it is possible MapboxGL@0.31 works a bit differently.

Are you sure the feature is deleted before calling `Draw.set(featuresUpdated)`. This action should reset the state of Draw, but it is trying to do this in a 'least changes possible' kind of way so its possible something funky is going on here.

Anyway, stack traces and/or a fiddle would help debug.

**Comment by BrunoSalerno** [comment]
@mcwhittemore thanks for your answer. Yes, the feature is deleted because everything starts in the `draw.delete` event listener. 
Here are the screenshots of the two errors:

The first one
<img width="251" alt="captura de pantalla 2017-01-31 a las 17 07 58" src="https://cloud.githubusercontent.com/assets/6061036/22473153/2eef5a02-e7d8-11e6-8218-5c3b45b92bbc.png">

When I try to select a feature a second time (and n times afterwards):
<img width="252" alt="captura de pantalla 2017-01-31 a las 17 08 19" src="https://cloud.githubusercontent.com/assets/6061036/22473246/83304c66-e7d8-11e6-9f2b-422c530cfde2.png">

**Comment by mcwhittemore** [comment]
@BrunoSalerno - sorry, I should have been more clear, can you send me the stack trace so I can see line numbers? Really, a [jsfiddle](https://jsfiddle.net/) that reproduces this would be awesome.

**Comment by mcwhittemore** [comment]
Without a jsfiddle, no action can be taken here. Closing.
