### ISSUE TITLE
Draw.add(feature) - TypeError: null is not an object (evaluating 'e.store.get')

### ISSUE THREAD

**Issue by dwaldmannDE** [mapbox/mapbox-gl-draw#594]
Hi all, 

I encountered an error with draw when I'm using Draw.add(GeoJSON-Object). TypeError: null is not an object (evaluating 'e.store.get') is showing up in the console.

The issue can be seen here: https://codepen.io/dwaldmannDE/pen/jBNBWx

I based the code on the following example:
`Draw.add({ type: 'Point', coordinates: [0, 0] });
Draw.add({ type: 'Point', coordinates: [1, 1] });
Draw.add({ type: 'Point', coordinates: [2, 2] });
console.log(Draw.getAll());`

I'm using: 
mapbox-gl-js/v0.32.1
mapbox-gl-draw/v0.16.0

How can one prevent this error?

Thank you!

**Comment by drewbo** [comment]
@dwaldmannDE I think because `map.addControl(draw);` is waiting for the map to load, the other calls are firing before Draw is added to the map and causing a race condition. If you put your other code inside the `map.on('load'...` block it seems to work

**Comment by dwaldmannDE** [comment]
@drewbo 

Thank you! This solved my problem. I would never have thought about this.

**Comment by davidtheclark** [comment]
For future visitors: this need to wait for the map to load is documented at the top of https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md.
