### ISSUE TITLE
getSelected() should return shape currently being drawn (maybe?)

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-draw#595]
Another option would be adding `getActive` to return this shape

**Comment by keyofj** [comment]
"draw.update" returns the polygon that is adjusted. Does this not return selected points for other draw types?

**Comment by mcwhittemore** [comment]
This is breaking change as thus [a great candidate for custom mode](471fdfa89eb26d90fbe16791f5fc56a33b9026dc).
