### ISSUE TITLE
getSelectedPoints should be getSelectedVertices?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#597]
It seems to me that `getSelectedPoints` is a misnomer. The name suggests that I could have a polygon, two lines, and two points selected, and this function will return only the points. The true intention is to return the selected vertices of a directly selected feature, right?

**Comment by mcwhittemore** [comment]
Yea... I missed this in the PR...

Bigger question, should we drop the use of `vertices` for the GeoJSON word `positions`?

**Comment by davidtheclark** [comment]
> should we drop the use of vertices for the GeoJSON word positions

Sure!

**Comment by mcwhittemore** [comment]
This has been well established. If we talk about doing a v2 of MapboxDraw, we should bring this back up.
