### ISSUE TITLE
Hover styling

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-draw#60]
It would be nice if on hover, the feature that would be selected if clicked was styled differently.

**Comment by kelvinabrokwa** [comment]
I'm concerned about what this entails performance-wise. It would mean re-rendering two whole geojson layers on hover (and on exit) of features.

**Comment by lucaswoj** [comment]
This is something we've been thinking about building upstream in GL JS. It'll probably be a priority soon after data-driven styling lands.

As a temp workaround, what if you created a separate layer with *only* the hovered feature and draw it on top of the main features layer?

**Comment by kelvinabrokwa** [comment]
@lucaswoj thats a good idea. I'll try it.

**Comment by mcwhittemore** [comment]
We need at least 4 styles

- Unselected
- Unselected Highlighted
- Selected
- Selected Highlighted

**Comment by mcwhittemore** [comment]
The more I think about this the more I think this is something the end user should do if they want and we should leave alone. There is no need to have lots of featuresAt calls when we do need them.
