### ISSUE TITLE
Draw plugin affects other plugins 

### ISSUE THREAD

**Issue by KfirShainholtz** [mapbox/mapbox-gl-draw#602]
Hey, 
I have a custom control that contains an input  which I'm using, that when used parallely with draw control, the backspacing doesn't work at the custom module. 
I've seen that in the draw control code, when subscribing to key down event, backspacing is prevented if a geometry isn't being actually deleted. 

I could PR this issue, but I think you should think how you could handle this event in a better way. 

Thanks guys!

**Comment by mcwhittemore** [comment]
@KfirShainholtz,

Thanks for bringing this up. Just to make sure we're clear, the problem here is that the backspace event is captured and stopped by Draw even if Draw doesn't delete anything?

A PR would be great. Thanks!

**Comment by wqoq** [comment]
Just adding my +1 to this. Can't really use Mapbox-gl-geocoder with this, because you can't backspace or delete in the geocoder textbox if you make a mistake. Even when there's no geo objects on the map.

**Comment by keyofj** [comment]
Could this also result in slow rendering when using draw in IE 11? When entering mode DRAW_POLYGON it is taking a long time for the cursor to change and to draw the polygon. A considerable lag is happening that does not happen in Chrome or Firefox. If I use the example page 

[https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/)

I can not duplicate the slowness, but it does not have other plugins such as the autocomplete.

**Comment by mcwhittemore** [comment]
MapboxDraw has custom key handlers. One of these key handlers is stopping the propagation of the event and/or preventing the default which is why you can not use the `delete` key.

> Could this also result in slow rendering when using draw in IE 11?

This is a different issue and is either a problem with mapbox-gl-js or a performance difference in how IE handles some of the data structures MapboxDraw uses. As you find more about this info, please feel free to open a different issue.

**Comment by mcwhittemore** [comment]
This is fixed in master, and will be in the next release.

471fdfa89eb26d90fbe16791f5fc56a33b9026dc
