### ISSUE TITLE
Can I draw Rectangle?

### ISSUE THREAD

**Issue by jack-solutions** [mapbox/mapbox-gl-draw#604]
Is there any option available in library for drawing Rectangle and Circle on map as Polygon and Line as in [This Demo](https://developers.google.com/maps/documentation/javascript/examples/drawing-tools)

**Comment by mcwhittemore** [comment]
@jack-solutions,

GeoJSON doesn't have the concept of a Circle and a Rectangle, so Draw has decided to not implement these drawing modes. The concern is that while we can make sure the tool draws a circle or rectangle well, we can't know from GeoJSON added to Draw if a feature is a Rectangle or Circle. Well... we could, but it opens up a bunch of weird edge cases.

That said, being able to Draw these shapes is needed. While Draw will not support this, @drewbo is currently working on letting Draw have custom drawing modes and I suspect that Circle and Rectangle modes will quickly come about once that work is ready.

Here is the issue where we are tracking Custom Modes.

https://github.com/mapbox/mapbox-gl-draw/issues/289

Regards,
Matthew

**Comment by BhavanPatel** [comment]
@mcwhittemore @drewbo I think GeoJSON support rectangle... as I have seen in this [Demo](http://geojson.io/) and map seems mapbox.

**Comment by mcwhittemore** [comment]
@BhavanPatel GeoJSON supports Polygons and thus you can create GeoJSON rectangles. My comments in #604 aren't trying to say this isn't possible, but that Rectangles are out of the scope of Draw. It should be noted, that Draw used to have Rectangle support and it caused unexpected functionality multiple times so it was removed. Around this same time, we decided that Draw would only support the code [GeoJSON Spec](https://tools.ietf.org/html/rfc7946) and that custom modes could provide for extra functionality such as Rectangles and Circles.

Personally, I really want a mode that lets me Draw hexagons. Sadly I don't have a lot of time for this project currently. @drewbo has shown interest in getting Custom Modes to happen, but more help from others in the community would be great too.

**Comment by fc** [comment]
Someone created this:
https://github.com/edgespatial/mapbox-gl-draw-rectangle-mode

Works for me.
![image](https://user-images.githubusercontent.com/20962/44960966-b7c51a80-aebd-11e8-9c94-9a5f35a5c317.png)

**Comment by andrewharvey** [comment]
For a demo of https://github.com/edgespatial/mapbox-gl-draw-rectangle-mode see  https://bl.ocks.org/andrewharvey/31b8180e3f5f1e12849a352796e0daf4

**Comment by mcwhittemore** [comment]
I've added this to the mode list page.
