### ISSUE TITLE
Deploy 0.16.1 to the CDN

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-draw#608]
0.16.1 is tagged as a release https://github.com/mapbox/mapbox-gl-draw/releases and appears in the CHANGELOG.md however it's not on the CDN https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v0.16.1/mapbox-gl-draw.css

**Comment by mcwhittemore** [comment]
@lucaswoj is there a way for us to publish tags that are already on github to the cdn?

@andrewharvey - we should have a new version in the next few days, will that work for you?

**Comment by andrewharvey** [comment]
@mcwhittemore It's not urgent, so that's fine thanks.

**Comment by lucaswoj** [comment]
@mcwhittemore This should do it:

```
# make sure you are authenticated for AWS
git checkout v0.16.1
npm run build
aws s3 cp --recursive --acl public-read dist s3://mapbox-gl-js/plugins/mapbox-gl-draw/v0.16.1
```

(You also have the option of uploading the files via the AWS web console.)

**Comment by mcwhittemore** [comment]
@andrewharvey 0.17.0 is live on the CDN now
