### ISSUE TITLE
Cannot delete features in direct_select mode

### ISSUE THREAD

**Issue by Yitaek** [mapbox/mapbox-gl-draw#612]
draw.delete does not fire in direct_select mode. I can move, update, etc but I can only delete in simple_select mode

**Comment by mcwhittemore** [comment]
Yitaek ,

Thanks for reporting this. Can you provide a link to jsfiddle so I can see this in action and know we're seeing the same error?

Thanks,
Matthew

**Comment by Yitaek** [comment]
Hey Matthew,

Thanks for the quick reply. I don't have a link to jsfiddle, but even the official mapbox example https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/ has the same error. It seems to be using v0.17.0 as well and is displaying the same error (e.g. double click on the polygon to be in direct_select mode and I am unable to delete the feature). 

Best,
Yitaek

**Comment by mcwhittemore** [comment]
Yitaek,

Oh. Sorry. I misread this. `direct_select` does not let the `delete` key delete features as its working with vertices.

> Lets you select, delete, and drag vertices; and drag features.
*https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#direct_select*

If you want Draw to do this, you can override the `delete` key handler to call `Draw.delete`.

Regards,
Matthew
