### ISSUE TITLE
can we update the mapbox-gl-js dependency? 

### ISSUE THREAD

**Issue by z0d14c** [mapbox/mapbox-gl-draw#613]
Listed `mapbox-gl-js` dependency: 0.27.x - 0.29.3
I'm using `mapbox-gl-draw` with`mapbox-gl-js` with 0.32.1 right now with no problems.

Can we update the dependency so that I can keep my package.json and have `npm install`, `npm shrinkwrap`, etc. not give me any complaints/warnings?

**Comment by z0d14c** [comment]
I didnt check the new version of this which is apparently more up to date. 😩  Maybe we can close this issue, although it seems that the dependency is still behind mapbox-gl-js, which is at `0.34.0`. I'm wondering what the process is for updating this dependency.

**Comment by mcwhittemore** [comment]
Thanks @z0d14c. PRs that bump the version are our best solution right now. Until `mapbox-gl-js` goes to `1.x.x` the team has asked us to accept new versions after testing. Feel free to open this PR whenever you need to.

**Comment by mcwhittemore** [comment]
I'm going to close this as the original request has been solved. Please use a PR to fix any individual gl-js dependency issues.

**Comment by z0d14c** [comment]
Thanks!

Thomas A. Grice
