### ISSUE TITLE
Seeking clarity on release versions and mapbox-gl core support

### ISSUE THREAD

**Issue by davecranwell** [mapbox/mapbox-gl-draw#623]
- NPM thinks the latest versions is 0.16.0 despite 0.17.1 listed in Github
- The package.json in 0.17.1 has a peer dependency on mapbox-gl >=0.27.0 <=0.34.0
- But the 0.17.1 README.md states right at the top "Requires mapboxl-gl (version 0.27.0 – 0.29.x)"
- And yet the description of 0.16.0 on NPM states "Requires mapbox-gl-js@0.27.0 or higher."
- 0.17.1 can't be installed via NPM. It could be installed via the commit hash, along with mapbox-gl 0.34.0, except when you do this `mapbox-gl/plugins/src/mapbox-gl-draw` folder never gets created

Please can someone explain what's going on? Are the releases above 0.16.0 not actually releases?

**Comment by mcwhittemore** [comment]
@davecranwell - mapbox-gl-draw has moved to `@mapbox/mapbox-gl-draw` on NPM.

https://www.npmjs.com/package/@mapbox/mapbox-gl-draw

I'll update the old npm project to make this clear.

I'm also going to update the readme to point people to the package.json for info about compatible versions of mapbox-gl-js. I'll take you on this PR for review.

I'm not sure what you mean by your last bullet point. Maybe this was an artifact of how mapbox-gl used to do plugin management?

**Comment by mcwhittemore** [comment]
It looks like I no longer have access to the old `mapbox-gl-draw` project on npm.

**Comment by davecranwell** [comment]
Doh, how could I have missed the install instructions, which I note already mentioned the @mapbox namespace! Thanks for clarifying all the same. Pity about the old npm project. Will check that PR.
