### ISSUE TITLE
jsonlint error when importing library

### ISSUE THREAD

**Issue by ddibiase** [mapbox/mapbox-gl-draw#626]
**mapbox-gl-js version**:

Whatever is bundled with the latest version of draw.

**mapbox-gl-draw version**:

Using version 0.16

### Steps to Trigger Behavior

 Import the library using `import MapboxDraw from '@mapbox/mapbox-gl-draw';`
 
### Expected Behavior

I'm using webpack to pull the library into my application. I tracked down the line in jsonlint and for some reason it appears it's making a call with the `fs` library. I kind of gave up and just used the CDN version.

### Actual Behavior

client:119 ./~/jsonlint-lines/lib/jsonlint.js
Module not found: Error: Can't resolve 'fs' in '/Users/ddibiase-macbook/Projects/usi-compass-api/public/node_modules/jsonlint-lines/lib'
 @ ./~/jsonlint-lines/lib/jsonlint.js 692:17-30
 @ ./~/@mapbox/geojsonhint/lib/index.js
 @ ./~/@mapbox/mapbox-gl-draw/src/api.js
 @ ./~/@mapbox/mapbox-gl-draw/index.js
 @ ./src/views/questions/pathmap.js
 @ ./src/views/questions.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/index.js

**Comment by ddibiase** [comment]
Ah shoot, after more searching found this issue here: https://github.com/mapbox/mapbox-gl-js/issues/1649.

This was a webpack issue not related to the library. This needed to be added to webpack config:

```
  node: {
    fs: "empty"
  }
```

**Comment by mitulgolakiya** [comment]
@ddibiase any idea where and in which file should I add this block while using this with Angular 5?

**Comment by a-faraz** [comment]
@mitulgolakiya did you every figure this out for Angular 6?

**Comment by ParryQiu** [comment]
Not elegant but effective, just hacked the code directly.
file path: /node_modules/jsonlint-lines/lib/jsonlint.js
comment the codes from line 688 - 693, it works.

![code comments](https://image.devopen.club/Jietu20190108-092636@2x.png)
