### ISSUE TITLE
0.17.4 has empty dist js file

### ISSUE THREAD

**Issue by ChrisBellew** [mapbox/mapbox-gl-draw#637]
Hello,

I have just `npm install @mapbox/mapbox-gl-draw@0.17.4` and have noticed that the dist/mapbox-gl-draw.js is an empty file. In `0.17.3` the file is 100kB. Is this expected?

Thanks
Chris

**Comment by mcwhittemore** [comment]
Hi Chris,

Its not... though I really don't like how we currently build the dist folder. I think right now this happens on `npm publish` but it should happen on `npm post-install` I think. I don't use Draw this way so if you have thoughts on how to do this correctly and help us make sure it always happen, I'm all ears.

Matthew

**Comment by danielthall** [comment]
Same issue here. Commenting to follow this thread.

**Comment by z0d14c** [comment]
Same issue as well :\ trying to upgrade to get the new peer dependency for mapbox-gl so i can update versions for that and I ran into this...

**Comment by andrewharvey** [comment]
Checking out the process for mapbox-gl-geocoder at https://github.com/mapbox/mapbox-gl-geocoder/blob/master/CONTRIBUTING.md#deploying which says to run `npm run prepublish` before `npm publish`.

Perhaps the solution here is adding an instruction at the start of https://github.com/mapbox/mapbox-gl-draw#publishing to run `npm run prepublish`?

**Comment by mcwhittemore** [comment]
I've cut a new release `0.18.0` and the `dist/mapbox-gl-draw.js` in non-empty when I install it locally. Can someone else confirm and then we'll close this.

**Comment by z0d14c** [comment]
@mcwhittemore can you publish it on npm?

**Comment by mcwhittemore** [comment]
@z0d14c - `0.18.0` is [on npm](https://www.npmjs.com/package/@mapbox/mapbox-gl-draw).

**Comment by z0d14c** [comment]
works for me @mcwhittemore

**Comment by mcwhittemore** [comment]
Thanks @z0d14c!
