### ISSUE TITLE
map.on('draw.update') fires twice on coordinate change of drawn polygon

### ISSUE THREAD

**Issue by bdoyle522** [mapbox/mapbox-gl-draw#640]
1. Add map.on('draw.update') listener
 2. Change coordinates on an existing polygon (put a console.log on the event to observe)

Expected Behavior: Per the API, we should see the event logged in the console AFTER finishing the coordinate change (after you have moved the point and released the mouse)

Actual Behavior: fires 'draw.update' coordinate change event upon first click, while mouse is still held down. Fires the second 'draw.update' coordinate change event after the mouse is released.

**Comment by bdoyle522** [comment]
I noticed this happens specifically when you choose one of the drag-point between existing coordinates that isn't a coordinate yet. So I guess when the "drag-point" is selected, an event is fired upon creating the coordinate and then another is fired when you move the newly created coordinate in the same move, without ever releasing the mouse.

**Comment by mcwhittemore** [comment]
@bdoyle522 - Thanks for opening this issue. Can you please follow the issue template to help others debug this. Versions and a [jsfiddle](https://jsfiddle.net/) are key. Thanks!

**Comment by mcwhittemore** [comment]
Looking into this a bit more. This is expected behavior. The `draw.update` event fires everytime the features updates. Once for adding a position to the polygon, another for moving that position.

**Comment by Erutan409** [comment]
@mcwhittemore is it possible to separate these out into different events, then?  Or is there any way to discern between the two fired events that's not immediately apparent to me?

**Comment by mcwhittemore** [comment]
@Erutan409 - hmmm... it would be hard to know if a coordinate was added or if a coordinate moved short of comparing the feature before the update and after the update, though you could do that.

You could add some sort of property to the event that indicated what kind of change is happening though out the feature types. They all use [feature.changed](https://github.com/mapbox/mapbox-gl-draw/blob/7456a6478b2698d19ade958fab631d6a8d3fb73a/src/feature_types/feature.js#L12-L14), so you'd want to start there.
