### ISSUE TITLE
Active draw tool button does not grey out enough on mobile

### ISSUE THREAD

**Issue by Radikaltech** [mapbox/mapbox-gl-draw#644]
**mapbox-gl-js version**:
**mapbox-gl-draw version**:0.17.4

### Steps to Trigger Behavior

 1. Open in mobile https://radikaltech.com/DroneFlightPlan1.6.html
 2. Use the draw tools
 3.the selected draw tool button does not grey out enough for user to note is active.

### Expected Behavior

the buttons should grey out darker for the user to note which is active when using the tool.

### Actual Behavior
the selected draw tool button does not grey out enough for user to note is active.

**Comment by mcwhittemore** [comment]
@Radikaltech,

You can overwrite the CSS to make these darker but this kind of change is not something we plan to make to make the Draw itself.

Regards,
Matthew
