### ISSUE TITLE
split/cut Line

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-draw#647]
I'd like an easy way to split/cut a line at a node.

**Comment by drewbo** [comment]
@andrewharvey if you want to check out our downstream implementation of this, we set up a method to [do this in our app](https://github.com/developmentseed/skynet-scrub/blob/master/app/scripts/components/map/index.js#L333-L353). Abstracted code:

```js
// get an event 'e' from map.on('click'... and do some test for being in "splitting mode"
const ids = Draw.getFeatureIdsAt(e.point);
if (!ids.length) { return; }
const line = Draw.get(ids[0]);
const cursorAt = turf.point([e.lngLat.lng, e.lngLat.lat]);

// delete the existing line, and add two additional lines.
Draw.delete(line.id);
Draw.add(turf.lineSlice(turf.point(firstCoord(line)), cursorAt, line));
Draw.add(turf.lineSlice(cursorAt, turf.point(lastCoord(line)), line));
```

The `first/lastCoord` functions are little line helper utilities:
```js
const firstCoord = (line) => line.geometry.coordinates[0];
const lastCoord = (line) => line.geometry.coordinates[line.geometry.coordinates.length - 1];
```

**Comment by mcwhittemore** [comment]
This is a great idea for a custom mode, for info on how to write one please see [there new docs](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw).

**Comment by BrunoSalerno** [comment]
I wrote a custom mode that does this, inspired by the work of @drewbo https://github.com/BrunoSalerno/mapbox-gl-draw-cut-line-mode
