### ISSUE TITLE
Adding drawControl appear to break map click + drag zoom

### ISSUE THREAD

**Issue by benheb** [mapbox/mapbox-gl-draw#651]
**mapbox-gl-js version**: 0.37.0 and 0.28.0
**mapbox-gl-draw version**: v0.18.0

### Steps to Trigger Behavior

 1. Add the drawing control to map: `map.addControl(this.draw, 'bottom-right');`
 2. Hold shift, click down on map and drag
 3. Observe light box that is drawn over map 

### Expected Behavior
When release click, map should zoom to extent of box

![zoom-works](https://cloud.githubusercontent.com/assets/910495/26742420/d77af736-479a-11e7-8aa4-7cf6fb9c77b7.gif)

### Actual Behavior
Nothing happens 

![zoom-busted](https://cloud.githubusercontent.com/assets/910495/26742378/b0ddb528-479a-11e7-9343-4528e6afb3f3.gif)

I observe the same issue here: https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

**Comment by mcwhittemore** [comment]
Brendan,

This is expected behavior with a way to opt out. If you set `boxSelect` to `false` when setting up MapboxDraw you should be good. Here is where you can [find this in the docs](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#options).

I hope that helps.

Matthew

**Comment by benheb** [comment]
@mcwhittemore thanks!!

**Comment by nreese** [comment]
> This is expected behavior with a way to opt out. If you set boxSelect to false when setting up MapboxDraw you should be good. Here is where you can find this in the docs. 

Updated link [find this in the docs](https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/API.md#options)
