### ISSUE TITLE
npm install cannot finish properly

### ISSUE THREAD

**Issue by aarzhou** [mapbox/mapbox-gl-draw#663]
**mapbox-gl-js version**: --
**mapbox-gl-draw version**: v0.19.0

### Steps to Trigger Behavior

 1. Clone this repo, checkout out v0.19.0 or just use master branch
 2. run `npm install`
 3. error out

The last few lines of the error message I received:
```
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox nespace: install @mapbox/geojson-area instead
npm WARN deprecated geojson-normalize@0.0.0: This module is now under the @mapx namespace: install @mapbox/geojson-normalize instead
npm WARN deprecated ignore@3.2.0: several bugs fixed in v3.2.1
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gulp-sourcemaps@1.7.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'mapbox-gl-js-mock'
npm ERR! notarget
```

**Comment by mcwhittemore** [comment]
@aarzhou I've just done a clean install locally and everything seems fine. What version of NPM are you using? I'm using `2.15.11`.

**Comment by aarzhou** [comment]
I'm using npm 5.0.4, would that be the reason? npm earlier than version 3 does not support flat directory structure though. Let me give a try

**Comment by aarzhou** [comment]
Yea, it works. I downgraded to v3.10.10, which comes with node v6.11 installation. Everything looks fine now. Thank you!

**Comment by mcwhittemore** [comment]
You can also use `yarn` if you want @aarzhou.

**Comment by aarzhou** [comment]
@mcwhittemore, thanks a lot for the recommendation!
