### ISSUE TITLE
Drawing an area broken on Safari

### ISSUE THREAD

**Issue by ChrisBellew** [mapbox/mapbox-gl-draw#665]
Hello,

I've just noticed that 0.38.0 appears to be broken on Safari on OSX. The demo page (https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/) shows this as well.

If you click to start drawing an area, and then move the mouse, the whole map pans as well. Could it be something to do with mapbox underneath thinking that it's a pan action?

**Comment by jwilliams-ecometrica** [comment]
I can confirm that I'm having the same problem, does anyone know what is causing this?

**Comment by andrewharvey** [comment]
This regression happens in https://github.com/mapbox/mapbox-gl-draw/commit/362d33517983ed1af103ec157c7ece919634ec85

/cc @z0d14c

**Comment by z0d14c** [comment]
Will take a look ASAP

**Comment by nicholasgonzalezsc** [comment]
What's the status on fixing this?
@mcwhittemore @ChrisBellew @z0d14c @andrewharvey
