### ISSUE TITLE
Feature Request: ability to turn off dragging of features

### ISSUE THREAD

**Issue by calvinmetcalf** [mapbox/mapbox-gl-draw#667]
I'm using this in an app were using are drawing a polygon over an area and maybe editing it and some feed back I get is they really don't ever want to be moving the polygon just edit the vertexes so it would be nice to have an option to turn moving of polygons.

Happy to take a stab at opening a pull request

**Comment by calvinmetcalf** [comment]
the other option could be to split simple_select up based on whether anything is actually selected or not

**Comment by mcwhittemore** [comment]
Calvin,

Thanks for the request. Would transitioning into `direct_select` mode when a feature is selected work for you? Really all `simple_select` does is let you select multiple things, move and delete them. If you don't need to work with multiple features, then I'd say listening for [draw.selectionchange and maybe draw.modechange](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#events) and moving to `direct_select` with `draw.changeMode()` should work for you.

If this doesn't work, I'm not sure this is something we really want to add to this mode. Generally speaking, I think we want to keep the core modes as simple as possible and put new development towards [custom modes](https://github.com/mapbox/mapbox-gl-draw/issues/289).

**Comment by calvinmetcalf** [comment]
ok I'll give transitioning on select a try

**Comment by mcwhittemore** [comment]
👍

I'm going to close this issue for now. Please feel free to reopen if you think the feature is still needed. I'll probably make some comment about custom modes, but it would be good to know if transitioning doesn't work for you.

**Comment by bwyss** [comment]
I also have the case where I would like users to modify the geometry of a polygon, but I never want the polygon's position to change.

My solution is not great but it ensures that a polygon is never moved:

        map.on('draw.update', function (e) {
            if (e.action === 'move') {
                draw.deleteAll();
            }
        });

**Comment by fc** [comment]
This overrides the existing simple_select and direct_select modes to make the drag methods do nothing.  I'm sure a PR could be easily inspired by this.
```
const NewSimpleSelect = _.extend(modes.simple_select, {
  dragMove() {}
});

const NewDirectSelect = _.extend(modes.direct_select, {
  dragFeature() {}
});

const draw = new MapboxDraw({
  modes: {
    ...MapboxDraw.modes,
    simple_select: NewSimpleSelect,
    direct_select: NewDirectSelect
  }
});
```

**Comment by IsaacTrevino** [comment]
> This overrides the existing simple_select and direct_select modes to make the drag methods do nothing. I'm sure a PR could be easily inspired by this.
> 
> ```
> import _ from 'lodash';
> import MapboxDraw from '@mapbox/mapbox-gl-draw';
> 
> const NewSimpleSelect = _.extend(MapboxDraw.modes.simple_select, {
>   dragMove() {}
> });
> 
> const NewDirectSelect = _.extend(MapboxDraw.modes.direct_select, {
>   dragFeature() {}
> });
> 
> const draw = new MapboxDraw({
>   modes: {
>     ...MapboxDraw.modes,
>     simple_select: NewSimpleSelect,
>     direct_select: NewDirectSelect
>   }
> });
> ```

I believe they removed access to the mode libraries since. I don't believe this is no longer possible with the current version. `1.3.0`

**Comment by BooDeer** [comment]
> > This overrides the existing simple_select and direct_select modes to make the drag methods do nothing. I'm sure a PR could be easily inspired by this.
> > ```
> > import _ from 'lodash';
> > import MapboxDraw from '@mapbox/mapbox-gl-draw';
> > 
> > const NewSimpleSelect = _.extend(MapboxDraw.modes.simple_select, {
> >   dragMove() {}
> > });
> > 
> > const NewDirectSelect = _.extend(MapboxDraw.modes.direct_select, {
> >   dragFeature() {}
> > });
> > 
> > const draw = new MapboxDraw({
> >   modes: {
> >     ...MapboxDraw.modes,
> >     simple_select: NewSimpleSelect,
> >     direct_select: NewDirectSelect
> >   }
> > });
> > ```
> 
> I believe they removed access to the mode libraries since. I don't believe this is no longer possible with the current version. `1.3.0`

tested it right now, it works with the `1.4.1` version

**Comment by stevage** [comment]
This is really useful. I don't think you need lodash though. This seems to work fine:

```
import MapboxDraw from '@mapbox/mapbox-gl-draw'

const draw = new MapboxDraw({
  modes: {
    ...MapboxDraw.modes,
    simple_select: { ...MapboxDraw.modes.simple_select, dragMove() {} },
    direct_select: { ...MapboxDraw.modes.direct_select, dragFeature() {} },
  },
})
```

Or if you want just a bit more control over when dragging is initiated (for instance, with shift key), you can do something like this:


```
const NewDirectSelect = {
  ...MapboxDraw.modes.direct_select,
  onDrag(state, e) {
    if (state.selectedCoordPaths.length === 0 && !e.originalEvent?.shiftKey) {
      // require shift key in order to drag the whole shape around
      return
    }
    if (state.canDragMove !== true) return
    state.dragMoving = true
    e.originalEvent.stopPropagation()

    const delta = {
      lng: e.lngLat.lng - state.dragMoveLocation.lng,
      lat: e.lngLat.lat - state.dragMoveLocation.lat,
    }
    if (state.selectedCoordPaths.length > 0) this.dragVertex(state, e, delta)
    else {
      this.dragFeature(state, e, delta)
    }

    state.dragMoveLocation = e.lngLat
  },
}
```

**Comment by kavinda1995** [comment]
> This is really useful. I don't think you need lodash though. This seems to work fine:
> 
> ```
> import MapboxDraw from '@mapbox/mapbox-gl-draw'
> 
> const draw = new MapboxDraw({
>   modes: {
>     ...MapboxDraw.modes,
>     simple_select: { ...MapboxDraw.modes.simple_select, dragMove() {} },
>     direct_select: { ...MapboxDraw.modes.direct_select, dragFeature() {} },
>   },
> })
> ```
> 
> Or if you want just a bit more control over when dragging is initiated (for instance, with shift key), you can do something like this:
> 
> ```
> const NewDirectSelect = {
>   ...MapboxDraw.modes.direct_select,
>   onDrag(state, e) {
>     if (state.selectedCoordPaths.length === 0 && !e.originalEvent?.shiftKey) {
>       // require shift key in order to drag the whole shape around
>       return
>     }
>     if (state.canDragMove !== true) return
>     state.dragMoving = true
>     e.originalEvent.stopPropagation()
> 
>     const delta = {
>       lng: e.lngLat.lng - state.dragMoveLocation.lng,
>       lat: e.lngLat.lat - state.dragMoveLocation.lat,
>     }
>     if (state.selectedCoordPaths.length > 0) this.dragVertex(state, e, delta)
>     else {
>       this.dragFeature(state, e, delta)
>     }
> 
>     state.dragMoveLocation = e.lngLat
>   },
> }
> ```

This worked perfectly for me :). Thanks @stevage

**Comment by vcardins** [comment]
@stevage I tried your snippet however using typescript and for some reason I couldn't find out, the `this` object is always `undefined`. Any idea?
