### ISSUE TITLE
Add simple event listener examples to API.md

### ISSUE THREAD

**Issue by chriswhong** [mapbox/mapbox-gl-draw#669]
As a first-time user reading the docs, it was not clear to me how to implement an event listener.  I tried `draw.on('create')` before going back to read that they are namspaced as `draw.{event}` and are fired by the mapboxGL JS map object.

I think a simple snippet showing `map.on('draw.create', (d) => { ... });` would be helpful for noobs.  

Happy to PR this, just let me know if there is a preference for where it should go, format, etc.

**Comment by mcwhittemore** [comment]
@chriswhong - This is a great idea. Do you think we should have one for each event or a general example?

Either way, we'll want to add this in [this section of the docs](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#events) I think.

**Comment by andrewharvey** [comment]
I think one example at the top is fine like https://github.com/mapbox/mapbox-gl-draw/pull/670, but what do others think?

Others are also running into this, eg. https://gis.stackexchange.com/questions/244155/how-to-center-a-mapbox-gl-js-map-at-the-point-coordinates-from-a-point-edited-wi

I'd also like to incorporate events into https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/ so it updates the area automatically triggered by events.

**Comment by andrewharvey** [comment]
@chriswhong So sorry! I missed your last line:

> Happy to PR this, just let me know if there is a preference for where it should go, format, etc.

I should have left the PR for you!

**Comment by chriswhong** [comment]
No prob!  Just happy someone did it.
