### ISSUE TITLE
Possibly unintentional ES6 object literal shorthand

### ISSUE THREAD

**Issue by maxh** [mapbox/mapbox-gl-draw#681]
Our build pipeline choked on `{point}` here. At quick glance, it looks like the rest of the repo is ES5, so filing an issue to call it out in case it was unintentional.  Feel free to close if not an issue.  Thanks!

https://github.com/mapbox/mapbox-gl-draw/blob/master/src/api.js#L24

**Comment by mcwhittemore** [comment]
Yea, there has been a bit of history with newer ES features. If you want to make a PR that moves to ES5 I'm good with that.

**Comment by maxh** [comment]
We ended up sending this package through our transpilation step, so it's all good for us if it works for you. Thanks.
