### ISSUE TITLE
Limit the drawn features to 1

### ISSUE THREAD

**Issue by K1N5L4Y3R** [mapbox/mapbox-gl-draw#682]
I am trying to limit the features drawn to one, meaning that if the user wants to add a different polygon than the one already created, they need to delete it, or edit the existing one.
Is there a built in way to do this? I was thinking of removing the draw control and adding a new one with only the trash control visible, but when I do this I get the following exception:

```
map.removeControl(mapboxDraw)
var newMapboxDraw = new MapboxDraw({
  displayControlsDefault: false,
  controls: {
      trash: true
  }
})
map.addControl(newMapboxDraw)
```

```
mapbox-gl-draw.js:3 Uncaught TypeError: Cannot read property 'get' of null
    at t.exports.u.getFeature (mapbox-gl-draw.js:3)
    at mapbox-gl-draw.js:3
    at Array.filter (<anonymous>)
    at t.exports.l.onSetup (mapbox-gl-draw.js:3)
    at Object.start (mapbox-gl-draw.js:3)
    at o (mapbox-gl-draw.js:3)
    at Object.t [as changeMode] (mapbox-gl-draw.js:2)
    at t.exports.u.changeMode (mapbox-gl-draw.js:3)
    at t.exports.c.onKeyUp (mapbox-gl-draw.js:3)
    at Object.<anonymous> (mapbox-gl-draw.js:3)
```

**Comment by mcwhittemore** [comment]
> I was thinking of removing the draw control and adding a new one with only the trash control visible

Having a custom draw polygon control that deletes all features when it is clicked seems like a good way to achieve what you want.

> when I do this I get the following exception

The error message you are showing is definitely a bug, so we need to fix that. From looking at the error stack, I'm not sure why this is happening. Can you create a [jsfiddle](https://jsfiddle.net/) for it?

**Comment by K1N5L4Y3R** [comment]
@mcwhittemore sure, I can create it, however I'm on a really tight schedule, so I should be able to create it in the afternoon. Will update the issue when I do.

**Comment by K1N5L4Y3R** [comment]
Sorry for the delay, here is the [jsfiddle](https://jsfiddle.net/r8x87qb2/1/). To reproduce, draw a polygon and even though the draw controls *are* removed, the error that I mentioned appears in the console.

The new controls with only "trash" are added, but _presumably_ because of the mentioned error, the polygon no longer appears on the map

**Comment by mcwhittemore** [comment]
Looking at your fiddle, this behavior is expected. MapboxDraw does not share state between two different instances. If you want custom UI behavior, you should create your own UI elements rather then using the default ones Draw provides.

**Comment by K1N5L4Y3R** [comment]
Ok, in that case I'll just go with the following method for limiting the drawn polygons to one: [jsfiddle](https://jsfiddle.net/3fr728td/1/).

Whenever a feature is created or updated, all other existing features are deleted, which simply means that only one feature is visible at a time. This is good enough for my use case, and wanted to share it in case someone else needed something similar. Thanks for the support anyway.
