### ISSUE TITLE
map.doubleClickZoom.disable() re-enabled

### ISSUE THREAD

**Issue by mkozak0108** [mapbox/mapbox-gl-draw#691]
**mapbox-gl-js version**: 0.40.1
**mapbox-gl-draw version**: 1.0.0

### Steps to Trigger Behavior

 1. Call `map.doubleClickZoom.disable()`
 2. Double click on the map
 3. `map.doubleClickZoom.isEnabled()` returns `true`

### Expected Behavior
Zoom should be disabled
### Actual Behavior
Zoom is enabled

Link to JS Bin:
[https://jsbin.com/sikeyajoto/edit?html,output](https://jsbin.com/sikeyajoto/edit?html,output)
Don't forget to change token

**Comment by alexgleith** [comment]
I've encountered this issue just now too.

In my case, I create a map, then add draw tools layer and it seems to have enabled doubleClickZoom. When disabling draw tools (removing them) double click zoom is still enabled.

**Comment by mcwhittemore** [comment]
@alexgleith's PR to fix this has just merged and it available in 1.0.4 on npm.
