### ISSUE TITLE
Feature request: cancel selection change

### ISSUE THREAD

**Issue by IAfanasov** [mapbox/mapbox-gl-draw#692]
I had scenario with validation. User should choose the polygon and fill it's properties. Like name, year and etc. This properties should be validated. I want to disallow user to select other object or clear selection before she correct all validation issues.

**Comment by mcwhittemore** [comment]
So, the quick answer is to use the [draw.modechange](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md#drawmodechange) event revert back to the state you want the user to be in.

The long answer is that this might be a really good mode modifier function. With custom modes now live, one could write a module that wraps a mode in a validation check.

```js
var defaultDirectSelectMode = MapboxDraw.modes.directSelect;
var validator = require('mapbox-gl-draw-validate-features'); // what needs to be written
var validatorDirectSelectMode = validator(defaultDirectSelectMode, function(some, args) {
  return false; // stay in the same mode
  return true; // continue changing the mode
});
```

If this was written and published to npm, I'd love to put it in [the custom modes](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/MODES.md#available-custom-modes) docs

**Comment by kkaefer** [comment]
closing because this is not currently actionable
