### ISSUE TITLE
How to set colors based on feature properties for drawn items?

### ISSUE THREAD

**Issue by checkerap** [mapbox/mapbox-gl-draw#693]
I'm trying to set colors for feature polygons based on user input (clicking some swatches).

When clicking the red/green button I set a group property on the feature. In order to persist the property I found that I have to add it back to the map and it will get merged. Otherwise the property is lost when unselecting the polygon.

I want to display the selected color for the features with custom styles, but I might be doing something wrong.
I tried entering a filter entry based on the group property (see last 2 styles).

Please see bellow example:  
https://jsbin.com/soxekubako

**Comment by mcwhittemore** [comment]
I think you want to use [draw.setFeatureProperty](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md#setfeaturepropertyfeatureid-string-property-string-value-any-draw).

This will update the properties of your polygons as they are stored in Draw. Its good to note that Draw assumes that it is the primary manger for your features. If this is not the case, it supples `Draw.set()` to let you flush reset draw quickly.

**Comment by checkerap** [comment]
Thank you, it works better for setting the feature property.

For the colors and the filter I had to turn on the userProperties and use "user_group" instead of "group" in the filter. Seams to work for me, so I will close this.
