### ISSUE TITLE
draw a polygon without area throw an error and kills functioning of MapBoxDraw

### ISSUE THREAD

**Issue by IAfanasov** [mapbox/mapbox-gl-draw#695]
**mapbox-gl-js version**: v 1.6.5
**mapbox-gl-draw version**: v 1.0.0

### Steps to Trigger Behavior

 1. open https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/
 2. choose a polygon from palette 
 3. place a polygon like a line (see the screencast attached).

### Expected Behavior
same as pressing "esc" button on keyboard

### Actual Behavior
Js error thrown 
mapbox-gl-draw.js:4 Uncaught TypeError: Cannot read property 'toGeoJSON' of undefined
    at mapbox-gl-draw.js:4
    at Array.map (<anonymous>)
    at t.exports (mapbox-gl-draw.js:4)
    at t.exports.r [as render] (mapbox-gl-draw.js:3)
    at o (mapbox-gl-draw.js:3)

Selection of existing polygon don't work. Buttons in palette don't work ever.

**Comment by mcwhittemore** [comment]
I think this have been fixed in [v1.0.2](https://github.com/mapbox/mapbox-gl-draw/blob/master/CHANGELOG.md#102). Please confirm and close if it has been.
