### ISSUE TITLE
yarn build failed to minify the code

### ISSUE THREAD

**Issue by bibekdahal** [mapbox/mapbox-gl-draw#702]
When trying to build a react app with mapbox-gl-draw as its dependency, I got following error:

```
$ yarn build
yarn build v1.0.1
$ node scripts/build.js
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/@mapbox/mapbox-gl-draw/src/modes/index.js:10 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

As per [README of create-react-app](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify), it will be great if this package is available pre-compiled to ES5.

**mapbox-gl-js version**: 0.41.0
**mapbox-gl-draw version**: 1.0.3

### Steps to Trigger Behavior

 1. Create a react app using `create-react-app`: 
 2. Add the dependency: `yarn add @mapbox/mapbox-gl-draw`
 3. Try building the app: `yarn build`

**Comment by suyesh** [comment]
Any update on this?

**Comment by jmking** [comment]
I was able to overcome this by importing the dist version of mapbox-gl-draw directly i.e. `import MapboxDraw from '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.js'`

**Comment by mcwhittemore** [comment]
The dist version is the right way to require/import this if you need es5 support

**Comment by rorysedgwick** [comment]
This is causing an issue for me when importing the dist/ version and using `create-react-app`:

In `MapComponent.js`:
`import '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.css'`

```
$ npm run build

> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/@mapbox/mapbox-gl-draw/src/modes/index.js:10 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amundsen@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the amundsen@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rory.sedgwick/.npm/_logs/2017-12-05T14_51_38_755Z-debug.log
```

mapbox-gl version: **0.42.2**
mapbox-gl-draw version: **1.0.4**
