### ISSUE TITLE
Map box draw prevents disabling of zoom on double click

### ISSUE THREAD

**Issue by IAfanasov** [mapbox/mapbox-gl-draw#710]
Have a look in files below and you will easily find a problem: double click zoom firstly disabled and then enabled no matter if it was disabled before.

https://github.com/mapbox/mapbox-gl-draw/blob/066ab202a2132bb9c725607ad588f7068972b298/src/modes/simple_select.js
https://github.com/mapbox/mapbox-gl-draw/blob/066ab202a2132bb9c725607ad588f7068972b298/src/modes/simple_select.js
https://github.com/mapbox/mapbox-gl-draw/blob/c14acde0af91c236e4d67ac9ddb69df11c063fc2/src/modes/draw_line_string.js

**mapbox-gl-js version**: v0.39.1
**mapbox-gl-draw version**: v1.0.2
 
### Steps to Trigger Behavior

 1. initialise map and call `map.doubleClickZoom.disable();`
 2. double click on map

### Expected Behavior
map is not zoomed

### Actual Behavior
map is zoomed

**Comment by mcwhittemore** [comment]
Will be fixed by #696

**Comment by mcwhittemore** [comment]
This has been fixed and is in 1.0.4
