### ISSUE TITLE
Possible to removeLayers before addLayers

### ISSUE THREAD

**Issue by gpbmike** [mapbox/mapbox-gl-draw#721]
**mapbox-gl-js version**: v0.42.2
**mapbox-gl-draw version**: v1.0.4

### Steps to Trigger Behavior

 1. Add control.
 2. Remove control before map is loaded (before `control.addLayers` is called).

### Expected Behavior

Control should check for layers/sources before trying to remove them.

### Actual Behavior

Many errors are thrown related to missing layers/sources.

eg: `The layer 'gl-draw-polygon-fill-static.hot' does not exist in the map's style`

### Additional Details

Contrived CodePen example: https://codepen.io/gpbmike/pen/EbqNmp

My use case: User navigates to route with map then quickly navigates away before the map loads.

**Comment by mcwhittemore** [comment]
Hmmm... yea it looks like even `map.removeControl(Draw)` has to be called after `map.on('load', () => {})` has been triggered.

I'm guessing we just need some extra handling [here](https://github.com/mapbox/mapbox-gl-draw/blob/830b18236c2903231badfa9395f33371293ce711/src/setup.js#L11).

**Comment by gpbmike** [comment]
This looks like it was fixed sometime between v1.0.4 and v1.0.9. Perhaps by me? https://github.com/mapbox/mapbox-gl-draw/pull/685 😅
