### ISSUE TITLE
Unknown Layout Properties

### ISSUE THREAD

**Issue by kdedakia** [mapbox/mapbox-gl-draw#736]
**mapbox-gl-js version**: 1.0.2
**mapbox-gl-draw version**: 0.41.0

### Steps to Trigger Behavior

 1. Attempt to add "text-field", "icon-image" to layout properties in `theme.js`, as shown in [this mapbox example](https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/)
 2. Notice an error in the console: 'Error: layers.gl-draw-point-inactive.hot.layout.text-field: unknown property "text-field"'

### Expected Behavior
Ability to use all [layout properties that mapbox supports](https://www.mapbox.com/mapbox-gl-js/style-spec/#layer-layout)

**Comment by lbud** [comment]
Hey @kdedakia, [`gl-draw-point-inactive`](https://github.com/mapbox/mapbox-gl-draw/blob/de7b4a37efdd4ac11f912f5af8163ee223ecc0e5/src/lib/theme.js#L143-L155) is a `circle` layer, so it will only support [circle layout properties](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-circle). `text-field` and `icon-image` are layout properties specifically for symbol layers, so you'll only be able to use those to style symbol layers.

**Comment by kdedakia** [comment]
@lbud Thanks for the prompt reply. That makes sense, I will look into symbol layers.
