### ISSUE TITLE
draw.changeMode('direct_select', feature_id) not rerendering properly

### ISSUE THREAD

**Issue by mmoutenot** [mapbox/mapbox-gl-draw#738]
**mapbox-gl-js version**: 0.43.0
**mapbox-gl-draw version**: 1.0.4

### Steps to Trigger Behavior
`feature` is an immutable Map.

```
const draw = new MapboxDraw({
  displayControlsDefault: false,
  controls: {
    polygon: true,
  },
});
map.addControl(draw);`
draw.add(feature.toJS());
draw.changeMode('direct_select', {featureId: feature.get('id')});
```

Drag one of the feature's vertices.

### Expected Behavior

Allows editing of the polygon and when vertices are dragged it renders the updated geometry on each frame.

### Actual Behavior

Old frames are not cleaned up and the geometry is "smeared" across the movement path.

![example](https://media.giphy.com/media/3ohs4sbeo9T5qO2S2s/giphy.gif)

**Comment by george-silva** [comment]
seeing the same behavior here. same versions!

**Comment by OskarHeden** [comment]
We had the same problem with MultiPolygons but it turned out to be because our id was an int instead of a string, I don't know if this is relevant here though.

**Comment by mmoutenot** [comment]
! That solves it. @OskarHeden thank you.

So perhaps this should be a bug to properly handle integer ids, or to return an error when ids are integers.

**Comment by george-silva** [comment]
You mean the feature id?

**Comment by mcwhittemore** [comment]
Oh! Wow. That is most definitely a bug.

> If a Feature has a commonly used identifier, that identifier SHOULD be included as a member of the Feature object with the name "id", and the value of this member is either a JSON string or number.
