### ISSUE TITLE
Feature Request: Events for BoxSelect

### ISSUE THREAD

**Issue by benrudolph** [mapbox/mapbox-gl-draw#740]
I would love to use the Box Select to select other features on my map. Unfortunately I cannot do that right now as there are no hooks into events when a user starts a Box selections (that I know of).

Would something like the following make sense?

```
map.on('boxSelect.start')
map.on('boxSelect.change')
map.on('boxSelect.end')
```

**Comment by benrudolph** [comment]
This is possible to do already by overriding with your own mode. Very cool!

**Comment by mcwhittemore** [comment]
@benrudolph - if you can share how you do this that would be great. More custom mode over ride examples would be great!

**Comment by benrudolph** [comment]
Honestly it was super hacky and I just did it by looking at the simple_mode code:

```
import MapboxDraw from '@mapbox/mapbox-gl-draw';


const SimpleSelectExtended = {}

Object.assign(SimpleSelectExtended, MapboxDraw.modes.simple_select)

SimpleSelectExtended.onMouseUp = function(state, e) {
  if (state.boxSelecting) {
    // boxSelectStartLocation is stored as an XY coordinate
    const startLngLat = this.map.unproject(state.boxSelectStartLocation);
    const endLngLat = e.lngLat
    this.map.fire('boxSelect.done', {
      start: startLngLat,
      end: endLngLat,
    })
  }

  return this.stopExtendedInteractions(state);
};

export default SimpleSelectExtended;
```
