### ISSUE TITLE
draw.add(feature) throws "Cannot read property 'get' of undefined"

### ISSUE THREAD

**Issue by thekip** [mapbox/mapbox-gl-draw#742]
**mapbox-gl-js version**: v0.43.0
**mapbox-gl-draw version**:  v1.0.4

A lso tried with older versions of mapbox-gl-js, and with versions from package.json restricted range
### Steps to Trigger Behavior
```js
draw.add({ type: 'Point', coordinates: [0, 0] })
```

This code (and other valid features) throws an error "Cannot read property 'get' of undefined"

Fiddle to reproduce https://jsfiddle.net/thekip/8p8xqpjc/33/

**Comment by thekip** [comment]
My Fault, all interaction with should be done after map load

**Comment by yonderTech** [comment]
> My Fault, all interaction with should be done after map load

I do that in the 'load' callback and get the same error.
