### ISSUE TITLE
Wiring to a different canvas

### ISSUE THREAD

**Issue by Warkst** [mapbox/mapbox-gl-draw#743]
Hi everyone,

I would like to know a little more about how mapbox-gl-draw works but I'm not very experienced at javascript and I can't figure it out from the code. I'm guessing the draw controls work with the `canvas` element introduced by mapbox-gl, `.mapboxgl-canvas`. If so, is it possible at all to wire the controls to a different canvas? I would like to draw and listen to pointer events on a different canvas (an overlay over the mapbox canvas, to be honest, created by deck.gl).

**Comment by mcwhittemore** [comment]
@Warkst - Draw manages a few GeoJSON source layers in a mapbox-gl-js map. mapbox-gl-js manages rendering those source layers onto the canvas so Draw has no direct connection to the canvas element.

If deck.gl exposes the mapbox-gl-js instance it creates, you could use that to replace the `map` in [this example](https://github.com/mapbox/mapbox-gl-draw#usage-in-your-application).

I hope that helps! For questions about how to get the map instance out of deck.gl, please reach out to the developers of that module.

**Comment by Warkst** [comment]
Hi @mcwhittemore and thanks for explaining this. Deck does indeed expose the underlying map instance and I can successfully add Draw to that instance. However, deck also creates an extra canvas positioned on top of the mapbox canvas in which it renders its own layers. This canvas is blocking the pointer events from reaching the mapbox canvas, preventing Draw from functioning. Disabling pointer-events on the deck canvas allows Draw to function properly, but the shapes that are drawn on the mapbox canvas are invisble because they end up behind the deck layers. I was hoping to be able to rewire the controls so they interact with the deck canvas instead, but I understand that it's more complicated than that. I'll keep looking for another solution :)

**Comment by lrgalego** [comment]
@DeMol-EE a couple years have passed, and I'm having the same issue you were, how did you end up solving this? Thanks!

**Comment by lrgalego** [comment]
If anyone lands on this issue in a couple of years from now (like I did). I found a workaround that with the current versions is working just fine.
All you need to do is to avoid the canvas from deck.gl to receive the events from the mouse, when the drawing mode is enabled. and reenable those events on the the drawing is complete.

Example:

```
document.querySelector('#map canvas:not(.mapboxgl-canvas)').style.pointerEvents = "none";
draw.changeMode('draw_polygon')


  map.on('draw.create', function (e) {
    document.querySelector('#map canvas:not(.mapboxgl-canvas)').style.pointerEvents = "unset";
  });
```
