### ISSUE TITLE
Annotations doesn't show on map after removing and adding a new draw instance to map.

### ISSUE THREAD

**Issue by jithintomz** [mapbox/mapbox-gl-draw#745]
mapbox-gl-js version : 0.44.1
mapbox-gl-draw version :1.0.4

### Steps to Trigger Behavior

 1.Remove existing draw instance.
 2.Add a new draw instance to the map.
 3.Add a  feature to the draw.

The added feature won't show until user interacts with draw.

https://codepen.io/jithintom/pen/WMMEPj

**Comment by mcwhittemore** [comment]
Closed by #749
