### ISSUE TITLE
Disabling dragging/moving of drawn features

### ISSUE THREAD

**Issue by nigelsim** [mapbox/mapbox-gl-draw#753]
When drawing a feature it is possible to drag and move the entire feature. This is confusing to users as they expect to be dragging the map, so we want to be able to disable this functionality.

**mapbox-gl-js version 0.44.1**:
**mapbox-gl-draw version 1.0.4**:

### Steps to Trigger Behavior

 1. Draw a polygon
 2. Click on the polygon
 3. When hovering over the polygon the cursor becomes a 'move' icon
 4. Clicking and dragging moves the polygon

### Expected Behavior

No move cursor and polygon not moved.

### Actual Behavior

Cursor changes and polygon is movable.

**Comment by mcwhittemore** [comment]
This is expected behavior of how mapbox-gl-draw works. For custom interactions please see [Custom Modes](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/MODES.md#writing-custom-modes).

**Comment by clementmas** [comment]
Can anyone provide an example of how to do this with a Custom Mode? Thanks :)

**Comment by scooterGrun** [comment]
Have a look at https://github.com/mapbox/mapbox-gl-draw-static-mode

**Comment by stevage** [comment]
See also solution at https://github.com/mapbox/mapbox-gl-draw/issues/667#issuecomment-1707799304

**Comment by vcardins** [comment]
Although It's an old thread but it's exactly the problem I'm facing. How could I still drag the map without dragging/moving the feature?
I came across a solution that uses `map.panTo(e.lngLat);` however the transition is awkward. Ideas?

![2023-12-11 17 55 57](https://github.com/mapbox/mapbox-gl-draw/assets/2383329/a426c06a-e5b4-4a90-a889-ff145490441d)
