### ISSUE TITLE
Double Clicking while Drawing a Polygon results in nothing

### ISSUE THREAD

**Issue by milafrerichs** [mapbox/mapbox-gl-draw#756]
Hi, thanks for all the hard work on Mapbox-gl-draw.

I got one weird bug/behaviour:
 
When I'm in draw mode (polygon_draw) for example and I double click on the map nothing is done and I'm in simple_select again. 

**mapbox-gl-js version**: 0.44.1
**mapbox-gl-draw version**: 1.0.4

### Steps to Trigger Behavior

 1. Start drawing
 2. Double-click on the same location
 3. Try to draw again

### Expected Behavior
Start drawing with the point where the double click occurred. 
At least be in `polygon_draw` mode again so I can try to click again. 

### Actual Behavior
Nothing is done and I'm in simple_select mode

### Why does this happen?
The first clicks adds a vertex to the map via `DrawPolygon.clickAnywhere` and the polygon has one coordinate.  
The second click triggers `DrawPolygon.clickOnVertex` since you clicked on a vertex.   
This changes the mode to simple_select and calls `DrawPolygon.onStop`  
which removes the last coordinate (the only one availabe)   
`state.polygon.removeCoordinate(`0.${state.currentVertexPosition}`);` and the polygon is invalid and   
`this.deleteFeature([state.polygon.id], { silent: true });`
`this.changeMode(Constants.modes.SIMPLE_SELECT, {}, { silent: true });`
removes the polygon.

**Comment by mcwhittemore** [comment]
@milafrerichs - is the thought here that the user didn't really mean to double click? Double clicking on a node in an invalid polygon should kick you out of draw_polygon and back into simple_select so the interaction you're seeing is expected.

**Comment by milafrerichs** [comment]
yes, the idea is that the user did not intend it because he did not realize he was actually drawing. 
and another thing that I encountered is around the same issue, if you click on a vertex again while your Polygon is not complete yet (fewer than three unique points) it will kick you out as well and remove the drawing. 
I would think it would be nicer to stay in the mode and just ignore it or what is the idea around going into `simple_select`? 
thanks.

**Comment by mcwhittemore** [comment]
@milafrerichs - these are all great points and I think the answer is that different applications want different defaults when drawing. This is why Draw supports and promotes custom modes. I'm more than happy to list alt to the shipped modes if you want to fork those and package them up. I think that would be a great thing for the community. But having how Draw works by default is a breaking change we're not going to make as other application expect Draw to work as it does today.

I'm going to close this issue for tidiness sake. Please feel free to reopen if having a place to talk about what this custom modes might look like is helpful for you.

Thanks!

**Comment by shivalika-techp** [comment]
Hi @mcwhittemore  @milafrerichs 

I am trying to find a workaround for the same issue where the user **accidentally double-clicks** when they start drawing a polygon.
This removes the first (and only) polygon point and confuses the user about whether the drawing mode has been initialized.

Is there a solution you would like to recommend to keep the draw tool in the `draw_polygon` mode even if the user has clicked on the same vertex again? Can I use any event method to notify me when this case occurs?

Thanks for the help!
