### ISSUE TITLE
onClick event not firing for custom modes

### ISSUE THREAD

**Issue by benkearney** [mapbox/mapbox-gl-draw#758]
Hi,

I'm trying to set up the example custom mode 'LotsOfPointsMode' and cannot get click events to register. Both the onSetup and onKeyUp events are working as expected, So I am sure that the mode is correctly loaded into the draw object.

My lotsOfPointsMode.js is as follows:

```
var LotsOfPointsMode = {};

LotsOfPointsMode.onSetup = function(opts) {
    console.log("Lots of points mode setup")
  var state = {};
  state.count = opts.count || 0;
  return state;
};

LotsOfPointsMode.onClick = function(state, e) {
    console.log("ON CLICK")
};

LotsOfPointsMode.onKeyUp = function(state, e) {
    console.log("on key up")
  if (e.keyCode === 27) return this.changeMode('simple_select');
};

LotsOfPointsMode.toDisplayFeatures = function(state, geojson, display) {
  display(geojson);
};

export default LotsOfPointsMode
```

I am adding the mode to draw like this:

```
var modes = MapboxDraw.modes;
modes.lots_of_points = LotsOfPointsMode
this.draw = new MapboxDraw({'modes': modes});
map.addControl(this.draw);
```

"mapbox-gl": "^0.44.1"
"@mapbox/mapbox-gl-draw": "^1.0.6",

I noticed that in another issue there were some compatibility issues with mapbox-gl > 0.41.0, so I tried downgrading to 0.41.0, but the problem remained the same. 

Has there been a change to the onClick event? The prototype is till in mode_interface.js, so I feel like it can't be that. 

I'm using mapbox_gl_vue if that matters. I tried removing all the click listeners in case that was affecting it, but it didn't make a difference.

This has to be something really basic, right? It doesn't make sense that onClick isn't at least triggering when onSetup and onKeyUp are both working.

**Comment by benkearney** [comment]
I've just checked each of the other modes and an odd combination of them are working/not working:

Working:
- onSetup
- onMouseOut
- onKeyUp
- onKeyDown
- onStop
- onTrash
- onMouseOut

Not working:
- onClick
- onTap
- onDrag
- onMouseMove
- onMouseOut
- onCombineFeature (error message)
- onUncombineFeature (error message)

I was prepared to say that none of the mouse related events were available to the draw object, but it looks like onMouseOut events are registering. Pretty stumped here.

**Comment by mcwhittemore** [comment]
@benkearney - My guess is that this is a problem with `mapbox-gl-vue`. Can you try with mapbox-gl-js and see if you have the same error. All modes (custom and default) are treated the same and the above events are working for in gl-js for me so, again, I'm pretty sure this is a problem with `mapbox-gl-vue`.
