### ISSUE TITLE
Editing a polygon that has been added to map with draw.add has some odd lagging behaviour.

### ISSUE THREAD

**Issue by jackwkinsey** [mapbox/mapbox-gl-draw#777]
I've encountered some strange behaviour with editing a polygon. It seems to be tied to having the draw mode "initialized" with "draw.add". When you try to edit the polygon and drag a vertex, it is never "cleared" from the frame and is layered on the last frame so you see bunch of vertices layered while dragging around.

[Dragging a vertex](http://res.cloudinary.com/exaptive/image/upload/c_fill,h_300,w_300/yti0fkdfjj3lzm0nilnw.png)

**mapbox-gl-js version**: 0.44.2
**mapbox-gl-draw version**: 1.0.4

### Steps to Trigger Behavior
 1. Navigate to https://codepen.io/jackwkinsey/pen/odoJJV?editors=0010
 2. Enter your Mapbox API Access Token at the top to make the code run.
 3. You should see polygons for Brazil.
 4. Double click on one of the polygons to allow it to be edited.
 5. Drag one of the vertices.

 OR

  Steps 1-3: Same as above.
  4. Click on the "Create Polygon" button in the top-right corner.
  5. Draw a new polygon, this is added to the Brazil set of polygons.
  6. Double click on your new polygon to allow it to edited.
  7. Drag one of the vertices.

### Expected Behavior
The polygon should be able to be edited freely and smoothly.

### Actual Behavior
The vertices and the polygon are never "redrawn" and "cleared" so you see a jagged bunch of vertices bunch up until you release and click off of the polygon.

**Comment by mcwhittemore** [comment]
Thanks for the issue @jackwkinsey. The problem here is that Draw does not correctly support numeric ids. If you can confirm https://github.com/mapbox/mapbox-gl-draw/pull/769 fixes your problem, I can merge that PR and get this out the door.

**Comment by jackwkinsey** [comment]
I mentioned this on the other thread that you linked to, but yes it looks like this fix will solve my issue as well.

We were using the CDN version of mapbox and mapbox draw. Any idea on how long this fix would take to get into CDN?
