### ISSUE TITLE
mapboxgl Expression not working in style of mapbox-draw

### ISSUE THREAD

**Issue by curvenut** [mapbox/mapbox-gl-draw#789]
**mapbox-gl-js version**:  0.45
**mapbox-gl-draw version**: 1.0.9

### Steps to Trigger Behavior

Edit  2018-05-24:   here the JSBIN  for illustration  :  https://jsbin.com/lojuwak/edit?html,output

 1.  In the style of mapboxDraw, I  add alayer that had       
expression on the circle-color in order to have different color  depending if 
the attributes in the properties exist 

  
    var colorExpressionPoint = ['case',
        ["==", ['get', 'isProcessed'], true ], '#214AED',
        ["==", ['get', 'isProcessed'], false], '#40CC16',
        '#FF0000'
    ]

    var paintPropertyPoint = {};
    paintPropertyPoint['circle-radius'] = 12;
    paintPropertyPoint['circle-blur'] = 0.5;
    paintPropertyPoint['circle-color'] = colorExpressionPoint;
      
      
      

    var mapboxDrawStylesCustom = [
        {
          'id': 'custom-point-inactive',
          'type': 'circle',
          'filter': ['all',
            ['==', 'active', 'false'],
            ['==', '$type', 'Point'],
            ['==', 'meta', 'feature'],
            ['!=', 'mode', 'static']
          ],
          'paint': paintPropertyPoint
        },

        {
          'id': 'custom-point-active',
          'type': 'circle',
          'filter': ['all',
            ['==', '$type', 'Point'],
            ['!=', 'meta', 'midpoint'],
            ['==', 'active', 'true']],
          'paint': {
            'circle-radius': 12,
            'circle-blur': 0.5,
            'circle-color': '#fbb03b'
          }
        },
        {
          'id': 'custom-point-static',
          'type': 'circle',
          'filter': ['all', ['==', 'mode', 'static'], ['==', '$type', 'Point']],
          'paint': {
            'circle-radius': 5,
            'circle-color': '#404040'
          }
        }
      ];   

 2.   the geojson file of feature collection 

     {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {"isProcessed": true},
          "geometry": {
            "type": "Point",
            "coordinates": [
              -101.92565917968749,
              48.79239019646406
            ]
          }
        },
        {
          "type": "Feature",
          "properties": {"isProcessed": false},
          "geometry": {
            "type": "Point",
            "coordinates": [
              -100.953369140625,
              48.785151998043155
            ]
          }
        },
        {
          "type": "Feature",
          "properties": {},
          "geometry": {
            "type": "Point",
            "coordinates": [
              -100.887451171875,
              48.5275192374508
            ]
          }
        },
        {
          "type": "Feature",
          "properties": {},
          "geometry": {
            "type": "Point",
            "coordinates": [
              -101.832275390625,
              48.4765629664158
            ]
          }
        }
      ]
    }

### Expected Behavior
2 points in RED and  1 point in GREEN,  1 point in  blue
### Actual Behavior
4 point un RED

**Comment by stdob** [comment]
> If opts.userProperties is set to true the properties of a feature will also be available for styling. All user properties are prefixed with user_ to make sure they do not clash with the Draw properties.

https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md#styling-draw

So you need to add a `user_` prefix to the property in styles:

```
var colorExpressionPoint = ['case',
    ["==", ['get', 'user_isProcessed'], true ], '#214AED',
    ["==", ['get', 'user_isProcessed'], false], '#40CC16',
    '#FF0000'
]
```

**Comment by mcwhittemore** [comment]
Thanks for clarifying this @stdob, I hope that helps @curvenut.

**Comment by curvenut** [comment]
Thanks indeed it works now, with the property prefix with  user_    in the filter.
It iwas not obvious that the user had to do it !

**Comment by mcwhittemore** [comment]
I'm happy to accept a docs PR if you have thoughts on how to make this clearer. I'm happy the clarification helped.

**Comment by jayarjo** [comment]
@curvenut @mcwhittemore what that dollar sign syntax (e.g. `$type`)? I've not seen it anywhere in the docs. Can one access geometry properties, like coordinates like this as well?
