### ISSUE TITLE
Enable Draw control programmatically

### ISSUE THREAD

**Issue by adam3039** [mapbox/mapbox-gl-draw#794]
I am able to get the basic example up and running, and this package does everything I need. However, I am having trouble figuring out how to activate the draw functionality programatically. For example, my application has some panel overlays, and as part of a form I'd like to activate the draw ability by clicking a custom button, not the control button that shows on the map. Ideally I'd like to keep the map control button hidden (which I can do).

I've scoured the documentation with no luck. Anyone have any insight?

**Comment by samanpwbb** [comment]
Check out the changeMode method to programmatically enter a drawing mode: https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md#changemodemode-string-options-object-draw

**Comment by adam3039** [comment]
Thank you Saman. I had assumed changeMode meant that once draw was enabled you could switch between modes that way. Had no idea it enabled the draw as well. 

Cheers

**Comment by Rebeccau** [comment]
Hi, I am also trying to enable draw programmatically. After I do addControl to the map I change the mode to draw_polygon but it still requires the user to actually click on the control to start drawing. I want to hide the control and the user to immediately start drawing, is that possible? Thanks
