### ISSUE TITLE
sprite not working 

### ISSUE THREAD

**Issue by inttyl** [mapbox/mapbox-gl-draw#796]
**mapbox-gl-js version**:  0.45.0
**mapbox-gl-draw version**: 1.0.9

### Steps to Trigger Behavior

 1.   I create a sprite in the style file of the map , when creating the map.
`....`
`"sprite": "assets/mapbox/sprites/sprites-test",`
`....`

sprite-test@2.json
`{
    "test-1": {
        "width": 32,
        "height": 32,
        "x": 0,
        "y": 0,
        "pixelRatio": 1
    }
}`

 2.In the style of the  draw , I have the following layer ,   i make a reference to the marker  , test-1

`{`
`      'id': 'test-layer',`
`      'type': 'circle',`
`      'filter':`
`        ['all',`
`        ['==', 'active', 'false'],`
`        ['==', '$type', 'Point'],`
`        ['==', 'meta', 'feature'],`
`        ['!=', 'mode', 'static'],`
`      ],`
`      "layout": {`
`        "icon-image": "test-1",`
`      },`
`    }`

 3.

### Expected Behavior
See a marker with the associate image 

### Actual Behavior
Instead I got an error when the map is load : 
`Error: layers.consent-marker-inactive.hot.layout.icon-image: unknown property "icon-image"`

Any help is appreciated !

**Comment by lbud** [comment]
Hi @inttyl, if you want to use an icon you'll need to use a layer of type `symbol` rather than of type `circle`. You can see all symbol layer-specific properties [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol).
