### ISSUE TITLE
How to get all new point coodinates after move?

### ISSUE THREAD

**Issue by benderlidze** [mapbox/mapbox-gl-draw#803]
I draw a line select it and move it to new position or move one point of the line. I need to update the tooltip coordinates - move them to a new line(point) position. So I need to know the old coodinate and update it with a new one. How to get new and old coordinates of the point or all points of the line?

I am trying to use

map.on('draw.selectionchange', update);
map.on('draw.update', update);

but no event is fired when I move the whole line.
Thanks

**Comment by woodpav** [comment]
`map.on('draw.update', update);` is what you want. You need to store the old feature elsewhere as `draw.update` only returns the updated feature.

    update(evt) {
      let feature = evt.features[0];
      console.log(feature)
    }
