### ISSUE TITLE
How to dynamically set a color for a polygon using a color picker

### ISSUE THREAD

**Issue by TebogoT** [mapbox/mapbox-gl-draw#804]
**mapbox-gl-js version**:
**mapbox-gl-draw version**:

### Steps to Trigger Behavior

 1.Draw a polygon using mapbox gl draw
 2.Use color picker to choose a color for the polygon
 3.Display the color as the user chooses the color for the current drawn polygon

### Expected Behavior
Have options for a user to choose a color for a polygon
### Actual Behavior
I am using react with mapbox gl js and mapbox gl draw with turf and I'm trying to set a color property for a drawn polygon based on a user selection but from the examples I've seen, you have to specify a fill color property which is not what I'm looking for because the fill color property of the polygon has to be set based on what a user selects from a color picker. Is there anyway to do this?

**Comment by TebogoT** [comment]
@det-jscott116 Thank you, is it possible for you to show me a full working example?

**Comment by det-jscott116** [comment]
@TebogoT 

Some mistakes and bad advice in the response above (I was mostly going off the top of my head :/). But nevertheless, here is a working example:

https://jsfiddle.net/rosLzqec/49/

Things to note:

- I missed this in my explanation above, you will need to set the ``userProperties`` property to ``true`` when creating the MapboxDraw object:

```
var draw = new MapboxDraw({
  ...,
  userProperties: true,
  ...
}
```

- A mistake in my explanation above. For any "paint" properties in the style definition you can have to access any user defined properties as such:
```
var drawStyles = [{
  ...,
  'paint': {
    'fill-color': {
      'type': 'identity',
      'property': 'user_myFillColorProperty'
    },
    ....
}];
```
For any "layout" properties, my example was correct:
```
var drawStyles = [{
  ...,
  'layout': {
    'icon-image': '{user_myIconImageProperty}',
    ...
  },
  ...
}];
```

**Comment by TebogoT** [comment]
@det-jscott116 It is exactly what I was looking for  👍 thanks a lot, how would I go about implementing it in ReactJS?

**Comment by det-jscott116** [comment]
@TebogoT Glad to help. Unfortunately I am more of an Angular guy, so can't really help you in that regard. Best of luck!

**Comment by TebogoT** [comment]
@det-jscott116 is it okay for us to keep in touch if so may I have your email

**Comment by det-jscott116** [comment]
@TebogoT hey no worries, feel free to email me at: j_a_c_k_n_k_a_n_d_y_@_g_m_a_i_l_._c_o_m (remove all underscores) i'll do my best to help if i can

**Comment by selenecodes** [comment]
I have made a mockup of how one can change colors based on a color picker on: https://observablehq.com/@selenecodes/mapbox-gl-colorpicker
