### ISSUE TITLE
 Is it possible to add a listener to MapboxDraw figure?

### ISSUE THREAD

**Issue by MariyaDutkina** [mapbox/mapbox-gl-draw#809]
Hello! 
Is it possible to add a listener  (for example 'click') to MapboxDraw figure? (sorry for my English)

Example: 
```
mapboxgl.accessToken = 'YOUR_ACCESS_TOKEN';

var map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/mapbox/streets-v8',
  center: [40, -74.50],
  zoom: 9
});

var Draw = new MapboxDraw();
map.addControl(Draw, 'top-left');

const geoJSON = {
      'type': 'FeatureCollection',
      'features': [{
        'type': 'Feature',
        'properties': {
        },
        'geometry': {
          'type': 'Polygon',
          'coordinates': [
            ...
          ]
        }
      },
      ]
    };

map.on('load', (e) => {
  Draw.add(geoJSON) // listener (for example 'click') for  polygon with these geoJSON data <===
});

```

**Comment by mcwhittemore** [comment]
You should be able to use the [`draw.selectionchange`](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md#drawselectionchange) event do create an onClick handler.

I hope that helps.

**Comment by MariyaDutkina** [comment]
@mcwhittemore Thank you!
Please, answer another question: how to create hover listener for MapboxDraw?

**Comment by mcwhittemore** [comment]
I don't know if there is a way to do this currently. We could find a way to expose it. If you are interested in outlining what the feature would look like please open a new ticket for that single event.

**Comment by MariyaDutkina** [comment]
@mcwhittemore Ok, Thank you!
