### ISSUE TITLE
Placing Icon at the corner/vertex of a polygon

### ISSUE THREAD

**Issue by adi-darachi** [mapbox/mapbox-gl-draw#819]
I'm trying the place an icon at the top most corder of a polygon.
So far, I managed to place an icon at the center of the polygon, also, I've found that an icon position can be adjusted using the 'paint.icon-translate' property.

What I could not do, is to set provide the  'paint.icon-translate' property with dynamic data driven from the position of the polygon.

EDIT: a walk-around that might work, dynamically updating the icon position using the 'draw.update' event?

It's less then an issue, I've tried for several days, and it appears to be impossible.
I just wanna make sure i'm not missing anything, and your opinion regarding the scenario i'm facing.

Thanks in advance.
'

**Comment by mcwhittemore** [comment]
@adi-darachi - the only option I could see for this to work is to use the GeoJSON points that represent handles when editing the polygon. This won't work when the polygon isn't being edited. A custom mode could be based of of simple_select to change that if getting this to work when editing works.

Another option would be to add your own GeoJSON to the map but that is a bit weird and I'm not sure how well Draw handles having two instances running to help make it easier.

Closing as this is a support ticket.
