### ISSUE TITLE
problem-plug-in

### ISSUE THREAD

**Issue by Niumeng1** [mapbox/mapbox-gl-draw#821]
I took a picture on the map, then executed the plug-in, and found that the graphics generated by the plug-in were below the already painted surface.
![image](https://user-images.githubusercontent.com/21193895/45815011-0241f600-bd0a-11e8-9854-cc871fbd14b2.png)
![image](https://user-images.githubusercontent.com/21193895/45815078-387f7580-bd0a-11e8-8c92-7817a06fb5bb.png)

thanks.
snowflake

**Comment by Niumeng1** [comment]
How to set the highest level of polygon drawing ？

**Comment by andrewharvey** [comment]
When you add the MapboxDraw control to the map it will insert the Draw layers as the top layer at that instant.

After this if you add more layers to your map you'll need to ensure they are inserted below (after) the Draw layers see https://www.mapbox.com/mapbox-gl-js/api/#map#addlayer, whether that means going through the map style and finding the bottom gl-draw layer (`map.getStyle().layers`) or finding the top layer of your style, it's up to you.

![layers](https://user-images.githubusercontent.com/117278/45992275-3b90b200-c0cc-11e8-9bcd-e480ac2d7506.png)
