### ISSUE TITLE
0.49 mapbox-gl support

### ISSUE THREAD

**Issue by dendrei** [mapbox/mapbox-gl-draw#827]
The supported peer dependency and dev dependency of `mapbox-gl` (in the `package.json`) is up to version `0.45` (i.e. four versions behind the current `mapbox-gl` release).

I am just wondering if there are any known issues with upgrading these dependencies to the current `0.49` release of `mapbox-gl`? Also, are there any plans to do so in the near term?

I've noticed that there is a relevant branch, `greenkeeper/mapbox-gl-0.49.0`, but the greenskeeper bot only updated the dev dependency and didn't change the peer dependency.

Thanks for the great work!

**Comment by curvenut** [comment]
I d like to known that too
