### ISSUE TITLE
Mapbox Draw Toolbox Javascript in Android Studio - Blank Page

### ISSUE THREAD

**Issue by AdinhLux** [mapbox/mapbox-gl-draw#828]
Hi,

Trying to create an Android App to Draw Polygon on Mapbox, **I don't find any examples with java code**. So I decided to create a Webview in Android Studio to use javascript files ( [https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/) ).

### Steps to Trigger Behavior

 1. I created an 'Assets' folder + 'www' folder
 2. I created an 'MapBoxPolygon'.html where I copied-pasted the code
 3. I tried to run the App but I got a blank screen

![capture](https://user-images.githubusercontent.com/43099257/47153267-69d66b80-d2df-11e8-9d0d-935dc5a6ab7a.PNG)
![capture2](https://user-images.githubusercontent.com/43099257/47153309-84104980-d2df-11e8-8c75-96571ba573f1.PNG)

### Expected Behavior

- Displaying the Map on a WebView ( on an Android Device )
- Using Mapbox Draw Toolbox to draw some polygons

 
### Actual Behavior

- Draw Toolbox and Map don't display

**Comment by fc** [comment]
Is the problem even with mapbox-gl-draw?  Why not just try to get it working mapbox-gl itself first. 
 It's likely there are JS errors and once you find out where those are you'll probably figure out what is happening.

**Comment by kkaefer** [comment]
not actionable
