### ISSUE TITLE
feature request: setSelectedIds API

### ISSUE THREAD

**Issue by tibotiber** [mapbox/mapbox-gl-draw#836]
Hi, thanks for the work on mapbox draw, it's pretty amazing.

I have a use-case where I keep the features on the map in sync with a table component via app state. I would like to keep the features selection synced as well. I can listen to `draw.selectionchange` to sync changes from the map to state, but there doesn't seem to be a way to programmatically set the selected features to sync state changes to the map.

What are your thoughts on adding `draw.setSelectedIds()` to the API?

Thanks.

**Comment by mcwhittemore** [comment]
Cool. Happy it helped. Not requiring modes to have a concept of selection is something I regret a bit. I'm not sure how we would have handled the draw modes with that constraint, but it means that all the work to allow devs to control what is being worked on (which is kinda the point of Draw...) feels like an after on hack.

Closing for now. Hope to reopen some time in the future.

**Comment by cpuy2020** [comment]
Any updates?
