### ISSUE TITLE
Typescript type declarations?

### ISSUE THREAD

**Issue by maxburke** [mapbox/mapbox-gl-draw#842]
Are there plans in the near future for supplying a Typescript type declarations file? 

(Presently using mapbox-gl-draw 1.0.9)

**Comment by vanhumbeecka** [comment]
While awaiting the official typescript declaration files, I've written the basics manually, based on the readme from this repo. Use with care. This can still contain mistakes:
```
declare module '@mapbox/mapbox-gl-draw' {
  import {Feature, FeatureCollection} from 'geojson'
  import IMapboxDrawControls = MapboxDraw.IMapboxDrawControls

  class MapboxDraw {
    constructor(options?: {
      displayControlsDefault?: boolean,
      keybindings?: boolean,
      touchEnabled?: boolean,
      boxSelect?: boolean,
      clickBuffer?: number,
      touchBuffer?: number,
      controls?: IMapboxDrawControls,
      styles?: object[],
      modes?: object,
      defaultMode?: string,
      userProperties?: boolean
    });

    public add(geojson: object): string[]

    public get(featureId: string): Feature | undefined

    public getFeatureIdsAt(point: { x: number, y: number }): string[]

    public getSelectedIds(): string[]

    public getSelected(): FeatureCollection

    public getSelectedPoints(): FeatureCollection

    public getAll(): FeatureCollection

    public delete(ids: string | string[]): this

    public deleteAll(): this

    public set(featureCollection: FeatureCollection): string[]

    public trash(): this

    public combineFeatures(): this

    public uncombineFeatures(): this

    public getMode(): string

    public changeMode(mode: string, options?: object): this

    public setFeatureProperty(featureId: string, property: string, value: any): this

  }

  export = MapboxDraw
}

declare namespace MapboxDraw {
  export interface IMapboxDrawControls {
    point?: boolean,
    line_string?: boolean,
    polygon?: boolean
    trash?: boolean,
    combine_features?: boolean,
    uncombine_features?: boolean
  }
}
```

**Comment by amaurymartiny** [comment]
@vanhumbeecka To get more visibility I think you can create a PR to create an `index.d.ts` file with these typings, it's already a start.

**Comment by vanhumbeecka** [comment]
@amaurymartiny done!

**Comment by Tyler-V** [comment]
Why hasn't this been merged in yet?

**Comment by maxburke** [comment]
@amaurymartiny is it possible to merge the change from @vanhumbeecka ?

**Comment by maxburke** [comment]
(Failing that, is there an update about when the official type declarations will be available?)

**Comment by amaurymartiny** [comment]
@maxburke I'm not part of this project, I can't do anything.

But see https://github.com/mapbox/mapbox-gl-draw/pull/877#issuecomment-519224456, I believe it won't be merged here

**Comment by kkaefer** [comment]
Yep, DefinitelyTyped is the where these should go. Thanks for your contribution!

**Comment by tudorgergely** [comment]
@kkaefer I added the types to DefinitelyTyped and they just got merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51243.

Can I add a section in the README.md file explaining what developers using typescript should do? thanks
