### ISSUE TITLE
jsonlint breaks angular apps, replace it. 

### ISSUE THREAD

**Issue by raysuelzer** [mapbox/mapbox-gl-draw#844]
**mapbox-gl-js version**:   0.51.0
**mapbox-gl-draw version**: ^1.1.1

### Steps to Trigger Behavior

 1. `import * as MapboxDraw from '@mapbox/mapbox-gl-draw';`
 2. ng build

### Expected Behavior
Webpack / Angular should be able to build package
### Actual Behavior
```
WARNING in ./node_modules/jsonlint-lines/lib/jsonlint.js
684:16-23 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

ERROR in ./node_modules/jsonlint-lines/lib/jsonlint.js
Module not found: Error: Can't resolve 'fs' in 'C:\an\interact-frontend\node_modules\jsonlint-lines\lib'
ERROR in ./node_modules/jsonlint-lines/lib/jsonlint.js
Module not found: Error: Can't resolve 'path' in 'C:\an\interact-frontend\node_modules\jsonlint-lines\lib'
```

Please remove the dependecy on `jsonlint`, it is no longer supported or maintained and will not work for people using angular-cli.  We do not have an option to specify  `node` property since webpack.config is abstracted.

**Comment by hallo02** [comment]
Is there a workaround?

**Comment by The-End-Hero** [comment]
I have encountered the same problem

**Comment by MatlBatl** [comment]
I was in the same situation. This worked for me:

`import * as MapboxDraw from '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw';`

**Comment by laurenoldham1202** [comment]
Up until last week, I was able to use the workaround[ detailed here ](https://github.com/mapbox/mapbox-gl-draw/issues/850)in which you add this bit of code to your package.json file (at the same level as name, version, scripts, etc.):
`  "browser": {
    "fs": false,
    "path": false,
    "os": false
  },`

Worked up until I did a git rebase on my code today. The above solution `import * as MapboxDraw from '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw';` worked for me! +1

**Comment by silberjan** [comment]
Using a deep import like ` '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw';` is not really a solution. (see https://github.com/Microsoft/TypeScript/issues/20160#issue-275455127)

Ivy starts to complain about them already. It would be way better to either fork jsonlint-lines or use something else

**Comment by vinayakkulkarni** [comment]
Facing a similar issue in the Nuxt based Vue App

```diff
+ import * as MapboxDraw from '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw';
- import * as MapboxDraw from '@mapbox/mapbox-gl-draw';
```

This hack works successfully though.

**Comment by kkaefer** [comment]
You should use the packaged version in the `dist` folder to avoid bundling errors as @vinayakkulkarni pointed out. For those curious, [we're excluding the `path` and `fs` modules from being bundled](https://github.com/mapbox/mapbox-gl-draw/blob/18e9eb024910af88c337e136908f070c19ffc648/rollup.config.js#L21-L26). The geojsonlint module only uses them in the main function which we never call, so it's eliminated from the final build anyway.

**Comment by trygveaa** [comment]
@kkaefer: If we should use the version from the `dist` directory, why do you set `main: "index.js"` in `package.json`?

**Comment by deepaksslibra** [comment]
> ```diff
> import * as MapboxDraw from '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw'
> ```

Stuck on this right now 😆

**Comment by Yug33** [comment]
> import * as MapboxDraw from '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw'

 This is not working as well getting error 
```
./node_modules/@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.js
Module not found: Error: Can't resolve 'fs' in '/home/po/practice/mapbox/mapbox_test_1/node_modules/@mapbox/mapbox-gl-draw/dist'
```
