### ISSUE TITLE
new MapboxDraw() doesnt seem to work with angular 6

### ISSUE THREAD

**Issue by devcer** [mapbox/mapbox-gl-draw#850]
**mapbox-gl-js version**: 0.52.0
**mapbox-gl-draw version**: 1.1.1

### Steps to Trigger Behavior

 1. npm i mapbox-gl && npm i @mapbox/mapbox-gl-draw
 2. Include styles in angular.json and import mapbox using below lines
import * as mapboxgl from 'mapbox-gl';
import * as MapboxDraw from '@mapbox/mapbox-gl-draw';
 3. Initialise MapboxDraw as
    this.draw = new MapboxDraw();

This throws out an error 
ERROR in ./node_modules/jsonlint-lines/lib/jsonlint.js
Module not found: Error: Can't resolve 'fs' in '/home/Documents/projects/Project_name/node_modules/jsonlint-lines/lib'
ERROR in ./node_modules/jsonlint-lines/lib/jsonlint.js
Module not found: Error: Can't resolve 'path' in '/home/gaian/Documents/projects/Project_name/node_modules/jsonlint-lines/lib'

Any help?
### Expected Behavior
Should work

### Actual Behavior
Throws an error

**Comment by dishantagnihotri** [comment]
This is Obvious because front-end applications are not allowed to use File Systems. You can make it work by disabling the fs. Just place below object into your application's 
> package.json 

file and everything will work fine.
```

// - other obj's
},
  "browser": {
    "fs": false,
    "path": false,
    "os": false
  },
// - other obj's

```

**Comment by JuanJoMh09** [comment]
"browser": {
    "fs": false,
    "path": false,
    "os": false
  }

Add that on package.json

**Comment by JimmyRitter** [comment]
I'm actually changing my package.json file adding the code that you guys just commented but it doesn't seems to be working.
What I'm doing is adding " "browser": { "fs": false, "path": false, "os": false } " to package.json, saving the file, reinstalling the packages (I'm using yarn) and after the packages are installed, just running a "ng build". Maybe I'm missing something?
@dishantagnihotri @JuanJoMh09

**Comment by garrettgsb** [comment]
The solution proposed here did not work for me using Yarn in an React app.

The solution [here](https://github.com/mapbox/mapbox-gl-draw/issues/626#issuecomment-293366562) did, however:

Added to `webpack.config.js` as a top level key:

```
node: {
    fs: "empty"
  }
```

**Comment by kkaefer** [comment]
I recommend using the version in the dist folder to avoid problems with custom bundlers.
