### ISSUE TITLE
mapbox-gl-draw:  $yarn start, getting error in browser with sample project.

### ISSUE THREAD

**Issue by SoftShit** [mapbox/mapbox-gl-draw#859]
**mapbox-gl-js version**:  latest checked out from github
**mapbox-gl-draw version**: latest checked out from github

### Steps to Trigger Behavior
```
 1. $git clone https://.../mapbox-gl-draw
 2. $cd mapbox-gl-draw
 3. $yarn install
4.  $yarn start
```
### Expected Behavior
I should be able to go to a web browser and see the sample project on:
  * http://localhost:9967

### Actual Behavior
I get this in the browser:
**Cannot GET /**

View source:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```

Any help getting this sample project going would be appreciated.

**Comment by andrewharvey** [comment]
See under the README https://github.com/mapbox/mapbox-gl-draw#developing-and-testing you'll need to visit `http://localhost:9967/debug/?access_token=<token>`
