### ISSUE TITLE
Multipolygon support

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/mapbox-gl-draw#86]
also, polygons with holes and all that other fun stuff... hellz yeahhhhh bruh!

**Comment by jakepruitt** [comment]
:tiger:

**Comment by kelvinabrokwa** [comment]
@jakepruitt 🐼

**Comment by bsudekum** [comment]
@kelvinabrokwa have you every tried editing in qgis/ArcGIS? Might be helpful for inspiration.
