### ISSUE TITLE
Cannot find module 'envify' when using npm version of Mapbox draw

### ISSUE THREAD

**Issue by briandaviddavidson** [mapbox/mapbox-gl-draw#861]
**mapbox-gl-js version**: ^0.52.0
**mapbox-gl-draw version**: ^1.1.1

### Steps to Trigger Behavior

 1. `npm install @mapbox/mapbox-gl-draw --save` 
 2. Add `const MapboxDraw = require("@mapbox/mapbox-gl-draw")` to `index.js` file
 3. Create new Mapbox Draw 
```
const draw = new MapboxDraw({
  displayControlsDefault: false,
  controls: {
    line_string: true,
    trash: true
  }
});
```
 4. `npm start`

### Expected Behavior

Mapbox draw would load and be ready to use with a `line_string` and `trash` button.

### Actual Behavior
<img width="827" alt="screen shot 2019-01-23 at 3 49 57 pm" src="https://user-images.githubusercontent.com/2423402/51636577-9544a400-1f27-11e9-9941-95079e0bb5b2.png">

**Comment by kkaefer** [comment]
fixed
