### ISSUE TITLE
Draw two different style polygon

### ISSUE THREAD

**Issue by q869939686** [mapbox/mapbox-gl-draw#875]
**mapbox-gl-js version**:0.49
**mapbox-gl-draw version**:1.1.1

### Steps to Trigger Behavior
I am working a new scene recently
 1.I had new two objects from MabboxDraw with different styles.
 2.Add two controls in map
 3.And then i can have two different pen to draw polygons
### Expected Behavior
Draw two different styles of polygons,for example , red and blue polygon
 I cna switch pens between red and blue to draw different polygons
 And if i have two feature data collection,i can add to the map by red and blue polygon
 Editable too
### Actual Behavior
Error 'There is already a source with this ID'

**Comment by kkaefer** [comment]
This seems identical to https://github.com/mapbox/mapbox-gl-draw/issues/912. Closing this issue since the other one has more background information.
