### ISSUE TITLE
Drawing triangl 

### ISSUE THREAD

**Issue by grigvardanyan** [mapbox/mapbox-gl-draw#876]
Hi,
I want to draw rectangle  on some point or points on map does it possible?
Thanks!

**Comment by fc** [comment]
https://github.com/thegisdev/mapbox-gl-draw-rectangle-mode

**Comment by kkaefer** [comment]
@grigvardanyan This is a feature that could be accomplished with a [custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/MODES.md#creating-modes-for-mapbox-draw), but not something that we'll add to the core of this module.
