### ISSUE TITLE
Is there any method or parameter that makes the drawn graphic impossible to drag?

### ISSUE THREAD

**Issue by The-End-Hero** [mapbox/mapbox-gl-draw#886]

**Comment by awulkan** [comment]
I'm also interested in knowing this. Do we have to create our own mode for it?

**Comment by ryanhamley** [comment]
You can use the `Static` custom mode via [this plugin](https://github.com/mapbox/mapbox-gl-draw-static-mode).

**Comment by awulkan** [comment]
@ryanhamley I though static mode disabled all interaction, not just the ability to drag things.

**Comment by awulkan** [comment]
Any news regarding this? Is it still impossible to just disable the ability to drag a feature?
