### ISSUE TITLE
Drawing polygons like triangles and squares on layers instead of circles

### ISSUE THREAD

**Issue by nishchalpoornadithya** [mapbox/mapbox-gl-draw#917]
Hi there,
I am using "mapbox-gl": "^1.3.0".
So, in mapbox GL JS,
I would like to know if there is a way to draw polygons such as triangles and squares like circles on layers.
But the problem is I have to do this in a coordinate that is of the geoJson type: Point
{"type":"Point","coordinates":[307170.943,6679032.568]}

There was an example in the documentation to do this when with "type": "Polygon".
https://docs.mapbox.com/mapbox-gl-js/example/fill-pattern/

But i want to do it with Points just like how we are able to draw circles in place of points.

Note: I tried adding a sprite and plotted an icon using "icon-image" like this:
"layout": {
        "icon-image":"airport-15" ,
        "icon-size": 1
        }
But the problem is I I have more than 100 k points like this. So, rendering so many images is causing the map to lag too much. This doesn't happen when i use circles as i believe drawing is smoother than using images. 
Any help would be appreciated.

**Comment by kkaefer** [comment]
@nishchalpro I'm having some trouble understanding what visual look you want to achieve. Could you please post a mockup (e.g. from a graphics program or other map) that illustrates this?

**Comment by hexadeciman** [comment]
@kkaefer 
Imagine a map that has triangles drawn on each point instead of a circle. I'm facing the same challeng as @nishchalpro

**Comment by puka-tchou** [comment]
I face the same problem: we need to enable the user to choose an icon to display on each point a user may place on the map, but, without some help or documentation we are clueless for now. I'll add a comment if I find a workaround.

**Comment by SnailBones** [comment]
If I'm understanding the question correctly, it should be possible to achieve this with either custom markers ([example](https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/)) or a symbol layer ([example](https://docs.mapbox.com/mapbox-gl-js/example/geojson-markers/)) in GL JS without using mapbox-gl-draw. Something like this (untested):

```js
map.on('click', (e) => {
    const el = document.createElement('div');
    el.className = 'marker';
    el.style.backgroundImage = 'your_custom_icon.png';
    el.style.backgroundSize = '100%';
    new mapboxgl.Marker(el)
      .setLngLat(e.lngLat)
      .addTo(map);
    }
});
```

**Comment by puka-tchou** [comment]
Yep, that's precisely what I went with, but it causes some problems down the line and funky code (but maybe that's coming from me) to ensure that the marker is not duplicated when the drawings are moving. For future readers, here's what I ended up with:

```
let icons = [];

map.on('draw.render', renderEvent);

async function renderEvent() {
	icons.forEach((icon) => {
		try {
			icon.remove();
		} catch (error) {
			//
		}
	});

	icons = await renderCustomIcon(map);
}


/**
 * @param {{draw: MapboxDraw}} map
 */
async function renderCustomIcon(map) {
    const data = map.draw.getAll();
    /** @type {mapboxgl.Marker[]} */
    const markers = [];

    data.features.forEach((feature) => {
        if (feature.geometry.type === "Point") {
            /** @type {[number, number]} */
            const lngLat = [feature.geometry.coordinates[0], feature.geometry.coordinates[1]];
            const iconName = "fa fa-example";
            const element = document.createElement("span");
            element.className = iconName;

            const marker = new mapboxgl.Marker({
                element,
                draggable: false,
            })
                .setLngLat(lngLat)
                .addTo(map);
            markers.push(marker);
        }
    });

    return markers;
}
```

**Comment by puka-tchou** [comment]
Sorry to ask, but why this issue was closed? The solution I mentioned above is just a hack and a robust solution should be provided by `mapbox-gl-draw` (at least in my opinion).

**Comment by SnailBones** [comment]
The original issue here describes a performance issue in `mapbox-gl-js`, not `mapbox-gl-draw`, so I've closed this issue as it's not pertinent to this repository.

@puka-tchou If I understand your use case correctly, you're looking for a simpler way to enable custom styling of the points making up polygons/polylines within `mapbox-gl-draw`? Could you open a new issue for this feature request and include an image or mockup of what you are looking to achieve? Thanks!

**Comment by RomainGratier** [comment]
I am having the same issue. Is there any following issue?
