### ISSUE TITLE
Different browser behaviour/performance

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-draw#92]
I think this will be a really useful plugin but I've noticed different performance and some issues on different browsers:

-Chrome- generally all works ok, although maybe its just me but I think performance gets significantly worse at higher zoom levels? Sometimes shapes do not complete and it starts to get buggy. It seems to use a huge amount of processing power - i'm using a macbook pro and the fan goes crazy when zoomed in and drawing shapes. However, when i'm zoomed out it all seems to work fairly smoothly. I thought it might be because at higher zoom levels more features are shown on my map, but even in completely empty sections of map the same happens. This may not be browser specific.
-Safari - seems to have the best performance generally and everything works well
-IE11 - doesn't work at all (the library doesn't load), will it be possible? Mapbox-gl works ok generally
-Edge - very poor performance (browser console says 'Unable to get property 'moveVertex' of undefined or null reference' when editing (however mapbox-gl seems to have bigger issues with Edge in the current build (0.11.1) - I think that is a known issue https://github.com/mapbox/mapbox-gl-js/issues/1437)
-Firefox - very poor performance, erratic/laggy behaviour when editing, editing shape remain when deleting shape.

Hope that helps!

**Comment by kelvinabrokwa** [comment]
@joedjc thanks for opening this issue! Performance is definitely the biggest hurdle to overcome before this library is generally useable. There have been a number of issues already addressing this (https://github.com/mapbox/gl-draw/issues/43, https://github.com/mapbox/gl-draw/issues/89)

It is the focus of my [current PR][pr].

Next moves is to remove [Immutable.js][immut] from gl-draw. From my previous profiling it seems like it has [quite a bit of overhead][prof]. After that I'm going to look at implementing translations with fewer calculations and go from there.

Please feel free to take a look at the source and let me know when you find performance pitfalls!

[pr]: https://github.com/mapbox/gl-draw/pull/91
[immut]: https://github.com/facebook/immutable-js
[prof]: https://github.com/mapbox/gl-draw/issues/43

**Comment by mcwhittemore** [comment]
@joedjc - version 0.1.2 shipped a bunch of changes, can you confirm if this solved your problem?

**Comment by joedjc** [comment]
@mcwhittemore - It is much better and consistent across browsers (chrome, safari, edge and firefox) - my laptop no longer goes into meltdown when editing features which is good!

However, it still doesn't initialise at all on IE11. I get the following error:

SCRIPT438: Object doesn't support property or method 'assign'
mapboxgl.draw.js (12,29552)

It would be great if it could work on IE11 as mapbox-gl supports it and it's still a popular browser for now.

**Comment by mcwhittemore** [comment]
@joedjc - I don't think we're using Object.assign in many spots. Want to make a PR and fix that up?

**Comment by joedjc** [comment]
I've had a go but github is pretty new to me as i'm a fairly amateur coder so not sure if it worked, I got an error saying I don't have permission when pushing the changes.

However it was a simple change - I changed each of the 'Object.assign' methods to the following and it seemed to work:

Line 57 replaced with: 
for(var key in options) {
        this.options[key] = options[key];
    }

and...

Lines 225 & 240 replaces with:
for(var key in this.options.styles[style.id]) {
      style[key] = this.options.styles[style.id][key];
}
