### ISSUE TITLE
This library is fundamentally broken

### ISSUE THREAD

**Issue by donnyv** [mapbox/mapbox-gl-draw#929]
First `map.removeControl(draw);` throws an error because its not properly implemented. 
Second the event `draw.render` constantly fires when the mouse is moving.
Third if you try to clean up all the layers this creates, which there are  22, and remove the source. It throws an error because its still capturing features using `queryRenderedFeatures()` while the mouse is moving. 

This plugin trashes your map context and then gives you no way to clean it up.

**Comment by stevage** [comment]
Hi @donnyv. You might be new to commenting on public repos? Your language is really harsh, and not very helpful in terms of actually getting any of those issues addressed.

If you want to be helpful, you might consider raising an issue for each of the different defects you have noticed, without some of the inflammatory language. Cheers.

**Comment by donnyv** [comment]
No I'm not new to commenting. I just made the mistake of commenting while being frustrated with the library. I should of waited. I ended up fixing my issue by not using this library. I ended up building my own, with snapping.
