### ISSUE TITLE
Change color of polygons?

### ISSUE THREAD

**Issue by mattoni** [mapbox/mapbox-gl-draw#931]
I went through the examples for styling polygons, but I want to do something very simple: 

I need to allow each polygon to have a separate, user defined color. How can I go about using the styles block to achieve this? I see there's a filter option, but I have no idea how to identify a polygon and color it properly.

```
 {
          id: 'gl-draw-polygon-fill',
          type: 'fill',
          filter: ['all', ['==', '$type', 'Polygon'], ['!=', 'mode', 'static']],
          paint: {
            'fill-color': '#D20C0C',
            'fill-outline-color': '#D20C0C',
            'fill-opacity': 0.1,
          },
        },
```

Any help is greatly appreciated, thanks!

**Comment by kkaefer** [comment]
@mattoni You can do this with [data driven styling](https://docs.mapbox.com/help/glossary/data-driven-styling/): If you add properties to your features, you can use those property values in `fill-color` to determine the color.

**Comment by rctngle** [comment]
I found this closed ticket when having an issue with data-driven styling. My features have a boolean property `currentUserCreated` but the below custom style does not have any effect. Would much appreciate if anyone could suggest why?

```
{
	"id": "polygon-unselected-fill",
	"type": "fill",
	"filter": ["all", ["==", "$type", "Polygon"], ["!=", "active", "true"]],
	"paint": {
		"fill-color": [
			"case",
			["==", ["get", "currentUserCreated"], true],
			"#ff0000",
			"#00ffff"
		],	
		"fill-opacity": 0.4
	}
}
```

**Comment by hmendezm** [comment]
I have a similar issue with the below data-driven styling.  I think the issue is that when the polygon is drawn the data source of the layer is created and properties always are empty. And Although you update after it does not work because the data source will not update. is there a way to pass properties when the user starts drawing the polygon?
```
 // polygon fill
          {
            'id': 'gl-draw-polygon-fill',
            'type': 'fill',
            'filter': ['all', ['==', '$type', 'Polygon'], ['!=', 'mode', 'static']],
            'paint': {
              'fill-color': ['get', 'color'],
              'fill-outline-color': '#D20C0C',
              'fill-opacity': 0.1
            }
          },
```

**Comment by hmendezm** [comment]
Just in case someone comes in this direction. I did the following and it is working
```
 new MapboxDraw({
       // other options
        userProperties: true
}

//sets color attribute
this._drawControl.setFeatureProperty(featureId, 'color', value); 
```

**Comment by kashishgadhiya** [comment]
Hey everyone, coming to this late but I ran into the same problem and ended up building a package that solves exactly this.
[maplibre-gl-multiple-color-draw](https://www.npmjs.com/package/maplibre-gl-multiple-color-draw) — lets you assign a different color to each drawn feature (polygons, lines, freehand shapes) with a color picker UI built in. Also includes TypeScript support and GeoJSON export.
` npm install maplibre-gl-multiple-color-draw`
Hope it helps anyone still landing on this issue!
