### ISSUE TITLE
What's the future of this project?

### ISSUE THREAD

**Issue by fc** [mapbox/mapbox-gl-draw#933]
Just curious.
The project has had very few updates and it seems to be in maintenance mode.

**Comment by fc** [comment]
@asheemmamoowala @vakila @ansis

**Comment by asheemmamoowala** [comment]
Thanks for raising this question. We know that many developers rely on GL-Draw to supplement the map visualization capabilities in GL-JS, and enabling these use cases is important. 
As you and others have pointed out, it's been a challenge to stay on top of this issue queue as well as GL-JS' in addition to that of numerous other libraries in the Mapbox GL ecosystem.
Early next year, we are planning to conduct an internal review of the libraries that the GL-JS team will maintain official ownership of. We'll keep you posted on what you can expect re: GL-Draw then.

**Comment by benrudolph** [comment]
Does closing this mean that there is a future or there is not a future?

**Comment by kkaefer** [comment]
There is a future, but this ticket isn’t actionable, so I closed it.

**Comment by benrudolph** [comment]
nice! that's awesome to hear

**Comment by fc** [comment]
@benrudolph check the commit history of the repos, @kkaefer is killing it! He's been categorizing and prioritizing PRs, issues and bugs, as well as merging PRs, and ultimately breathing life back into `mapbox-gl-draw`. Thank you so much @kkaefer !

**Comment by benrudolph** [comment]
i did as soon as i got a notification on this project 💪 💪

**Comment by Quietly-20201113** [comment]
It's 2024 now. If bugs are not responded to or fixed, is there still a future?
