### ISSUE TITLE
Can't draw a polygon over a imageSource layer

### ISSUE THREAD

**Issue by rrecio** [mapbox/mapbox-gl-draw#934]
**mapbox-gl-js version**: 1.5.0
**mapbox-gl-draw version**: 1.1.2

### Steps to Trigger Behavior
 1. See the video: https://youtu.be/FR2iXweik3s?t=34 (Starts at 00:34)

### Expected Behavior
See the polygon tool over the image so I can draw the polygon correctly

### Actual Behavior
The polygon tool lines are rendered behind the image layer

### Additional context
This is how I'm rendering the image in the map:

```
    this.map.addSource('uploadedImage', {
      type: 'image',
      url: imageURLString,
      coordinates: this.coordinates
    });

    this.map.addLayer({
      id: 'uploadedImageOverlay',
      source: 'uploadedImage',
      type: 'raster',
      paint: {
        'raster-opacity': 1
      }
    });
```

**Comment by rrecio** [comment]
This is how I'm rendering the image in the map:

```
    this.map.addSource('uploadedImage', {
      type: 'image',
      url: imageURLString,
      coordinates: this.coordinates
    });

    this.map.addLayer({
      id: 'uploadedImageOverlay',
      source: 'uploadedImage',
      type: 'raster',
      paint: {
        'raster-opacity': 1
      }
    });
```

**Comment by fc** [comment]
Question: is the layer you are adding added before you add the mapbox-gl-draw control?  Try putting your code somewhere after you call `addControl(draw)` if you are not already doing that.

**Comment by rrecio** [comment]
@fc Thank you, Clay! I tried what you said but then the 'uploadedImage' doesn't show up (screenshot below), it's probably rendered behind the map!? I'll take a look at the other layers you referenced and see if I can figure it out.

<img width="1145" alt="Screen Shot 2019-12-11 at 9 07 06 AM" src="https://user-images.githubusercontent.com/52694/70620299-a6f17180-1bf5-11ea-89c3-3adf5dcd0cdf.png">

You can see my entire source code at this gist: https://gist.github.com/rrecio/bec6a419b3a0f05549fb2561a0f91fd4

**Comment by rrecio** [comment]
@fc I debug this.map.style.layers and saw there's a 'gl-draw-polygon-fill-inactive.cold'. So adding the layer before it worked! :) Thank you for your insight!
