### ISSUE TITLE
Drag performance in Chrome

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/mapbox-gl-draw#94]
What is this `(program)` business?

![](https://cloud.githubusercontent.com/assets/7795202/10674766/c15494bc-78ca-11e5-8b2d-ccda966ecddd.png)

**Comment by mh166** [comment]
Maybe this SO answer can help you a bit: [Slow javascript execution in chrome, profiler yields (program)](http://stackoverflow.com/a/9574976/3380671).
