### ISSUE TITLE
onDrag not firing for Custom Modes

### ISSUE THREAD

**Issue by JamesLMilner** [mapbox/mapbox-gl-draw#961]
**mapbox-gl-js version**:  1.6.1
**mapbox-gl-draw version**: 1.1.2

### Steps to Trigger Behavior

 1. Create a custom mode, with an `onDrag` handler
 2. Use the custom mode in conjunction with mapbox-gl-draw
 3. The handler never fires

### Expected Behavior

The onDrag handler would fire upon dragging

### Actual Behavior

The handler never fires

**Comment by texels** [comment]
I am seeing the same thing. Did you have a solution?

**Comment by JamesLMilner** [comment]
I think if I remember correctly, onDrag is handled by `DirectSelect` mode
