### ISSUE TITLE
Possibility to select feature programmatically  

### ISSUE THREAD

**Issue by BlitZz96** [mapbox/mapbox-gl-draw#965]
I have disabled default toolbar and created my own, in this case, I would like to "highlight" a feature if I click it in a menu (Outside of map).

I saw in the docs there was a styling feature available: `active`. And this would work good for my purpose.

Is it possible to select a drawn polygon via its feature_id?

**Comment by wurmrobert** [comment]
I would also need that functionality.

**Comment by alecf** [comment]
you can do this with `draw.changeMode('simple_select', { featureIds: [featureId] })`

where `featureId` is the value of `feature.id` for the feature you wish to select.

**Comment by wurmrobert** [comment]
Merci @alecf  that that works perfect 👍

**Comment by viceodev** [comment]
Amazing. Thank you very much @alecf .This was really helpful

**Comment by OchiengHosea** [comment]
Ahsante
