### ISSUE TITLE
Release version 1.2?

### ISSUE THREAD

**Issue by alecf** [mapbox/mapbox-gl-draw#966]
**mapbox-gl-js version**: 1.7
**mapbox-gl-draw version**: 1.1

Is there any chance of releasing the 1.2 that has been under development for the past few months? 

At minimum this has been a hassle because there seem to be slight docs discrepancy in the docs, some kind of "rectangle mode" is mentioned, among other thigns

Here's the diff:

https://github.com/mapbox/mapbox-gl-draw/compare/v1.1.2...v1.2.0-beta.1

**Comment by Primajin** [comment]
I guess this is done now.
https://github.com/mapbox/mapbox-gl-draw/releases/tag/v1.2.0
