### ISSUE TITLE
Strange functioning/api

### ISSUE THREAD

**Issue by usb248** [mapbox/mapbox-gl-draw#971]
Hi,

  Question. I need to manage meta data on points. So points are considered as "vertices".
1 - Why i can't set/retrieve meta data on vertices ? (https://github.com/mapbox/mapbox-gl-draw/blob/master/src/api.js#L49 why always empty ? why always only selected ? :confused:
2 - When i delete a point, i get nothing in **draw.delete** callback, this callback isn't called, why :confused: ? So how to know which point is deleted ? i don't understand this behavior.
3 - how to detect when a new point is created ? **draw.update** isn't called too...

I need to manage points in a database in order to store paths and get points coordinates from linestring feature is not enough.
An idea how to achieve this with mapbox-gl-draw... ?

Thanks

**Comment by usb248** [comment]
dead project, i switch lib

**Comment by coupez** [comment]
@usb248 what did you switch to?

**Comment by usb248** [comment]
mine
