### ISSUE TITLE
[Feature] - Display draw tools popover in other language than english

### ISSUE THREAD

**Issue by kara22** [mapbox/mapbox-gl-draw#988]
It would be very helpful for our users to have this content in french

![image](https://user-images.githubusercontent.com/21340608/83021961-171c7400-a02b-11ea-8c2c-09d31c2512b0.png)

Is it possible to add a locale system ?

**Comment by nzjs** [comment]
You can achieve this with some simple js:

```js
var ls = document.getElementsByClassName("mapbox-gl-draw_line"); 
ls[0].setAttribute('title', 'Outil linestring (l)');
```

**Comment by Strongleong** [comment]
This is not a good solution. I think there is need to be a something like [that](https://gis.stackexchange.com/a/356772)

Sorry for my bad English :sweat_smile:
