### ISSUE TITLE
V1.2.0, with ES6 module change can no longer use require?

### ISSUE THREAD

**Issue by jaybo** [mapbox/mapbox-gl-draw#997]
**mapbox-gl-js version**: 1.11.0
**mapbox-gl-draw version**: 1.2.0

### Steps to Trigger Behavior

 1.  Had working code using:
`MapboxDraw = require("@mapbox/mapbox-gl-draw");`
 2. Yarn upgrade to  MapboxDraw 1.2.0
 3. _require_ no longer works.  Needed to change to:
`import MapboxDraw from "@mapbox/mapbox-gl-draw";`

Documentation in **Readme.md** page needs updating, or is this some other issue?

**Comment by ericclemmons** [comment]
This is actually a bigger problem when adding maps within a project like Next.js:

```
event - build page: /
wait  - compiling...
error - ./node_modules/jsonlint-lines/lib/jsonlint.js
Module not found: Can't resolve 'fs' in '.../node_modules/jsonlint-lines/lib'
.../node_modules/@mapbox/mapbox-gl-draw/index.js:1
import runSetup from './src/setup';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at eval (webpack-internal:///@mapbox/mapbox-gl-draw:1:18)
    at Object.@mapbox/mapbox-gl-draw (.../.next/server/static/development/pages/index.js:234:1)
```

**Comment by adrianababakanian** [comment]
Thank you for opening @jaybo , you are correct that the readme should be updated to use `import` rather than `require`, since v1.2.0 includes an upgrade to ES6 as noted in the [changelog](https://github.com/mapbox/mapbox-gl-draw/blob/main/CHANGELOG.md).

**Comment by adrianababakanian** [comment]
@ericclemmons thank you for your feedback, would you be able to open a separate issue expanding on the details of the problem you are seeing? For example, some additional context on your use case, whether the same `import` statement was working with a version of GL Draw earlier than v1.2.0, etc.

**Comment by nogashimoni** [comment]
Any news on this? I'm getting 'SyntaxError: Cannot use import statement outside a module' even though I use import and not require

**Comment by nrgapple** [comment]
This is still an issue and does not work with nextjs

**Comment by doliolarzz** [comment]
Same, have you find any way to patch it? # # #

> This is still an issue and does not work with nextjs

**Comment by doliolarzz** [comment]
@nrgapple This library doesn't work on Server side rendering (as you can see there's no .cjs in its source code).
There's a workaround which load the `mapbox-gl-draw` dynamically, see the code in the sandbox below:
https://codesandbox.io/s/young-smoke-xqo42?file=/pages/index.js

**Comment by bradgreens** [comment]
Similar as @doliolarzz, I converted my map component to a [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import) instead of testing for the `browser` presence.
